target/goalert

web/src/package.json
web/src/yarn.lock

Although we were using `3.2.1` from the lockfile, the `package.json` was set to version `3`, which includes an unstable release. This PR updates the `package.json` to ensure that a stable release is always installed for this package. `yarn install` has been run as well to ensure the lockfile is up to date.

ui dependencies: webpack-dev-server upgrade to stable version

---

devtools/ci/dockerfiles/goalert/Dockerfile

Update the default bind address from localhost to wildcard in the goalert/Dockerfile.
Depending on docker/environment configuration, mapping ports to localhost (within the container) may not work, giving users "connection refused" errors when using the container as documented.
This PR sets the default address for the container to the wildcard address (within the container) on the same port, resolving the issue.

container: fix default listen address

---

notification/twilio/validation.go
validation/validate/phone_test.go
web/src/app/contact-methods/components/ContactMethodForm.js
web/src/app/contact-methods/components/VerificationForm.js
web/src/app/users/UserContactMethodForm.js
web/src/app/users/util.js
web/src/app/users/util.test.js

Allow for Mobile numbers from the UK (+44) to be used in GoAlert.
Only US and Indian numbers are avaliable at the moment, we need to be able to use UK based numbers for alerting 
Fixes #21
Users can now select a UK phone number when creating a new contact method

contactmethod: allow UK (+44) numbers

---

devtools/runjson/ci-cypress.json
devtools/runjson/localdev-cypress-prod.json
devtools/runjson/localdev-cypress.json
web/src/cypress/support/config.ts

The fake credentials used for running tests against the mock Slack server look real (in fact they are probably indistinguishable). The values being used were randomly generated at some point by the mock server with the default seed value.
This PR replaces them with ones that are zeroed out, hopefully making it apparent that they are dummy values. :)

slack/testing: make fake slack creds look more fake

---

config/config.go
devtools/mockslack/validate.go

Some Slack tokens have an alternate numeric section consisting of 10-digits instead of 12. This PR updates the validation regex to accept between 10 and 12, allowing both formats.
Fixes #33

slack: accept tokens with 10-digit sections

---

config/config.go
docs/getting-started.md
graphql2/mapconfig.go
validation/validate/ascii.go

This PR loosens the validation requirements for things like client IDs, API keys, etc.. that come from external systems and stored in config. Previously config validation would match against strict regular expressions.
Since GoAlert doesn't actually parse or otherwise require specific formats, this only caused confusion as the external systems could provide/change said formats making it impossible for GoAlert to be configured correctly until a code fix/regex update was deployed.
Additionally, the Getting Started guide was updated for the new Mailgun UI.
Closes #43 
Client IDs, secrets, API keys (e.g. Mailgun, Slack) are now only required to be <128 ASCII characters without formatting …

config: loosen key validation & guide updates 

---

app/concurrencylimiter.go
app/concurrencylimiter_test.go
app/middlewarereqlimit.go

This PR introduces request queueing to the concurrency limiter.
The concurrency limiter was designed to limit the number of simultaneous integration keys, service, and/or user-requests that are processed concurrently per-instance.
The present-day implementation limits concurrency, effectively isolating busy consumers, but all "pending" requests are then processed in random order. This results in latency spikes under load (per individual key) and 502 responses due to "backend timeout".
This change introduces a FIFO queue for all pending requests instead of the random group.
- For requests beyond the maximum (250 per key), they are immediately returned with status code 429 (too many requests)
- Requests stuck in the queue for longer than 25s are also returned with 429 …

http: request queue and timeouts

---

Makefile

This updates `make smoketest` to depend on `install` instead of `generate`.
Closes #51 
Internally the smoketests use the installed binary, and generate is already done as-needed when the `install` task is run. So this will also result in preventing the accidental running of smoketests against outdated code.

dev: change `smoketest` dep from `generate` to `install`

---

web/src/app/users/UserContactMethodList.js

Hides the `Reactivate` button on mobile as it overlaps ListItem text.
Adds a reactivate button the a contact method's other actions menu if disabled, regardless of the current breakpoint.

contact methods: hide reactivate button on mobile/always have option within other actions

---

graphql2/graphqlapp/contactmethod.go
user/contactmethod/store.go
web/src/app/dialogs/FormDialog.js
web/src/app/users/UserContactMethodEditDialog.js
web/src/app/users/UserContactMethodForm.js
web/src/app/users/UserContactMethodVerificationDialog.js
web/src/app/users/UserContactMethodVerificationForm.js
web/src/cypress/integration/profile.ts

This PR fixes issues around contact method management in preparation for the next release.
- Fixes "A verification code has been sent to undefined" message for new contact methods
- Fixes a regression that prevented pasting pre-formatted numbers into the contact method field
- Fixes the "too many messages" error when opening the reactivate dialog
- Fixes the "Retry" button appearing in the reactivate dialog when it had not been submitted
It is no longer possible to edit a contact method value. This was done to ensure consistency in logs and verification.

profile: contact method management fixes

---

web/src/app/dialogs/FormDialog.js
web/src/app/services/ServiceDeleteDialog.js

This fixes a couple of issues where error messages were not displayed in dialogs.
- Delete service errors not displaying
- Long dialogs didn't show any error messages
- The service dialog issue was due to the field `escalationPolicyID` not matching `escalationPolicyId` (capitalization).
- The other dialogs were actually rendering the errors, but the error sections were collapsed into a scrollable container rather than expanding the dialog content (which scrolls already).

dialogs: fix cases where errors were not displayed

---

web/src/app/util/Search.js
web/src/cypress/support/page-nav.ts
web/src/cypress/support/page-search.ts

This PR fixes focus issues regarding the search bar on mobile and desktop.
Additionally, it ensures that the search string is visible on mobile if results are being filtered.
- Unable to type in search bar without losing focus
- When canceling the mobile search bar, the search state is cleared
- When loading the page, if a search is present, the mobile search bar is shown
The `Search` component was converted to React Hooks.

search: focus fix

---

.dockerignore
Makefile
devtools/ci/dockerfiles/goalert/Dockerfile
web/handler.go

This PR updates the primary Dockerfile to be all-inclusive to build a GoAlert container using the multistage build feature of Docker.
It is possible to build using only local data via:
```bash
go mod vendor # Allows passing Go deps to the final build container
make bin/goalert BUNDLE=1 # Build all dependencies ahead of time
docker build -t my-image -f devtools/ci/dockerfiles/goalert/Dockerfile .
```
Node and Go dependencies will be downloaded as-needed otherwise.
Additionally, UI timestamp/version info has been reworked to be provided by the GoAlert binary at runtime rather than embedded in `index.html` directly. This ensures information is consistent from the server binary and server responses. Version information is only provided for embedded assets, not proxied.
^ with …

build: Dockerfile update

---

web/src/app/actions/main.js
web/src/app/lists/QueryList.js
web/src/cypress/support/fail-fast.ts
web/src/package.json
web/src/yarn.lock

This PR fixes the pagination Cypress tests.
The issue was actually a bug, if you were on any page past the first, and clicked on a nav link the page would be stuck in a loading state.
For example:
1. Click on rotations
1. Navigate to the next page
1. Click the rotations link again
1. Observe broken list
The fix was to change the `PaginatedList` key value from the search param to the router location key (which updates on any navigation change). In doing so discovered that the search bar was causing a double-page-navigation on load which caused intermittent failures. That was fixed by updating the URL actions to only dispatch a navigation action if the parameter changes.
Also:
- Updated `cypress` to 3.4.1, resolving the lodash warning
- Updated …

cypress: fix pagination tests

---

web/src/app/schedules/ScheduleCalendar.js

Closes #35. This PR fixes an issue where the height and font were set with the `webkit` vendor prefix, which Firefox does not support. These values are now represented using our `theme` from material-ui, and `rem` for the height.

ui: firefox support for schedule calendars

---

web/src/app/rotations/RotationUserList.js
web/src/app/services/components/OnCallForService.js

This PR removes padding on a service's on-call users list to match schedule assignments, alerts, and contact methods. Also removes the padding for a rotation's participants list.
Before:
After:

ui: padding consistency around rotation participants and service on-call user lists

---

web/src/app/admin/AdminConfig.js
web/src/app/alerts/components/AlertsList.js
web/src/app/alerts/components/CheckedAlertsFormControl.js
web/src/app/details/DetailsPage.js
web/src/app/escalation-policies/PolicyStepForm.js
web/src/app/lists/PaginatedList.js
web/src/app/schedules/ScheduleAssignedToList.js
web/src/app/schedules/ScheduleForm.js
web/src/app/schedules/ScheduleOverrideList.js
web/src/app/util/FilterContainer.js
web/src/app/wizard/WizardForm.js

This PR removes any inconsistencies between `Grid` components being rendered with both the `item` and `container` properties, when in most use cases it should be one or the other. In some cases here, a grid was not needed at all has been subsequently removed.
Also updates the few places where we use `spacing={3}` to `spacing={2}`, which is what we mainly use across GoAlert.

ui: grid item container consistency

---

web/src/app/dialogs/components/DialogTitleWrapper.js

This is a small PR that adjusts the padding of form dialogs such that extra whitespace isn't rendered if a subtitle isn't present, as well as removes the bottom padding on the dialog title headers so it doesn't feel like there is lots of empty space between the title and the content.

ui: adjust form dialog spacing

---

web/src/app/users/UserContactMethodVerificationDialog.js
web/src/app/util/RequireConfig.js

Adds a new hook `useConfigValue` that is a bit more natural to use than the raw `useConfig` hook.
Usage:
```js
const [fromNumber] = useConfigValue('Twilio.FromNumber')
```
- also fixes `mapConfig`

hooks: add useConfigValue hook

---

app/healthcheck.go
notification/twilio/voice.go
retry/do.go
sqltrace/connector.go
sqltrace/simpleconnector.go

This PR updates the DB driver wrapper to retry connecting to the DB when the connection attempt fails. It also updates the health check to ignore DB state (as UI can and should still be served).

db: retry on connection failure

---

web/src/app/main/NewApp.js

added padding to the main tag for cards to not appear cutoff on moble.

ui: mobile card padding fix

---

web/src/app/users/UserDetails.js

This PR fixes the "Provided by Gravatar" text so that it is centered under the profile avatar at all breakpoints.
The position of the text caption under the current user's profile avatar was misaligned at different breakpoints, as seen in the provided before/after screenshots.
Before:
<br>
After:

ui: fix alignment of "Provided by Gravatar" under user profile avatar

---

web/src/app/escalation-policies/PolicyStepForm.js

This PR fixes the 'optional' text field on escalation policy step form so that it is left-aligned under the preceding text.
Before:
<hr/>
After:

ui: fix 'optional' text align on escalation policy step form

---

devtools/ci/tasks/scripts/test-integration.sh

Update browser debug tgz files to only include screenshots and videos.

ci: only add screenshots and videos to debug tgz

---

genericapi/handler.go

Our heartbeat endpoint was allowing all HTTP methods on `/api/v2/heartbeat/` -- this change is to enforce allowing `POST` requests only.  If request method is not `POST`, client will receive a `HTTP 405 Method Not Allowed` status code as response.

heartbeat: adjust heartbeat endpoint to only allow POST requests

---

web/src/app/details/DetailsPage.js

Adds link / href to the `ChevronRight` icon that is displayed on Details Pages.  Currently, clicking directly on this button doesn't actually do anything.

ui: add href to ChevronRight button on details pages

---

web/src/app/admin/AdminConfirmDialog.js
web/src/cypress/integration/admin.ts
web/src/cypress/support/page-search.ts

This PR adds more assertions (e.g. `cy.get('x').should('have.value', val)`) such that retry logic is hardened as cypress navigates throughout the page.

cypress: more assertions for admin and page search tests

---

web/src/app/dialogs/components/ConfirmationDialog.js

This PR adds the old client to ack all/close all functionality for service alerts.

apollo: add old client to serviceAlerts

---

web/src/app/services/ServiceDeleteDialog.js

Converts the `ServiceDeleteDialog` to hooks
- Fixes a race condition where deleting a service results in a not-found page instead of redirecting to the list page.

services: convert ServiceDeleteDialog to hooks

---

web/src/app/admin/AdminConfirmDialog.js
web/src/app/apollo.js
web/src/app/escalation-policies/PolicyDeleteDialog.js
web/src/app/escalation-policies/PolicyEditDialog.js
web/src/app/escalation-policies/PolicyStepCreateDialog.js
web/src/app/escalation-policies/PolicyStepEditDialog.js
web/src/app/rotations/RotationAddUserDialog.js
web/src/app/rotations/RotationEditDialog.js
web/src/app/rotations/RotationSetActiveDialog.js
web/src/app/rotations/RotationUserDeleteDialog.js
web/src/app/schedules/ScheduleEditDialog.js
web/src/app/schedules/ScheduleOverrideCreateDialog.js
web/src/app/schedules/ScheduleOverrideDeleteDialog.js
web/src/app/schedules/ScheduleOverrideEditDialog.js
web/src/app/schedules/ScheduleRuleCreateDialog.js
web/src/app/schedules/ScheduleRuleDeleteDialog.js
web/src/app/schedules/ScheduleRuleEditDialog.js
web/src/app/services/HeartbeatMonitorCreateDialog.js
web/src/app/services/HeartbeatMonitorDeleteDialog.js
web/src/app/services/HeartbeatMonitorEditDialog.js
web/src/app/services/ServiceDeleteDialog.js
web/src/app/services/ServiceEditDialog.js
web/src/app/users/UserContactMethodCreateDialog.js
web/src/app/users/UserContactMethodDeleteDialog.js
web/src/app/users/UserContactMethodEditDialog.js
web/src/app/users/UserContactMethodVerificationDialog.js
web/src/app/users/UserNotificationRuleCreateDialog.js
web/src/app/users/UserNotificationRuleDeleteDialog.js
web/src/app/util/QuerySetFavoriteButton.js

This PR updates the default apollo client to `awaitRefetchQueries` by default (no effect if `refetchQueries` are not set), set a default `pollInterval` and use `cache-and-network` as the default `fetchPolicy`
The values provided are the ones used by our `Query` component.

apollo: set default options

---

app/cmd.go
app/startup.go
devtools/resetdb/main.go
engine/processinglock/lock.go
migrate/migrate.go
smoketest/migrations_test.go
switchover/dbsync/shell.go
util/sqlutil/listener.go

This PR updates the migrate package to operate on a connection string and use pgx directly instead of `*sql.DB`. This ensures that GoAlert establishes it's connection pool *after* any new types/tables have been created.
- Fixes an issue where migrations would fail to apply during engine cycles

migrate: use connection string instead of *sql.DB

---

escalation/store.go
smoketest/systemlimits_test.go

This PR moves UUID generation for EP step actions to the app layer (rather than from Postgres) as the latter, using `gen_random_uuid()` can return the same value multiple times on some systems.
It was found because the EP method to add a new target had `ON CONFLICT DO NOTHING` which would swallow the duplicate primary key error when an error was expected as part of the system-limits test.

smoketest: fix ep action limit flakyness

---

web/src/app/schedules/ScheduleRuleForm.js
web/src/app/schedules/ScheduleRuleList.js
web/src/app/schedules/ScheduleTZFilter.js

This PR fixes a regression that broke the TZ filter on the schedule assignments page.

schedules: pass schedule ID to tz filter

---

devtools/ci/dockerfiles/build-env/Dockerfile

Updates the version of Go in the build-env container to 1.13.1

go: update build-env to use Go 1.13.1

---

web/src/app/dialogs/FormDialog.js

Previously we weren't using padding around the form in our form dialogs. With the addition of dialog content on our forms, the padding has changed from what it was originally designed as. This PR keeps the content (needed for proper overflow scrolling), but removes the padding.

form dialogs: revert to old content padding

---

alert/search.go
graphql2/graphqlapp/alert.go

This PR fixes pagination on the `alerts` query by setting the `After` cursor data and fixing a syntax error in the query.

graphql: fix alerts query pagination

---

smoketest/addrules_test.go

This PR fixes a timing race that caused the AddRules test to sometimes fail.

dev: fix race and add comments to AddRules smoketest

---

remotemonitor/monitor.go

Fixes bug that caused Twilio request validation for the remote-monitor to fail -- this PR reorders operations so that `WrapValidation` occurs before `TrimPrefix`

remotemonitor/monitor: WrapValidation before TrimPrefix

---

devtools/resetdb/datagen.go

This PR makes changes to our regendb randomly generated seed data code. It makes sure there are never any escalation policies that have a repeat count of -1.

ep repeat count never negative

---

smoketest/harness/datagen.go

This fixes a bug where repeat values could be returned from datagen methods on occasion, causing failing tests.

smoketest/harness: ensure harness datagen always returns unique values

---

web/src/app/services/ServiceDetails.js

This PR fixes a bug where a blank details page is displayed when navigating from the services list.

ui/service: don't show page spinner if partially loaded

---

auth/handler.go
devtools/ci/tasks/scripts/codecheck.sh
devtools/mockslack/state.go
devtools/runjson/task.go
engine/engine.go
engine/message/config.go
engine/message/queue.go
oncall/state_test.go

This PR adds the `-s` flag to `gofmt` checks and corrects a few spelling mistakes.

go: linting fixes

---

schedule/rotation/rotation.go
schedule/rotation/rotation_test.go

This PR fixes a bug in `Rotation.EndTime` that would return an incorrect value causing an infinite loop in some cases.
When it comes to rotations we use a single timestamp and timezone to denote when the "rotating" begins.
For weekly and daily this is how a rotation at 8 pm keeps its meaning across timezone boundaries. Additionally, changing the timezone of the rotation won't "lose its place" because it's evaluated as "what time was it, at this moment, in that timezone".
When dealing with rotations we have one method that does most of the heavy lifting `EndTime`. It takes a single argument, `t`, any timestamp, and will output the time at which a rotation shift would be over, for whatever shift is active at `t`.
There is also a `StartTime` method, …

schedule/rotation: fix endtime calculation bug

---

web/src/app/users/UserContactMethodForm.js

Added input adornment for phone number field when adding a new contact method.

ui/profile: added '+' as input adornment to phone field for contact method

---

web/src/cypress/support/index.ts
web/src/cypress/support/util.ts

This PR replaces the `preserveOnce` inside `beforeEach` by whitelisting the session cookie.

cypress: use whitelist instead of preserveOnce

---

web/src/app/rotations/RotationDetails.js
web/src/app/rotations/util.js
web/src/app/schedules/ScheduleDetails.js

This updates `ScheduleDetails` and `RotationDetails` so they can render immediately (i.e. from the list page) with cached data while fetching additional information on the page. It fixes the page flicker to make them behave like service and EP details pages.
Schedule and rotation details pages should render immediately when coming from the list page, even when on a slow network or device.

ui/details: use partial query for schedule/rotation initial render

---

web/src/app/schedules/CalendarToolbar.js

This rewrites the `CalendarToolbar` using `ButtonGroup`s and hooks. It's responsive as shown in screenshots below.
- Buttons render more consistently
This is blocking #277

ui/schedules: Refactor CalendarToolbar

---

web/src/app/schedules/CalendarEventWrapper.js

ui/calendar: replace invalid `mini` prop with `size`

---

web/src/app/util/promiseBatch.js
web/src/cypress/support/login.ts

This PR adds a polyfill for the `finally` method of promises and removes the use of `setCookie`, `getCookie`, and `clearCookie` that were causing issues for admin tests.

refetch: fix auth issues in admin tests

---

web/src/app/config/index.js
web/src/app/rotations/RotationDetails.js
web/src/app/schedules/ScheduleDetails.js
web/src/app/services/ServiceDetails.js
web/src/app/util/promiseBatch.js

This PR fixes an issue triggered by mutating `Promise.prototype.finally` to polyfill missing functionality in Electron. When running tests, Electron would crash while the polyfill was in effect.
Additionally, the `promiseBatch` code was refactored to be easier to understand and maintain.

refetch: fix electron crash

---

web/src/app/forms/FormField.js
web/src/app/selection/MaterialSelect.js
web/src/app/util/hasValue.js
web/src/app/util/shrinkWorkaround.js

Added fix for input labels that would overlap in text fields that had autofilled values.
**Additional Info**
Link to documentation in material ui for this fix:
https://material-ui.com/components/text-fields/#shrink

ui: fix input label shrinking bug

---

web/src/cypress/support/dialog.ts

Increases timeout on commands in `dialogFinish()` from 4000 (default) to 10000
Addresses flakey build in #326

cypress: Increase timeout when closing dialogs

---

web/src/app/services/components/ServiceAlerts.js

`onSubmit` is an event handler that will pass in arguments not meant for mutate, and we don't want it to interpret the return value of mutate.

ui/ServiceAlerts: wrap call to mutate in onSubmit handler

---

devtools/ci/dockerfiles/cypress-env/Dockerfile
devtools/ci/tasks/scripts/codecheck.sh

This PR adjusts `codecheck.sh` (which is called by `make check`) so an error occurs if Cypress versions are not set with the same version in both:
`web/src/package.json`
and
`devtools/ci/dockerfiles/cypress-env/Dockerfile`

ci: make check will fail if cypress version mismatch

---

web/src/app/schedules/ScheduleOverrideCreateDialog.js

Calendar schedule pages are lagging, including dialogs. Converted the dialogs to hooks, but didn't gain any significant improvement in perf

ui: Convert ScheduleOverrideCreateDialog to hooks

---

web/src/app/loading/components/Spinner.js

Loading spinners weren't styled correctly in Firefox. This change has been tested for compatibility in Chrome, Firefox, and Safari.
Loading spinners will be a fixed height on all devices.

ui: set fixed size on loading spinner

---

web/src/app/alerts/components/AlertsListDataWrapper.js

Adds a left margin to the alert summary
Before:
After:

ui/alerts: Give visual separation between alert service name and summary

---

.dependabot/config.yml

This makes Dependabot stop watching our Go modules. Our CI was failing due to a few known issues, but before GitHub fixes them, we are disabling it.

deps: disable dependabot Go config

---

web/src/cypress/integration/scheduleCalendar.ts

It "should create a replace override from a shift tooltip", but the replacer must be different than the replacee. We ensure this by verifying the replacer has a different user id.

cypress: fix flaky test; replace override requires unique users

---

web/src/app/rotations/UserForm.js

Currently, a user can submit the Add User form without selecting a user. We provide a cancel button if they don't wish to add a user.

ui: require input when adding user to rotation

---

smoketest/deleteescalationpolicy_test.go
smoketest/deleterotation_test.go
smoketest/graphqlalert_test.go
smoketest/graphqlcreateschedule_test.go
smoketest/graphqlcreatescheduledefaultrotation_test.go
smoketest/graphqlservicelabels_test.go
smoketest/graphqlupdaterotation_test.go
smoketest/graphqluserfavorites_test.go
smoketest/graphqlusers_test.go
smoketest/harness/graphql.go
smoketest/harness/harness.go
smoketest/listalerts_test.go
smoketest/policyreassignment_test.go
smoketest/twiliotestsms_test.go
smoketest/twiliotestvoice_test.go

This removes the `GraphlQLQuery` method in favor of `GraphlQLQuery2` without introducing any new functionality or features.

smoketests: migrate queries to use GraphQL 2

---

web/src/app/escalation-policies/PolicyStepForm.js

Previously, keyboard users did not receive visual feedback when tabbing through the escalation policy form. This resolves that issue by adding the `tabindex` attribute where needed.
Keyboard users are now able to receive visual feedback via the browser's default outline when tabbing through focusable form fields
**Other:**
Adds `aria-expanded` attribute to buttons of active accordion fields

ui/accessibility: make escalation policy form fields focusable

---

web/src/app/alerts/components/AlertsListDataWrapper.js
web/src/app/schedules/CalendarEventWrapper.js
web/src/app/schedules/CalendarToolbar.js
web/src/app/schedules/ScheduleCalendar.js
web/src/app/schedules/ScheduleCalendarQuery.js
web/src/app/util/CountDown.js
web/src/app/util/LuxonLocalizer.js
web/src/app/util/luxon-helpers.js
web/src/app/util/luxon-helpers.test.js
web/src/cypress/integration/scheduleCalendar.ts
web/src/package.json
web/src/webpack.dll.config.js

Migrates any use of the datetime formatter Moment to use Luxon which is much smaller in bundle size. (Although Moment is a dependency of cypress; thus `yarn.lock` remains unchanged).
**User-facing Changes:**
`CalendarEventWrapper.js` now includes timezone
Before:
After:

ui: migrate from moment to luxon

---

devtools/resetdb/main.go

Fixes an issue that caused `make regendb` to fail due to DB constraints by adding necessary dependencies to the `user_favorites` insert.

dev: add missing deps for user_favorites

---

web/src/app/selection/MaterialSelect.js
web/src/app/selection/MaterialSelectComponents.js
web/src/app/selection/QuerySelect.js
web/src/cypress/integration/materialSelect.ts
web/src/cypress/support/dialog.ts
web/src/cypress/support/form.ts

Sets isClearable in material-select component to always be true for all fields. If required, field will be reset to last set value (or default) after losing focus.

ui/material-select: set isClearable to always true

---

graphql2/generated.go
graphql2/graphqlapp/schedule.go
graphql2/graphqlapp/useroverride.go
graphql2/models_gen.go
graphql2/schema.graphql
smoketest/graphqloncall_test.go
smoketest/graphqloncallassignments_test.go

This migrates the tests in `smoketest/graphqloncall_test.go` and `smoketest/graphqloncallassignments_test.go` to use the graphql2 endpoint
To help accomplish this, we added the ability to create `newUserOverrides` as a nested field for `newSchedule`, and `scheduleID` is therefore optional
e.g. 
```go
...
steps: [{
delayMinutes: 1,
newSchedule: {
name: "David",
timeZone: "UTC",
newUserOverrides: [{
addUserID: "{{.User1.ID}}",
start: "1006-01-02T15:04:05Z",
end: "4006-01-02T15:04:05Z"
}]
}	
}]
...
```

smoketests: migrate on call tests to graphql2 

---

app/initauth.go
auth/authtoken/encode.go
auth/authtoken/parse.go
auth/authtoken/token.go
auth/authtoken/token_test.go
auth/authtoken/type.go
auth/handler.go
auth/handlerconfig.go
calendarsubscription/store.go
integrationkey/store.go
mailgun/mailgun.go
smoketest/harness/graphql.go
util/errutil/httperror.go
validation/fieldvalidationerror.go

This PR introduces a new package `authtokens` that handles parsing and encoding all used token formats in GoAlert.
Additionally, it changes the calendar subscription token from a JWT token to a binary base64 encoded string. This is due to size constraints on subscription URLs for some calendar providers.

auth: refactor token handling and shorten cal-sub token strings

---

Makefile
devtools/runjson/localdev-cypress-prod.json
devtools/runjson/localdev-cypress.json

Recent versions of the Postgres container now require `POSTGRES_HOST_AUTH_METHOD=trust` to be set in order for the containers to start in the previous relied-on mode. Without being set, commands like `make postgres` or `make cy-wide` will fail as the db container will fail to start.
This PR adds the required settings where necessary to allow development tools to behave the same way as they have in the past with recent versions of the container.

dev: add POSTGRES_HOST_AUTH_METHOD env var

---

web/src/app/schedules/calendar-subscribe/CalendarSubscribeCreateDialog.js
web/src/app/schedules/calendar-subscribe/CalendarSubscribeEditDialog.js
web/src/app/schedules/calendar-subscribe/CalendarSubscribeForm.js
web/src/cypress/integration/calendarSubscriptions.ts

This PR removes `reminderMinutes` fields from the UI when creating or editing calendar subscriptions and updates cypress tests.  It also sets a default reminder on new calendar subscriptions created in the UI to be the on-call shift start.  No GraphQL or backend adjustments were made (still support specifying alternate reminderMinutes).

ui: remove reminderMinutes

---

web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceListItem.js
web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceSelect.js
web/src/app/alerts/pages/AlertDetailPage.js
web/src/app/apollo.js
web/src/app/escalation-policies/PolicyDetails.js
web/src/app/schedules/ScheduleDeleteDialog.js
web/src/app/schedules/ScheduleTZFilter.js
web/src/app/services/ServiceOnCallList.js
web/src/app/util/Chips.js
web/src/app/util/Query.js
web/src/app/util/QuerySetFavoriteButton.js

This PR fixes a regression where default polling stopped working within the application in many instances.
The `watchQuery` field needed to be added in addition to `query` for default options. Consequently, a number of places needed to check for existing data before rendering spinners to not flicker on data fetch.
Fixes #450

ui: fix polling when calling `useQuery`

---

web/src/app/schedules/util.js

The existing fix would handle the week before a DST change,
but would not handle parsing clock values the week of/after.
This PR fixes an issue where `parseClock` would return an incorrect time the week of/after a DST change.

schedules/util: handle DST changes for the week after

---

web/src/app/alerts/components/AlertDetails.js
web/src/app/alerts/pages/AlertDetailPage.js
web/src/app/services/components/ServiceAlerts.js
web/src/app/util/Options.js

This PR converts the api calls from alert details pages to use the Graphql2 client in Apollo.
Converting alert details files to hooks and TypeScript
Rotations will now appear in the escalation policy countdown table

ui: use graphql2 api in alert details

---

Makefile
web/src/app/tsconfig.json
web/src/cypress/plugins/index.js
web/src/cypress/tsconfig.json
web/src/package.json
web/src/webpack.cypress.js
web/src/yarn.lock

This PR moves src/tsconfig.json to app/ and keeps the cypress/ and app/tsconfig.json files separate. Also updates the package.json to lint the project with a unified config and creates separate yarn scripts to format and type check app/ and cypress/.
- husky will **not** run typechecking pre-commit
- make check should fail if there are any typescript errors
- uses babel-loader to build cypress bundles
eslint will not check typescript files (current state)

dev: fix typescript file checking on commit and make check

---

web/src/cypress/integration/scheduleCalendar.ts

Fixes a test that would fail on overlap months (e.g. Jan 27 - Feb 2) when adding months to assert text.

cypress: fix failing test

---

web/src/app/alerts/AlertDetailLogs.js
web/src/app/alerts/AlertsList.js

This PR updates the formatting of the timestamps in the alert details event log to match the format of the calendar events when "Full Timestamps" is toggled on, and the alerts list time since open when toggled off.
- Event log message rendered as primary text (previous: secondary)
- Event log timestamps rendered on right of list item
- Event log timestamps `Today at 11:41 AM` -> `2m ago`
- Event log full timestamps `Apr 02 2020, 11:41:18 AM` -> `April 2, 2020, 11:41 AM CDT`
- Updates AlertsList ListItem to use the proper component, being ListItemText (instead of Typography)
- Visible changes: Text color black -> grey, with a slightly larger font size

ui: consistify alert timestamps

---

web/src/cypress/support/form.ts

This PR resolves a flaky test case where we were querying on all buttons for days in the material calendar component. 
e.g. fails when searching for button containing "30"
Old Query: "Search for button containing 30"
New query: "Search for clickable button containing 30"

cypress: resolve fallback datetime timepicker test issue

---

web/handler.go
web/src/webpack.config.js

This PR re-enables hot module reloading with the Webpack Dev Server by serving the hot reload hash files to the build directory for WDS to pick up and trigger a reload.

wds: re-enable hot module reloading

---

Makefile
devtools/gqltsgen/main.go
web/src/genschema.go
web/src/schema.d.ts

Ambient const enums are not allowed when the '--isolatedModules' flag is provided with typescript, effectively making the exported enums unusable
- uses string union types instead of enums
- run `prettier -l --write schema.d.ts` after generating
- reintroduce double newlines for readability

dev: generate string union types instead of const enums

---

web/src/cypress/support/alert.ts
web/src/cypress/support/calendar-subscription.ts
web/src/cypress/support/ep.ts
web/src/cypress/support/graphql.ts
web/src/cypress/support/limits.ts
web/src/cypress/support/profile.ts
web/src/cypress/support/rotation.ts
web/src/cypress/support/schedule.ts
web/src/cypress/support/service.ts
web/src/cypress/types/graphql.d.ts

In the spirit of #608 this PR removes the option to specify a graphql API endpoint other than `'/api/graphql'`

cypress: remove api endpoint option

---

notification/twilio/sms.go

This PR enables all Twilio stop codes via SMS: STOP, STOPALL, UNSUBSCRIBE, CANCEL, END, and QUIT.
Stop codes are now processed on exact matches, to fall inline with [Twilio's processing logic](https://support.twilio.com/hc/en-us/articles/223134027-Twilio-support-for-opt-out-keywords-SMS-STOP-filtering-): 
> Only single-word messages will trigger the block. So, for example, replying STOP will stop the customer from receiving messages from that particular Twilio number, but replying "STOP PLEASE" or "PLEASE CANCEL" will not.

sms: support all twilio stop codes

---

Makefile

Adding missing dependency to the `generate` task in the Makefile now that prettier is required for schema generation.
This fixes the issue where `make generate` (or `make check`) would fail if `node_modules` hasn't been initialized yet.

Makefile: add missing dep for `make generate`

---

devtools/waitfor/main.go

This PR tweaks the `watifor` devtool to allow both `postgresql://` and `postgres://` URI scheme designators.  Both are valid per PostgreSQL's [documentation](https://www.postgresql.org/docs/11/libpq-connect.html#LIBPQ-CONNSTRINGl):
> The URI scheme designator can be either postgresql:// or postgres://.

waitfor: support postgresql:// URI scheme

---

.dependabot/config.yml
web/src/package.json
web/src/yarn.lock

This PR patches a failing test in CI due to a patch update with `@material-ui/core`. Updates to this package will be ignored by dependabot until at least the next minor version increase is introduced.

deps: revert updates to material-ui/core introduced in #624

---

web/src/app/admin/AdminFieldComponents.tsx

Converts Admin Field Components to use hooks and Typescript.

ui: Convert Admin Field Components to TypeScript

---

.dependabot/config.yml

Follow-up from #634 - ignoring updates to `material-ui/core` until next major version (`4.10.x`).

deps: ignore @material-ui/core until 4.10.x

---

engine/engine.go
engine/message/db.go
notification/store.go

This PR logs notification_sent (but failed) when the applicable user's contact method is disabled.

alert logs: display when contact method is disabled

---

web/src/app/users/UserContactMethodList.js

This PR displays an error dialogue if sending a test message fails from `< UserContactMethodList />`

profile: display an error dialog if test contact method mutation fails

---

switchover/dbsync/changelog.go
switchover/dbsync/initsync.go
switchover/dbsync/shell.go
switchover/dbsync/sync.go
switchover/handler.go

This PR fixes some of the more prominent bugs in the switchover code.
- enable/disable will now drop the `change_log` table in both DBs consistently and is now handled by `reset-dest` appropriately (fixes need to enable/disable before `reset-dest` will work)
- initial sync will truncate destination tables before starting (fixes requirement to run `reset-dest` before starting)
- run `vacuum analyze` after initial sync (fixes perf. issues after switchover)
- cache `use_next_db` lookup (fixes connection delays after switchover is complete)

switchover: fix prominent bugs

---

devtools/mocktwilio/sms.go
smoketest/alertlog_test.go
smoketest/harness/graphql.go
smoketest/harness/harness.go

This PR adds tests for the following scenarios in the alert log:
- successful sent notification gets logged
- disabled contact method gets logged
- sms failure gets logged
- voice failure gets logged
- "no immediate rule" gets logged
- "no on-call users" gets logged
- "no escalation policy steps" gets logged

alert log: add smoketests

---

web/src/app/util/CountDown.js

the "<1 minute" active text now changes to "Active for..."  automatically within up to a few seconds after switching, rather than sometimes getting stuck on "<1 minute" until page reload

fix for <1 minute getting stuck switching active

---

web/src/app/details/DetailsPage.js

This PR adds a dedicated section for Quick Links when viewing in desktop mode (>=md), and keeps the quick links below the header card when viewing in mobile mode (<=sm).
In desktop mode:
In mobile mode:

details page: add quick links section for desktop

---

devtools/ci/dockerfiles/all-in-one/Dockerfile
devtools/ci/dockerfiles/all-in-one/start.sh

This image updates the all-in-one Dockerfile to use `alpine:3.12` as the base image instead of `postgres:11-alpine`
The resulting image now (correctly) has a single exposed port for the application (`8081`) now that the DB is used via unix socket.

all-in-one: use alpine base image

---

web/src/app/rotations/RotationRouter.js

This PR fixes an issue where the rotation's list search field would lose focus after the field would debounce. This was due to the fact that we were using `component` instead of `render` from `react-router-dom` to render the component (we are referencing a function that renders, not referencing a component directly).

ui: fix debounce bug on rotations list search

---

web/src/app/details/DetailsPage.js

This PR addresses an issue where the container for Quick Links (and it's vertical divider) were still being rendered on the page even if no quick links were given.
Before:
After:

ui: disable rendering quick links container if no links present

---

graphql2/graphqlapp/alert.go

Resolves an edge case in the alert log details text when `status_details` is empty.

alertlog: handle empty details correctly

---

graphql2/generated.go
graphql2/schema.graphql

This PR updates the default value of `includeNotified` in the alerts query to preserve compatibility for existing clients.

graphql: default `includeNotified` to false for API compatability

---

alert/log/store.go
engine/message/db.go

When twilio is disabled and trying to send message to the user, it will notify the user in the alert log that twilio is disabled.

engine/message: append alert log failure when Twilio is disabled

---

smoketest/graphqloncall_test.go
smoketest/graphqloncallassignments_test.go
smoketest/harness/graphql.go
smoketest/harness/harness.go

This PR adds a `GraphQLQueryUserT` method to the test harness that allows running graphQL queries via arbitrary UserIDs. This should make it possible to create users within initSQL and run a query from the same user.

dev/harness: add GraphQLQueryUserT method

---

web/src/app/admin/AdminConfig.tsx
web/src/app/admin/AdminSection.tsx
web/src/cypress/support/form.ts

This PR updates the admin config page to use accordions for the individual sections.
- `fillFormField` in cypress tests will now automatically handle accordions that are labelled appropriately for accessibility
- changes highlighted in yellow
- summary of enabled/disabled, and number of changes per-section
Closes #796

ui/admin: render sections in accordion

---

engine/message/db.go
smoketest/cmtestdisable_test.go

This PR fixes an issue where unsubscribing while a test message is pending (or otherwise having a pending test message on a disabled contact method) can lead to a state where a scan error prevents outgoing messages from being processed.

engine: fix message stall on disabled test message

---

app/initstores.go
engine/cleanupmanager/update.go
engine/schedulemanager/db.go
schedule/fixedshift.go
schedule/store.go
schedule/storefixedshifts.go
smoketest/fixedshifts_test.go
user/cache.go
user/store.go

This PR adds a cached list of valid user IDs for validating fixed shift data. The IDs are currently refreshed once per minute.
It uses the groupcache package, meaning future work can allow a single call for user IDs within an entire cluster (rather than per instance).
It also fixes an issue where invalid user IDs within fixed shift data would cause the engine to abort due to the on-call insert failing.

feature/temp-schedules: fix bugs with invalid user IDs

---

web/src/yarn.lock

This PR updates `selfsigned` to `1.10.8` which updates `node-forge` to `0.10.0` to address [CVE-2020-7720](https://github.com/advisories/GHSA-92xj-mqp7-vmcj)

chore: update node-forge to 0.10.0

---

schedule/storefixedshifts.go
schedule/validate.go

This PR updates the validation on the setFixedShifts mutation to require time ranges and values to be correct. Previously all values would be merged together and the resulting output would be cleaned/normalized and then used.
This change ensures that UI bugs or invalid API calls return with an error rather than accepted as best-effort for this mutation.

setFixedShifts: validate time ranges strictly

---

migrate/inline_data_gen.go
migrate/migrations/20200922140909-session-last-access-time.sql

This PR fixes an issue with a recent migration that fails to apply when there are old user sessions missing access times.

session migration: set last access time

---

web/src/app/selection/MaterialSelect.tsx

This PR address various warnings seen while using `MaterialSelect` around interface types of incoming props, and the current selected value matching what's in the options array now that strict validation has been added within the library.

ui: address warnings when using material select dropdowns

---

web/src/app/users/UserDetails.js

This PR includes a fix so that `non-admin` users (that have the role of `user`) can view other user's profile pages.
Fixes #905 
This PR fixes a bug where users who were not admins were not able to view other user's profile pages. The backend returns an `access denied` error when non-admins tried to view other user's profile pages (from the graphql query for user -> sessions). The front-end query has now been modified to only query for sessions if it's the logged in user or an admin. Else it will not query for sessions info.

user: non-admin viewing other user's profile pages fix

---

web/src/app/users/UserSessionList.tsx

This PR changes the ordering of active sessions to use descending order (last access time).  This places your active session on top and your most recently used sessions near the top (instead of the bottom).
Fixes #906 

active sessions: change ordering to descending

---

engine/cleanupmanager/db.go

Modified sql.Stmt for user cleanup sessions by including a Limit statement to prevent delays in the engine cycle. 
Fixes https://github.com/target/goalert/issues/909

engine/cleanupmanager: limit session cleanup

---

web/src/app/selection/MaterialSelect.tsx

This PR fixes a regression that caused the search text to be set in MaterialSelect fields when in multi-selection mode.
Fixes #911

material select: set empty input when multiple is true

---

app/tracing.go
devtools/runjson/localdev.json
engine/escalationmanager/db.go
engine/escalationmanager/update.go

This PR addresses some problems/regressions with the escalation manager:
- When multiple users are on call, or multiple alerts are escalated on the same policy, multiple logs were added
- It was multiplicative (e.g. 27 alerts = 27x27=729 entries) causing cycle timeouts
- Log entries were sent one-at-a-time, they are now batched with like-metadata in a single call of alert ids
- Part of debugging led to fixing local tracing with jaeger in `make start`
Fixes #912

engine/escalationmanager: fix regression in escalation logs

---

Makefile

Updates the make file to use `go run golang.org/x/tools/cmd/goimports` instead of executing `goimports` directly.
Using `go run ...` will automatically pull the tool, as well as using the correct version, rather than requiring the user to install it manually.

dev: fix `goimports` command in Makefile

---

mailgun/mailgun.go
smoketest/mailgunalerts_test.go

This PR fixes an issue where an invalid recipient address would cause a `500` response instead of the expected `406` when a message is to be rejected for failing validation.

mailgun: address validation fix

---

web/src/app/schedules/temp-sched/TempSchedDialog.tsx

Temp schedules form now has bounds to prevent swiping into empty pages, or to step 1 from an already created temp schedule.

temp schedules: temp schedules swipe-able form bounds

---

web/src/app/util/ISOPickers.js

Currently, the fallback non-native datetime picker component defaults to `now` when given an empty value such as an empty string.

fix: handle empty default values in fallback datetime picker

---

web/src/app/details/Notices.tsx
web/src/app/dialogs/FormDialog.js
web/src/app/schedules/ScheduleOverrideCreateDialog.js
web/src/app/schedules/ScheduleOverrideForm.js
web/src/app/schedules/useOverrideNotices.ts
web/src/app/util/shifts.ts

When a user edits or adds a temporary schedule, a warning appears above the form when the start or end time overlaps with a temporary schedule. A new hook was added, 'userOverrideNotices' to handle the query of start and end times and returns a warning to the FormDialog component if there is an existing overlap with a temporary schedule. Other supporting files were also modified to support this new functionality. 
Fixes https://github.com/target/goalert/issues/929
ScheduleOverrideEditDialog.js is out of scope because it is a class component, the useOverrideNotices hook can only be implemented in a React component. 
A warning banner appears in the dialog …

temporary schedules: warning when creating or editing an override that overlaps a temp. schedule

---

web/src/app/icons/components/Icons.js
web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx
web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
web/src/app/schedules/temp-sched/TempSchedTimesStep.tsx
web/src/app/util/luxon-helpers.js
web/src/app/util/shifts.ts

- added validation for start/end date/time so end must be after start
- display all shifts in shift list, doesn't filter by start/end
- added warning icon next to out of bounds shifts
- added floating warning in bottom left for out of bounds shifts
Fixes #930

temp schedules: timestamp bounds validation

---

Makefile
devtools/ci/dockerfiles/all-in-one/Dockerfile
devtools/ci/dockerfiles/goalert/Dockerfile

This PR updates the Makefile and Dockerfile to use embedded TZ data instead of relying on the system package.
This is to resolve an issue where DST values were no longer calculated properly in TZ versions `2020b` onwards (e.g. latest in the alpine build).
ZONEINFO is now set to use the tz data that ships under GOROOT for testing. This should help to ensure that binaries and container images are more consistent with regard to calculated times.

docker: use embedded TZ data

---

web/src/app/selection/MaterialSelect.tsx

This PR addresses a recent regression where the onBlur handler for material selects no longer worked properly.
Fixes #920

material select: fix onBlur handler

---

web/src/app/forms/FormField.js
web/src/app/schedules/temp-sched/TempSchedAddShiftForm.tsx
web/src/app/schedules/temp-sched/TempSchedTimesStep.tsx
web/src/app/util/ISOPickers.js

This PR ensures that the start date of a temporary schedule can not begin in the past.
Adds support for `min` and `max` dates in `ISOPickers`

feature/temp schedules: set min start date to now()

---

web/src/app/schedules/ScheduleDetails.js

To prevent unnecessary remounting of calendar event wrappers, we can memoize the event handlers here
Fixes #959

fix: memoize calendar event handlers to prevent tooltip flicker

---

web/src/app/schedules/temp-sched/TempSchedDialog.tsx

Disable arrow key navigation on swipable dialog views since it is unexpected behavior which can lead to confusing states for a user e.g. bypassing form validation

fix: disable arrow keys on swipable temp schedule dialog

---

web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx

Current state: 
When filling out the Add Shift form, users may add an "invalid shift". The user must ultimately either:
- delete and create new shift
- edit schedule bounds
New state:
When filling out the Add Shift form, users may only add shifts that are valid with respect to the stateful temp sched start/end times.
Net effect:
This only changes the UX. If a user creates an invalid state at any point in time, the ultimate form submit will prevent form submission and provide relevant error messaging.

fix: add shift form validation

---

web/src/app/schedules/calendar-subscribe/CalendarSubscribeButton.js

This PR fixes an issue where a still-null `userID` is sent when fetching calendar subscriptions.

schedules: wait for userID before fetching subscriptions

---

web/src/app/dialogs/FormDialog.js
web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx

Fixes an issue where form height was not stretched to fill the height of its parent container in Safari.

ui/safari: fix dialog overflow in temp schedules shifts step

---

schedule/fixedshift.go

Fixes a bug where the order of shifts within a temporary schedule was not deterministic, caught by a unit test that sometimes failed.

temp-schedules: fix shift sort order

---

web/src/cypress/integration/rotations.ts
web/src/cypress/integration/scheduleCalendar.ts
web/src/cypress/support/rotation.ts
web/src/cypress/types/rotation.d.ts

This PR adjusts the `shiftLength` limit of the hourly rotations created while testing the schedule calendar because of a performance issue mainly noticeable within our CI testing environment. **Schedules with a rotation assignment handing off every hour may lead to performance issues and should still be addressed.** The decision was made to continue forward with this milestone while addressing the performance degradation in CI first.

cypress: use reasonable limits for calendar tests

---

graphql2/graphqlapp/alert.go
web/src/cypress/support/form.ts

This PR fixes a nil pointer exception when the message status is no longer available from the alert log.

alert log: return no status if message is unavailable

---

graphql2/graphqlapp/app.go
override/store.go

This PR fixes a bug where an unknown override ID caused an unexpected error.
Additionally, the logged error message was already scrubbed making it harder to find the root cause. As such a fix was added to allow the original error message to be logged, as originally intended.

user overrides: return nil when a user override cannot be found

---

web/handler.go

Lowering max-age for new-version detection when `stale-while-revalidate` isn't supported.

cache: force re-validation more frequently

---

graphql2/isotimestamp.go
smoketest/graphqlupdaterotation_test.go

Small change to ensure all returned ISO timestamps from GraphQL calls are in the UTC offset.
This makes comparing output, sorting, etc.. easier.

graphql: make timestamps always in UTC

---

web/src/app/selection/MaterialSelect.tsx
web/src/cypress/integration/materialSelect.ts

This PR fixes an issue in the autocomplete select component in which the stateful selected option would not render as an option in the dropdown.
Closes #994 and closes #958

fix: material select shows selected option in dropdown for single-select

---

web/src/cypress.json
web/src/cypress/integration/rotations.ts

This configures cypress to block outgoing requests to gravatar. This is necessary because the current version of cypress (5.5.0) is unfortunately spamming thousands of requests for static assets. Performance impact is expected to be negligible, but it would be courteous of us to not hammer gravatar's servers/cache whenever we run our tests.

cypress: block outgoing requests to gravatar

---

web/src/app/forms/Form.js

Converted Form.js to use hooks
Part of https://github.com/target/goalert/issues/923

ui/hooks: app/forms/Form.js

---

web/src/app/main/components/Login.js
web/src/package.json
web/src/webpack.dll.config.js
web/src/yarn.lock

Removes `axois` because:
- we don't need it
- we can lower our dependency overhead
- we should be consistent in how we perform network requests

ui: remove axios dependency

---

Makefile
devtools/ci/tasks/scripts/test-integration.sh
devtools/pgdump-lite/cmd/pgdump-lite/main.go
devtools/pgdump-lite/dumpdata.go
smoketest/harness/harness.go

This PR adds a new tool `pgdump-lite` that is able to dump DB data for test debugging without depending on `pg_dump`
It also results in no longer getting the circular dependency spam when running smoketests.
It is still required to have `pg_dump` for the migration test, schema, sequence, etc.. output is out-of-scope.

dev: add pgdump-lite tool

---

notification/manager.go

This PR updates `notification/manager.go` to always log `notification sent` entries (instead of only when in debug mode).  The following is an example of what information is logged (useful for tracking what notification types are used):
`Backend  (err): time="2020-11-24T10:53:29-06:00" level=info msg="notification sent" AlertID=79672 AuthSource="SourceTypeContactMethod{00000000-0000-0000-0000-000000000000}" AuthSystemComponent=Engine AuthUserID=00000000-0000-0000-0000-000000000000 CallbackID=00000000-0000-0000-0000-000000000000 DestType=DestTypeSMS DestTypeID=00000000-0000-0000-0000-000000000000 ProviderName=Twilio-SMS ProviderType=DestTypeSMS Trigger=INTERVAL`

logs: always log notification sent info

---

web/src/app/main/WideSideBar.js
web/src/app/main/WideSideBar.tsx

Converts WideSideBar.js to hooks, and then to typescript
Part of #923

ui/hooks: wide sidebar

---

notification/twilio/carrier.go
user/contactmethod/store.go
web/src/app/admin/AdminNumberLookup.tsx

This fixes a `sql.ErrNoRows` error that prevented carrier info from being saved as well as ensuring both SMS and Voice metadata is updated where appropriate.

db: check for ErrNoRows on carrier lookup

---

web/src/app/users/UserDetails.js

This fixes the issue linked below. The business logic for this code is the following: "you're only authorized to view your own sessions unless you're an admin"
There are two solutions for this:
1. Query everything but the sessions until it is confirmed that the current user is an admin. Then if confirmed, query for sessions.
2. Wait to confirm whether current user is an admin. Then perform appropriate query.
This PR implements the second solution which has a slower TTI, but is a more reliable experience. I'm open to more discussion on the tradeoffs here.
Fixes #1072

ui/users: fix race condition; check for session readiness

---

graphql2/graphqlapp/app.go

This PR updates the `isGQLValidation` helper function to handle parse errors as GraphQL client errors.
Fixes #1101

graphql: consider parse error as client error

---

web/src/app/util/CountDown.js

Use hooks in CountDown.js
Part of #923

ui/hooks: count down

---

web/src/app/alerts/AlertsList.js

This PR hides the "include all services" filter on a single service's alerts list view
Fixes #1064

ui/alerts: hide "include all services" filter on service's alerts view

---

engine/message/queue.go
engine/message/queue_test.go

This PR updates the priority message sorting to track first-alert status per-destination-type. This is intended to prevent issues where contact methods with high throughput, but potentially low visibility (e.g. email) from de-prioritizing someone getting say a phone call or text before other services are notified using those methods.
GoAlert will prioritize the first alert notification to a service above all others, if the service has had no outgoing notifications within the last 2 minutes. This is intended to "guarantee" that at least one on-call user of a service will receive at least one notification for at least one alert when/if the system is at total capacity for sending messages.
As an example, SMS and VOICE calls are allowed by Twilio at a …

engine/messages: track first-alert by destination type

---

web/src/app/escalation-policies/PolicyStepForm.js

This PR has the delay minutes form field use the `NumberField` component making it unclearable, preventing invalid hint text.
Fixes #1055
Users can't clear the field since it is required.

ui/escalation-policies: use NumberField for delay minutes

---

.github/stale.yml

Adds [Stale](https://github.com/apps/stale) to our repo which will manage stale issues and pull requests. I aimed to use some reasonable defaults for now as we are still growing within the open-source community:
- Issues and PRs will be labeled with (stale) after 30 days and a comment will be added.
- Issues will be closed after 1 year.
- PRs will be closed after 3 months.
With our current workflow and pace of incoming external support, this seems to be a good default for how we currently operate in real time when while managing our backlog.

repo: add stale bot config

---

.github/stale.yml

Explicitly disables `daysUntilClose` within Stale as the bot will still close issues and PRs automatically even when unset.

repo: disable days until close in Stale config

---

web/src/cypress/integration/schedules.ts

This PR fixes the test for adding a schedule assignment which was passing as a false positive.  In the `beforeEach` hook, we add a rotation to a schedule. The old test code was trying to re-add this rotation. The new test code creates an entirely new rotation altogether.
`cy.get('body').should('not.contain', name)` was only asserting on top-level `body` element and wasn't drilling down into the child nodes. 
The new code scans `cy.get('ul')` which behaves correctly and also enforces semantic html. We should avoid asserting on the `body` element in general.

cypress/schedules: fix - should add a rotation as an assignment

---

devtools/ci/dockerfiles/cypress-env/Dockerfile
devtools/ci/tasks/test-integration.yml
web/src/cypress/integration/alerts.ts
web/src/cypress/integration/materialSelect.ts
web/src/cypress/support/form.ts
web/src/package.json
web/src/yarn.lock

- Followed the [migration guide](https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-6-0) from v5 to v6
- Reviewed full [changelog](https://docs.cypress.io/guides/references/changelog.html#6-2-0)
- Bug fix: multi select fields were not truly clearable. Now the input text will be cleared and the inline chips will be deleted when using `cy.form({inputName: ''})`
- Stability fix: added a `cy.reload()` before making assertions on the alerts page. While this may not be ideal, this is the precedent set in that test suite. I'm open to investigating this more, but IMO we are still exercising our code well enough. The main downside is the small perf impact for doing 3 page reloads

cypress: upgrade to 6.2.0

---

auth/github/identityprovider.go

This PR fixes a couple of places in the GitHub auth provider that were not properly logging errors.

auth/github: fix missing github auth errors

---

web/src/app/util/SpeedDial.tsx

This converts the `CustomSpeedDial` component to typescript.
The `SpeedDial` component has compatibility issues with react/react-dom v17. While investigating this, I converted this component. The original issue remains unresolved.

ui/util: use typescript for speed dial

---

config/config.go

This PR adds validation for the config changes for smtp, when enabled. 
Validating that the `from` email address is a valid email and `SMTP` when enabled, makes sure that `from` and `address` fields are also specified.

alerts smtp: add config validation 

---

remotemonitor/sms.go

This PR closes #1195 by tweaking the remote monitor's regex to allow matches for bundled message close codes (where the close action code = `cc` (instead of just `c` for single alert notifications).

remote monitor: support for bundled sms messages

---

web/src/app/main/App.js

Changes breakpoint to hide side drawer from `md` to `sm`
Fixes #1197 
This should fix displays on tablet-sized screens

ui: fix breakpoints issue

---

devtools/runjson/localdev-prod.json
web/src/webpack.config.js
web/src/webpack.prod.config.js

Fixes an issue in which emails in the production build couldn't find a reference to the logo
Fixes #1198

email: fix logo image

---

graphql2/generated.go
graphql2/graphqlapp/rotation.go
graphql2/models_gen.go
graphql2/schema.graphql
web/src/app/rotations/RotationForm.js
web/src/schema.d.ts

Closes #1141 
When selecting a rotation handoff time in the future, the displayed "upcoming handoffs" will always be after the selected time (current behavior displays relative to `now`)
CalcRotationHandoffTimesInput includes an optional `from: ISO Timestamp` paramter that defaults to `now`

add CalcRotationHandoffTimesInput from parameter

---

web/src/app/util/timeFormat.js
web/src/app/util/timeFormat.test.js

This PR fixes a flaking test by adding a grace period of 5 days to the "months since" format. It also improves the accuracy of the display by prefixing longer durations with a `>` sign
**User facing changes:**
See above
**Additional context**:
Resolves CI build errors

fix: update formatting for longer duration shorthands

---

.dependabot/config.yml

There is an incompatibility between `date-io/luxon@2` and `material-pickers@3`. 
`material-pickers@4` is supposed to ship and be included in `material-ui/core@5` which will should be released within 6 months or so. Until then, we should ignore `date-io/luxon`

ui: dependabot ignore @date-io/luxon@2

---

graphql2/graphqlapp/app.go

Currently, all requests made by an admin have tracing turned on for performance information. This PR updates the requirement so that request additionally requires the query parameter `trace=1`. This prevents devoting memory/resources to tracing for normal application usage while allowing admins/devs to collect performance information when necessary.

graphql explorer: require `trace=1` before enabling gql tracing

---

dataloader/alertloader.go
dataloader/loader.go
graphql2/graphqlapp/app.go
graphql2/graphqlapp/dataloaders.go

This PR updates the graphql dataloaders to only initialize & allocate memory when they are first used, as well as guarantee a cleanup when the request (or it's context) ends.

graphql: lazy-dataloaders

---

.eslintrc.js
web/src/app/index.tsx
web/src/app/lists/PaginatedList.tsx
web/src/app/util/Transitions.tsx

This PR configures the linter to use `eslint-plugin-react`. Checking prop-types is turned off in favor of typescript.
https://github.com/yannickcr/eslint-plugin-react

ui: configure eslint-plugin-react

---

web/src/app/util/Chips.tsx
web/src/cypress/integration/escalationPolicySteps.ts

This adds links to Slack `<Chip />` components that redirect users to the native app if installed, else the slack web interface. The first time a user clicks such a link, they will have a choice of opening in either the browser or natively.
Closes #1235 
Micro-improvement for UX, allowing user to click on slack chip
See https://api.slack.com/reference/deep-linking#slack_apps

ui/util: links to slack channels

---

LICENSE.md

This PR bumps the copyright year to 2021 and also adds the actual license text for integration with github's UI.
See more here: https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

license: bump copyright year to 2021

---

web/src/app/escalation-policies/PolicyStepForm.js
web/src/cypress/integration/escalationPolicySteps.ts
web/src/cypress/integration/favorites.ts

Reorders the stepper within the Policy Step Form so that selecting a Schedule over a Rotation is more obvious to the end user.
This change comes as a hopeful adjustment to mitigate instances where users have a misconfigured EP (adding their rotation instead of their schedule) and later noticing that their schedule overrides are not working as they intended.
Closes #1362

ui: reorder select fields in policy step dialog

---

smoketest/prioritization_test.go

This PR attempts to fix the flaky prioritization test by increasing the FastForward time and ensuring it happens after the second alert is created.

smoketest: FastForward after creating alert

---

oncall/activecalculator.go
oncall/activecalculator_test.go
oncall/state.go
oncall/state_test.go
oncall/timeiterator.go
oncall/usercalculator.go
oncall/usercalculator_test.go

This PR fixes a panic issue when calculating shifts that include time in the past that overlap current rulesets.
- The `oncall.TimeIterator` will now automatically extend the start time based on provided rules (eliminating the need for `ActiveTime`)
- `oncall.ActiveCalculator` no longer tracks "original" or "historic" times to simplify logic
- `oncall.ActiveCalculator` now explicitly requires spans to be set in order without overlap

oncall: fix panic for out-of-order shift spans

---

web/src/webpack.config.js

The Define webpack plugin is warning about inconsistent `NODE_ENV` naming. This PR makes it `'development'` when working locally
console warning:
`Object { message: "DefinePlugin\nConflicting values for 'process.env.NODE_ENV'" }`

ui: resolve conflicting `NODE_ENV` names

---

web/src/app/forms/FormContainer.js

This PR will copy form values into a mutable object. Without this, we are unable to initialize forms with values from Apollo that may be frozen in the cache
Users can toggle existing checkboxes when editing a schedule assignment
This may introduce a performance hit unfortunately, but for the time being correctness is more important for UX.

ui/forms: copy values into mutable object

---

web/src/app/selection/MaterialSelect.tsx

1. Currently, when using a select field e.g. in the Wizard, once a value has been selected, the input field cannot be cleared to allow for a new value. This PR fixes that, while still preserving the underlying state on blur events.
2. This PR updates the displayed input value when the component receives a new props.value but only if the component is not currently in use i.e. focused. 
Users will be able to clear the input field

ui/selection: handle empty input values, incoming `props.value`

---

oncall/activecalculator.go
oncall/state.go
oncall/state_test.go

This PR fixes two issues with the new `oncall` code:
- Out-of-order overrides would cause shift calculation to fail, they are now sorted like history entries
- Calculating future shifts would sometimes connect to current on-call shifts, time between `now()` and `Start` is now processed to determine actual start times

oncall: fix shift calculation with gaps

---

Makefile
app/cmd.go
devtools/ci/dockerfiles/goalert/Dockerfile
devtools/ci/dockerfiles/goalert/Dockerfile.buildx
devtools/ci/tasks/scripts/build-binaries.sh
web/index.go
web/src/app/env.ts
web/src/webpack.config.js
web/src/webpack.prod.config.js

This moves `GOALERT_VERSION` from the `DefinePlugin` to `BannerPlugin` and adds a validation check to the `self-test` subcommand.
Additionally, it adds self-test execution when building binaries (offline tests only) as well as the `goalert/goalert` docker container.
Closes #1134

self-test: set version as banner and check in self-test

---

app/cmd.go
migrate/migrate.go

This PR disables migrations when in `--api-only` mode. This ensures only instances running an engine loop can apply a new migration, ensuring messages always go out.
Additionally, retry messages are suppressed when applying migrations. Only the final error will be reported (if it fails).

migrate: no migrations for api only

---

oncall/overridecalculator.go
oncall/state.go
oncall/temporaryschedulecalculator.go

Fixes issues where out-of-order temp schedules could cause a panic (e.g., after deleting with multiple)

oncall: Fix oncall order panic

---

web/src/app/styles/base/elements.css

This PR updates the weekly view time indicator to be less harsh color-wise and more noticable.

schdules: update time indicator style

---

web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx

Shift list in the temporary schedule now always displays the start/end times and days with no coverage.

temp-schedules: always display start/end times in shift list

---

web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx

This PR removes the validation when adding a shift on step two for a temporary schedule regarding final start/end times. These errors are handled elsewhere in the form.

ui/temp sched: remove redundant validation on add shift step

---

.github/ISSUE_TEMPLATE/config.yml

Follow-up to #1165, adds link to our slack from the issues page
See https://github.com/rome/tools/issues/new/choose for working example

dev: add link to slack from new issue page

---

devtools/pgdump-lite/cmd/pgdump-lite/main.go
devtools/pgdump-lite/dumpdata.go

The default encoding in PostgreSQL is set to SQL_ASCII, but `pgx` requires UTF-8

pgdump-lite: set client_encoding to UTF8

---

.github/ISSUE_TEMPLATE/config.yml
devtools/ci/tasks/scripts/build-binaries.sh
engine/cleanupmanager/db.go
engine/cleanupmanager/update.go
schedule/storetemporaryschedules.go
web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx
web/src/app/styles/base/elements.css
web/src/cypress/support/schedule.ts

This PR updates the temporary schedule code to perform cleanup once per month, per schedule (vs. every day). Additionally, schedules are no longer trimmed to the current timestamp, but rather dropped entirely once their end time has expired.
An issue with `make check` was also resolved with the relevant formatting/type fixes added.

schedule: retain temp schedules

---

migrate/migrate.go

Fixes an issue where the error message was "no rows in result set" instead of "latest migration 'x' has not been applied"

migrate: fix error text in api-only mode

---

web/src/app/apollo.js

This PR updates the apollo cache configuration to suppress apollo warnings in the console. No perf or behavior change is expected. We are just making the default behavior explicit.
Example warning:
In this case, we deleted one `contactMethod` and want to use the `incoming` data (nothing to merge).

ui: appease apollo cache warnings

---

web/src/app/dialogs/FormDialog.js
web/src/app/util/Transitions.tsx

This PR renames the transitions, and using FadeTransition for the temp sched dialog since that is our convention on desktop screen sizes
Temp sched dialog fades in and out, as opposed to sliding in

ui/transitions: use fade in for desktop UX

---

web/src/package.json
web/src/webpack.config.js
web/src/webpack.cypress.js
web/src/webpack.prod.config.js
yarn.lock

Forces lodash functions to be run in strict mode, preventing silent errors (e.g. Apollo cache bug)

ui: load lodash in strict mode

---

app/shutdown.go
notification/manager.go
notification/notifier.go
notification/result_string.go
notification/slack/channel.go
notification/statusmanager.go
notification/twilio/sms.go
notification/twilio/voice.go

This work simplifies the notification package interfaces by allowing incoming messages/status to be handled through method calls instead of embedded channels. It's part of a cleanup effort for advanced notification provider functionality.

notification: Use methods instead of channels for incoming messages

---

devtools/ci/dockerfiles/all-in-one/Dockerfile
devtools/ci/dockerfiles/all-in-one/Dockerfile.buildx
devtools/ci/dockerfiles/goalert/Dockerfile.buildx
devtools/ci/tasks/build-binaries.yml
devtools/ci/tasks/scripts/codecheck.sh
devtools/ci/tasks/test-smoketest.yml

Updates Dockerfiles and task files to use a versioned tag of the build-env image.

dev: lock build-env version

---

notification/slack/channel.go

Example log message: 
- `error="Slack: missing_scope; need one of channels:read,groups:read,mpim:read,im:read but got app_mentions:read"`
- `error="unable to authenticate to Slack: token_revoked"`
Fixes #1246 
- User will see "Permission Denied" instead of "Only Channels Supported" when Slack app has misconfigured scopes
- User will see "Permission Denied" instead of "User account must be linked" when goalert is unable to authenticate to the Slack app

notification/slack: fix missing Slack scope error

---

graphql2/graphqlapp/mutation.go
oncall/activecalculator.go
oncall/temporaryschedulecalculator.go
schedule/storetemporaryschedules.go
schedule/temporaryschedule.go
web/src/app/schedules/CalendarEventWrapper.js
web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx
web/src/app/schedules/temp-sched/TempSchedDeleteConfirmation.tsx
web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
web/src/cypress/integration/temporarySchedule.ts

- Fixes an issue where temp schedule shifts could be processed out-of-order.
- Fixes related issues where invalid data could cause the schedule page to break
- Ensure past data is not changed when updating/deleting temp schedule info
- When editing, historical shifts are no longer shown in the edit dialog
- Disables Edit and Delete on past shifts/temp schedules

schedules: fix breaking potential issues with temporary schedules

---

web/src/app/escalation-policies/PolicyServicesCard.tsx

This sorts the policy services by name to prevent shuffling by apollo polling
fixes #1460 
Users will not see the listed items spontaneously change order

ui/escalation-policies: sort services by name

---

web/src/package.json
web/src/webpack.config.js
web/src/webpack.prod.config.js
yarn.lock

Removes `ifdef-loader` as it's no longer used and quite expensive/slow during builds.

dev: remove ifdef-loader

---

retry/temporary.go
user/store.go

Fixes issues when deleting a user:
- User is removed from all rotations prior to deleting the row (works around rotation trigger conflicts for multi-row)
- Attempt is retried up to 5 times in case of temporary or fkey errors

users: fix fkey and rotation issues when deleting a user

---

devtools/ci/dockerfiles/build-env/Dockerfile

Adds `glibc` to the `build-env` image, as it's required by `protoc` for the gRPC work.

dev: add glibc to build-env

---

web/src/package.json
yarn.lock

> If you are using webpack v5 or above you do not need to install this plugin. Webpack v5 comes with the latest terser-webpack-plugin out of the box.
Closes #1542
I verified there is no change to our bundle size

ui: remove terser-webpack-plugin

---

.github/dependabot.yml

This PR sets dependabot to run at 9am CT Mon-Fri
https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#scheduletimezone

dev: fix dependabot schedule

---

web/src/babel.config.js

The recent babel update produces ridiculous amounts of spam when running `make start` this is the requested change from the warning.
```
UI         (err): Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
UI         (err): The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
UI         (err):       ["@babel/plugin-proposal-private-methods", { "loose": true }]
UI         (err): to the "plugins" …
```

dev: add explicit option to prevent babel warning spam

---

app/app.go
app/initauth.go
app/initgraphql.go
app/initstores.go
auth/basic/db.go
auth/basic/identityprovider.go
auth/basic/provider.go
graphql2/generated.go
graphql2/graphqlapp/app.go
graphql2/graphqlapp/user.go
graphql2/models_gen.go
graphql2/schema.graphql
user/user.go
util/errutil/maperror.go
validation/validate/username.go
web/src/app/lists/QueryList.tsx
web/src/app/users/UserCreateDialog.tsx
web/src/app/users/UserList.tsx
web/src/app/users/UserRouter.js
web/src/schema.d.ts

Currently, goalert admins can only create users for basic auth via the CLI. This PR brings that functionality into the UI.
Part of #1247 
Admins will have a create user fab on the users list page
```
createUser(input: CreateUserInput!): User
```
```
input CreateUserInput {
username: String!
password: String!
name: String
email: String
role: UserRole
}
```
- This functionality may move into a central user management page in the future

ui/users: create user dialog

---

app/middleware.go
assignment/target.go
config/config.go
graphql/createall.go
graphql/createallutil.go
graphql/escalation.go
graphql/label.go
graphql/rawtarget.go
graphql/scheduleassignment.go
graphql/schedulerule.go
graphql/userfavorite.go
graphql/useroverride.go
graphql2/mapconfig.go
smoketest/grahpqlv1deprecation_test.go
smoketest/harness/harness.go
web/src/app/admin/AdminConfig.tsx
web/src/app/rotations/RotationForm.js
web/src/cypress/support/config.ts
web/src/schema.d.ts

Defaults the `/v1/graphql` endpoint to be disabled (returning a 404) and decouples `assignment.RawTarget` from the old code.

api: disable old graphql endpoint by default

---

migrate/migrations/20210601113520-override-lock.sql
smoketest/harness/harness.go
smoketest/overrideconflict_test.go

It's currently possible for duplicate/overlapping overrides to be entered if they are done simultaneously. This PR resolves the issue by adding a lock to the validation trigger.
A new smoketest was added for this case, removing line 8 of the new migration should cause the test to fail.

overrides: lock table before duplicate check

---

graphql2/graphqlapp/mutation.go
graphql2/graphqlapp/parseuuid.go
graphql2/graphqlapp/schedule.go
oncall/store.go
schedule/storedata.go
schedule/storetemporaryschedules.go
util/sqlutil/nulluuid.go
util/timeutil/clock.go

This PR makes schedule data helpers more generic and switches to using UUID's directly for Temp Schedules methods. This is in prep for schedule notifications.

temp-schedules: use UUIDs and generalize data update method

---

escalation/store.go
notificationchannel/store.go
util/sqlutil/nulluuid.go

Reworks how notification channels are created from an always-create method to re-using existing if possible.

notificationchannel: ensure only a single copy of a type/value is created

---

web/src/app/schedules/CalendarToolbar.tsx
web/src/app/schedules/ScheduleCalendar.js
web/src/cypress/integration/scheduleCalendar.ts

This PR proposes a new calendar toolbar design that better aligns with Material's Design spec. It also includes fixes for some existing alignment and a11y issues
Month view:
Week that starts and ends in same month:
Week that starts and ends in different month, same year:
Week that starts and ends in different month, different year:
New Calendar toolbar design; same functionality.

ui/schedules: calendar toolbar design

---

web/src/app/details/DetailsPage.tsx

This PR converts list item icon buttons into simple icons in the lists of quick links
https://github.com/target/goalert/pull/1614

ui: prevent screen reader stutter on quick links

---

devtools/mockslack/server.go
smoketest/harness/harness.go
smoketest/harness/slack.go
smoketest/slackaddtoepstep_test.go
smoketest/slacknotification_test.go

Changes slack `ExpectMessage` assertion to be blocking, providing more useful errors and line numbers on failure.

smoketest: sync slack assertions

---

web/src/app/lists/FlatList.tsx
web/src/app/users/UserContactMethodList.tsx
web/src/app/users/UserNotificationRuleList.js

This PR fixes a CSS issue in Safari when rendering wider secondary list actions. It solves the immediate problem of the content wrapping, but there is some outstanding work to be done preventing longer list item text from rendering behind the secondary action. See additional info below for more context. This is an existing bug today, so a separate PR will address it.
Fixes #1500 
Safari users can manage contact methods
https://github.com/mui-org/material-ui/issues/13597
https://github.com/mui-org/material-ui/issues/13495

ui/users: fix secondary action rendering in safari

---

web/src/app/details/DetailsPage.tsx

This PR fixes an issue in which we render the string `"0"` when there are no quick links e.g. rotation details
JSX rules: https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored

ui/details: prevent rendering 0

---

smoketest/graphqlalert_test.go
smoketest/graphqlcreatescheduledefaultrotation_test.go
smoketest/graphqlupdaterotation_test.go

Fixes a test issue introduced by #1580 
The PR made `weekdayFilter` validation strict, so tests had needed to be updated with missing bool values -- missing values were incorrectly assumed to be false, but `rule.NewAlwaysActive` has them all default to true. Updating the values fixes the issue where the smoketest(s) could fail at certain times.

smoketest: weekdayFilter should be all-true

---

engine/schedulemanager/update.go
engine/schedulemanager/update_test.go

Adds a unit test and fix for the issue where the next notification time for the current day would move to the following week when some (but not all) weekdays are selected.
Fixes #1685

engine/schedulemanager: weekday filter fix

---

Makefile

Fixes an issue where installing the gRPC tools during `make` would result in the library being updated at the same time. This changes the usage of `go get` which includes updating to `go install` which will respect the version on the current branch.

dev: fix issue with gRPC tools auto-updating

---

notification/slack/channel.go

Fixes grammar issues based on the number of on-call users in schedule notifications to make notifications read naturally.
Before:
`No users are on-call for Schedule: Primary Schedule`
`Users: Foo are on-call for Schedule: Primary Schedule`
`Users: Foo, Bar are on-call for Schedule: Primary Schedule`
`Users: Foo, Bar, Baz are on-call for Schedule: Primary Schedule`
After:
`No users are on-call for Primary Schedule`
`Foo is on-call for Primary Schedule`
`Foo and Bar are on-call for Primary Schedule`
`Foo, Bar, and Baz are on-call for Primary Schedule`

schedule/notifications: make notifications more readable

---

notification/slack/channel.go
notification/slack/oncallnotification.go
notification/slack/oncallnotification_test.go

Pulls the rendering logic out of the `Send` method for Slack on-call notifications into a unit-testable function and adds tests for edge cases.

slack: unit tests for on-call messages

---

.github/workflows/main.yml

This PR uses a tool called reviewdog to give linting diagnostics for each push to an open pull request. For most cases, it will create a comment at the relevant line of code, but if it is unable to, the warning/error is found in the github actions log. This provides some redundancy with the `make check` command, but the developer experience is improved enough to justify such redundancy.
eslint:
prettier:
stylelint:
typescript type checking (only reported in logs):

ci: add frontend linting action

---

engine/message/db.go
engine/message/ratelimit_test.go
engine/message/throttle.go
engine/message/throttle_test.go
smoketest/manyalerts_test.go

This PR fixes an issue where messages can be throttled too aggressively.
In `engine/message/throttle.go` the timestamp of the first message within the window for the current rule is used to derive the location in a sliding time-window. It assumed messages were always recorded in order, however, sent messages originate from a map iteration during each engine cycle, which randomizes the order. This caused the calculations to be off when there had been messages over a longer period of time (e.g. an alert every 20 minutes).
This PR adds a unit test for the configured rate limits in `ratelimit_test.go`, as well as a unit test and smoketest that exercises the bug and fix.
Additionally, it was identified that in rare circumstances a message could be counted twice (though only …

engine/message: fix throttle delay bug

---

web/src/app/admin/AdminSMSSend.tsx

This PR fixes an issue where SMS messages cannot be sent from the admin toolbox page within the UI. The required `+` before the phone number was accidentally prepended to the input variable twice: once from the `TelTextField` component, and the second within the mutation variables.

admin/ui: fix SMS send tool

---

web/src/app/admin/AdminConfig.tsx
web/src/app/lists/ControlledPaginatedList.tsx
web/src/app/lists/PaginatedList.tsx
web/src/app/main/App.js
web/src/app/rotations/RotationForm.js
web/src/app/schedules/CalendarToolbar.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
web/src/app/users/UserSessionList.tsx

Resolves task :
- The prop `justify` of `ForwardRef(Grid)` is deprecated. Use `justifyContent` instead, the prop was renamed. 
...from 'remove material-ui deprecation warnings' #1762
Resolves a portion of 'remove material-ui deprecation warnings' #1762.
Other errors related to material ui v5 will be address in separate PRs
N/A
N/A
N/A
Error regarding 'justify content' no longer present

ui/materialUI justify->justifyContent

---

auth/authtoken/parse.go

Adds a 0-length check to the `auth/authtoken.Parse` function to prevent a possible panic found during fuzz-testing.

authtoken: add 0-length check to Parse

---

engine/message/db.go
engine/message/dedupalerts.go
engine/message/dedupalerts_test.go
smoketest/escalationnotification_test.go

If multiple notifications are pending for the same destination (e.g. SMS/number combo) and alert ID, only the oldest message will be sent instead of duplicates.
Additionally, this resolves an issue with message bundling where multiple notifications for a single alert could cause a "bundle" to be sent -- which is intended for situations when more than one alert is unacknowledged for a service at a time.

engine/message: dedup identical alert notifications

---

migrate/migrations/20210623104111-alert-status-subscriptions.sql

This PR fixes an issue that prevents migrate-up from finishing when `user_last_alert_log` contains an entry for a user who has status updates disabled.

migrate: only insert non-null values for status update migration

---

web/src/app/mui.js

Resolves task :
- createMuiTheme function was renamed to createTheme
...from  #1762
Resolves a portion of 'remove material-ui deprecation warnings' #1762.
Other errors related to material ui v5 will be addressed in separate PRs
N/A
N/A
N/A
Error regarding 'createMuiTheme' no longer present

ui/materialUI createMuiTheme -> createTheme

---

engine/message/bundlealerts.go
engine/message/bundlealerts_test.go
engine/message/db.go

This PR alters bundling behavior to re-use existing alert bundles instead of creating new ones where possible.

engine/message: re-use existing alert bundles when possible

---

web/src/app/wizard/WizardForm.js
web/src/app/wizard/WizardScheduleForm.js

This PR refactors a few instances where props were being mutated and `this.forceUpdate` was being called as a work around. The fix uses lodash's `deepClone` to create a mutable form value object.
This PR unblocks a couple of hooks conversions since there is no analog for `forceUpdate` in the functional paradigm. 
e.g. #1791 #1689

ui/wizard: remove usage of forceUpdate

---

engine/message/bundlealerts.go
engine/message/dedupalerts.go
engine/message/dedupalerts_test.go
engine/message/dedupconcallnotifications_test.go
engine/message/deduponcallnotifications.go
engine/message/dedupstatusmessages.go
engine/message/dedupstatusmessages_test.go
engine/message/splitpendingbytype.go
engine/message/splitpendingbytype_test.go
smoketest/oncallnotify_test.go

This PR fixes a bug where some messages would be "de-duplicated" even after being sent (rather than only for `pending` messages)
A helper function that handles splitting messages by type and sent status was added and applied to the dedup and bundle methods.

engine/message: don't dedup sent messages

---

devtools/sendit/token.go
go.mod
go.sum
keyring/store.go

Updates `github.com/dgrijalva/jwt-go` to the latest version, with a new import path: `github.com/golang-jwt/jwt`
This originally came up due to `CVE-2020-26160`. However, GoAlert token validation *requires* audience validation (not optional) and as such is not affected by the vulnerability.

dev: update jwt library

---

.github/dependabot.yml

This PR ignores patch updates for all javascript dependencies based on their semver. Security updates are not ignored. Dependabot is a great tool, but the patches can get noisy and are often entirely ineffectual, such as a typo fix in documentation.
Also see: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore

dev: ignore javascript dependency patch updates

---

web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx
web/src/cypress/integration/temporarySchedule.ts

Users have reported that the temporary schedule form can be confusing- especially when they only need to add one user as the add and submit buttons appear to do the same thing.
It was suggested that the submit button be disabled until at least one shift has been added, but currently we can't allow this as an empty Temporary Schedule is an acceptable way to block off time where nobody is on-call (for whatever reason).
- Add shift fab removed from the middle
- Add shift text button added under shift fields
- Step 2 text adjusted
The button renders as dark grey as that is what our secondary color in the theme is currently set to. I chose to use the secondary color to avoid adding tech debt …

ui/temporary schedules: adjust add button placement and header text

---

web/src/app/admin/AdminConfig.tsx
web/src/app/admin/AdminNumberLookup.tsx
web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertListItem.js
web/src/app/schedules/calendar-subscribe/CalendarSuccessForm.js
web/src/app/services/HeartbeatMonitorList.js
web/src/app/services/IntegrationKeyList.js
web/src/app/util/CopyText.tsx

The `CopyText` component has a `textOnly` prop. After using this component for some time, I have been under the assumption that this prop was used to display the component without the icon (i.e. only the title text). However, this is _not_ the case and has to do with if the user is copying a URL or not so it can be properly encoded from the `href` event target. This small discrepancy caused me to lose a good chunk of time, so I propose we refresh the API a tad, to avoid something like this in the future.
- `textOnly` -> `asURL`, logic flipped

ui/tech debt: update CopyText interface

---

web/src/app/alerts/components/UpdateAlertsSnackbar.js
web/src/app/dialogs/FormDialog.js
web/src/app/util/Options.js

The prop `onExited` of `ForwardRef(Dialog)` is deprecated. Use the `TransitionProps` prop instead.
...from ui: remove material-ui deprecation warnings #1762
Resolves a portion of 'remove material-ui deprecation warnings' #1762.
Other errors related to material ui v5 will be addressed in separate PRs
N/A
N/A
N/A
Error regarding 'onExited' no longer present

ui/mui onExited of ForwardRef(Dialog) is deprecated

---

web/src/app/main/App.js

Addresses Material UI warning:
```The prop `onEscapeKeyDown` of `ForwardRef(Modal)` is deprecated. Use the onClose prop with the `reason` argument to handle the `escapeKeyDown` events.```
...from ui: remove material-ui deprecation warnings #1762
Current usage appears to be redundant. Removed line.
Resolves a portion of 'remove material-ui deprecation warnings' #1762.
Other errors related to material ui v5 will be addressed in separate PRs
N/A
N/A
N/A
Error regarding 'onEscapeKeyDown' no longer present

ui/mui remove onEscapeKeyDown

---

web/src/app/admin/AdminSMSSend.tsx

This PR fixes an issue where a `button` within a `form` submits the form by default
This may be browser specific; reviewers may validate in Firefox and Chrome

ui/admin: prevent default form submit on sms test form

---

engine/message/db.go
migrate/migrations/20210806074405-outgoing-source-value.sql
notification/email/sender.go
notification/namedsender.go
notification/sender.go
notification/slack/channel.go
notification/status.go
notification/store.go
notification/stubsender.go
notification/twilio/call.go
notification/twilio/message.go
notification/twilio/sms.go
notification/twilio/voice.go
notification/webhook/sender.go

This PR adds a new column `src_value` to the `outgoing_messages` table in order to track the real-world source of sent messages.
The message module's version has been increased (8 -> 9) accordingly.

engine/message: track src_value of messages

---

dataloader/alertlogstateloader.go
graphql2/generated.go
graphql2/graphqlapp/alert.go
graphql2/graphqlapp/contactmethod.go
graphql2/graphqlapp/dataloaders.go
graphql2/graphqlapp/toolbox.go
graphql2/models_gen.go
graphql2/schema.graphql
notification/manager.go
notification/status.go
notification/store.go
web/src/app/admin/AdminSMSSend.tsx
web/src/app/users/SendTestDialog.tsx
web/src/app/users/UserContactMethodVerificationDialog.js
web/src/cypress/support/dialog.ts
web/src/schema.d.ts

This PR updates the Test and Verify dialogs, as well as the admin Send-SMS tool, to use the From value returned by Twilio when sending messages.
This is in preparation for SID support when the FromNumber config value may be a SID and multiple numbers could be used when delivering messages.
A new field, `formattedSrcValue` was added to the `NotificationState` type in the GraphQL schema.

ui: use real from number in dialogs

---

engine/statusupdatemanager/db.go
engine/statusupdatemanager/update.go
migrate/migrations/20210811110849-valid-status-updates-indexes.sql
smoketest/statusupdates_test.go
smoketest/statusupdatescancel_test.go

This PR fixes a number of issues/regressions with the status update code:
1. performance issue when querying for updates
2. sending messages after CM disabled, or status updates turned off
3. sending updates for events that are very old
4. updates went to users who initiated the action
The existing smoketest was updated to validate 4. A new smoketest was added to validate 2 & 3.
For the first issue, it's harder to reproduce but the query was rewritten to use subqueries to avoid scanning
the alerts table during the join resulting in 100x performance improvement in certain workloads.

engine/statusmanager: fix performance and behavior issues

---

migrate/migrations/20210813131213-sched-query-index.sql
oncall/store.go
web/src/cypress/integration/favorites.ts

This PR adds an index to `schedule_on_call_users` and updates the shift query to use `tstzrange()`. It is functionally identical to the prior query but makes use of the index to greatly reduce DB load.

oncall: index for schedule on-call query

---

engine/statusupdatemanager/db.go
smoketest/harness/harness.go
smoketest/statusupdateschannel_test.go

Fixes a bug that prevented status updates for notification channels (e.g., Slack) from working and adds a smoketest to check for this.

engine/statusmanager: fix status updates for notification channels

---

web/src/app/rotations/RotationUserDeleteDialog.js

Fixes an issue where deleting a rotation user listed before the currently active user from the UI would result in the rotation advancing.

ui/rotations: preserve on-call user when deleting

---

engine/schedulemanager/update.go
smoketest/harness/slack.go
smoketest/oncallnotify_test.go
smoketest/oncallnotifytod_test.go

Fixes an issue where multiple on-call notifications would fail to send at the same time (for separate channels).
When collecting the messages to be sent we were tracking them so that a schedule ID mapped to a single channel ID. Now they are stored as a slice of channel IDs -- with care taken to ensure we don't send duplicate messages to the same channel.

engine/schedulemanager: fix sending messages to multiple Slack channels at the same time

---

.github/dependabot.yml

This PR ignores luxon dependencies due to https://github.com/mui-org/material-ui-pickers/issues/1440
It seems we must wait for Material UI version 5, which will ship with newer pickers

ui: ignore dependabot updates for luxon deps

---

web/src/app/schedules/useOverrideNotices.ts

Effect is the noun and the direct cause, so you would “take effect”. You cannot take a descriptive word.
This PR fixes a grammar typo

ui/schedules: fix grammar affect -> effect

---

web/src/app/schedules/calendar/ScheduleCalendar.js
web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/schedules/temp-sched/sharedUtils.tsx
web/src/app/schedules/useOverrideNotices.ts
web/src/app/util/shifts.ts

This PR changes `parseInterval` and `trimSpans` to require an explicit timezone as the second parameter. Previously, these defaulted to `'local'` i.e. system zone. Without setting a zone, the interval's endpoints (start/end) will be in the system zone. Sometimes this doesn't matter e.g. simply checking if two intervals overlap, but the more I work with luxon, the more I wish they enforced explicit zones in their function signatures. Time without a location isn't a concept, and bugs will crop up if we aren't being deliberate about pairing time with location.
Summary of changes:
- use `'local'` for `ScheduleCalendar`
- use schedule zone for `TempSchedDialog`
- remove redundant `parseInterval` function
- remove unused `validateShift` function
- use schedule zone for …

ui/schedules: use explicit time zone when parsing intervals

---

engine/message/db.go
notification/namedsender.go
notification/status.go
notification/twilio/call.go
notification/twilio/message.go
notification/twilio/sms.go
notification/twilio/voice.go

Moves `SrcValue` to message status and populates it during Twilio status callbacks, lookups, and sent messages.
This is necessary because Twilio's messaging service does not provide the From number until later in the message/call lifecycle.

twilio: update src value from status

---

.github/workflows/main.yml

This PR disables @github-actions from running on draft PRs. We had a case where a draft PR wasn't fully linted yet and got bombarded with comments.
---
An alternative could be to continue running everything as we do now, but instead have the bot comment just once with something like
```
Linting failed for the following files:
web/src/someFile.ts
web/src/someOtherFile.ts
```
for drafts, instead of line by line.

github-actions: don't run on draft PRs

---

config/config.go
devtools/mocktwilio/server.go
smoketest/harness/harness.go
smoketest/twiliosid_test.go
web/src/app/admin/AdminFieldComponents.tsx
web/src/app/util/FromValueField.tsx

Turns on the ability to configure a Messaging Service SID as the Twilio FromNumber in the admin config.

Twilio: allow configuring messaging service SID as FromNumber

---

web/src/app/admin/AdminFieldComponents.tsx

This PR misses an oversight from introducing the new outlined default variant for TextFields coming with MUI v5. The admin page uses `Input` instead of `TextField`, so the import has been adjusted to use the proper Input (`OutlinedInput`) component.

ui/admin: use outlined input for admin fields

---

web/src/app/services/IntegrationKeyForm.tsx

This PR fixes an issue in which an end adornment conflicts with a select expand icon (see screenshot below). This adornment was a link to the integration docs, but there is already a link to those on the integration keys page.
Link to docs not available from end adornment of input field

ui/services: remove end adornment on integration key type select

---

web/src/app/documentation/Documentation.tsx

This PR prevents rendering the webhook in-app documentation when webhooks are not enabled by an admin

ui/docs: hide webhook docs when webhooks not enabled

---

web/src/app/schedules/calendar/ScheduleCalendar.js
web/src/app/schedules/calendar/ScheduleCalendarEventWrapper.js
web/src/app/schedules/calendar/ScheduleCalendarQuery.tsx
web/src/cypress/integration/scheduleCalendar.ts

Currently, the calendar only shows the resulting shifts from an override. This PR adds an override item to the calendar that shows the details of the override as-well. This lets you edit these details straight from the calendar. You can change the details of the override such as who is affected & for what duration. You can also remove overrides straight from the calendar.
Image of new override event on calendar.
Tooltip when calendar item is selected:
- The pencil icon takes you to the edit override dialog
- The trash can takes you to the delete override dialog
Users will now be able to see overrides on the schedule calendar, and perform edit and delete operations for current/future overrides via the …

ui/schedules: display override events on schedule calendar

---

web/src/app/schedules/ScheduleDetails.js
web/src/app/schedules/calendar/ScheduleCalendar.js
web/src/app/schedules/calendar/ScheduleCalendarQuery.tsx

This PR fixes an issue wherein resizing a schedule calendar override dialog would result in it disappearing. The fix involves lifting the dialog component a couple of levels in the component hierarchy such that it can be managed independent of the calendar component.
Users may now continue using override dialogs having resized their viewports

ui/schedules: persist render state of schedule calendar override dialog on screen resize

---

web/src/app/schedules/temp-sched/shiftsListUtil.ts

Will check if schedule interval is valid (end date is later than start date) and if not it won't try to render the no coverage shifts. Before this was throwing an error.
Fixes #1943 - This PR includes steps for recreating issue.
Before it crashed and showed console error. Now shows this:

ui/temp-schedules: Add check for valid schedule interval before running operations on it

---

notification/twilio/voice.go

Adds the missing switch case for the Stop option for test calls.

twilio/voice: add case for Stop digit

---

search/render.go

Replaced check for splitting characters in a regex string with a check for unicode characters to enable search for users with non-english names. 
Fixes https://github.com/target/goalert/issues/1931

fix: user search for non-ASCII characters 

---

web/src/app/dialogs/FormDialog.js
web/src/app/schedules/calendar/ScheduleCalendarOverrideDialog.js
web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx

This PR has some finishing touches for the Temp Schedules redesign:
- Fixes shift list loading spinner placement
- Fixes right hand pane placement (wrap in Grid container)
- Fixes subheader overflow issue, but subheaders are no longer sticky
- Keeps height of dialog 100%
- Add Shift form is now "sticky" and will follow a user's vertical scroll
- Adds vertical spacing between left and right pane on mobile
Sticky Add Shift form:
A smoother experience :)
React:
`FormDialog` has a new `fullHeight` boolean prop that, when set, will make the dialog have a height of 100%.

ui/schedules: refine temporary schedule dialog css

---

web/src/app/lists/FlatList.tsx
web/src/app/schedules/ScheduleDetails.js
web/src/app/schedules/temp-sched/TempSchedAddNewShift.tsx
web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
web/src/app/schedules/temp-sched/sharedUtils.tsx
web/src/app/schedules/temp-sched/shiftsListUtil.test.ts
web/src/app/schedules/temp-sched/shiftsListUtil.ts
web/src/cypress/integration/temporarySchedule.ts

This PR adds the ability to click on a "No Coverage" notice within the Temporary Schedules Dialog to set the shift's start and end times in the form.
e.g.
1. 24hr No Coverage on Oct 14th
2. Clicking this would set the start to `October 14th, 12:00 AM`, and the duration to `24 hours`
- Coverage Notices within the Temporary Schedule Dialog are now clickable buttons
- Clicking a coverage notice will also cause the shift form to expand open, if closed

temp schedules: no coverage notice interaction

---

web/src/app/schedules/ScheduleDetails.js

Small fix to resolve console error in schedules page when slack is not enabled:

ui/schedules: Fix console error from malformed props

---

web/src/app/schedules/temp-sched/TempSchedAddNewShift.tsx
web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
web/src/app/schedules/temp-sched/sharedUtils.tsx
web/src/app/schedules/temp-sched/shiftsListUtil.tsx
web/src/app/util/timeFormat.test.ts
web/src/app/util/timeFormat.ts

This PR converts the time utils to typescript, removes the unused `logTimeFormat`, and adds two new general[purpose utilities: `fmtTime` and `fmtLocal`. 
This is a refactor. No changes in behavior are expected.

ui/util: time formatting helpers

---

alert/log/store.go
app/inithttp.go
config/config.go
devtools/mockslack/actions.go
devtools/mockslack/api.go
devtools/mockslack/chatpostmessage.go
devtools/mockslack/chatpostmessage_test.go
devtools/mockslack/server.go
devtools/mockslack/state.go
engine/backend.go
engine/engine.go
engine/sendmessage.go
graphql2/mapconfig.go
notification/alertstatus.go
notification/namedreceiver.go
notification/receiver.go
notification/resultreceiver.go
notification/slack/channel.go
notification/slack/servemessageaction.go
smoketest/harness/harness.go
smoketest/harness/slack.go
smoketest/slackinteraction_test.go
smoketest/statusupdateschannel_test.go
user/store.go
validation/fieldvalidationerror.go
web/src/schema.d.ts

Adds two-way interactivity as an option for Slack notifications.
Summary of changes:
- make alert log store support both contact methods and notification channels for ack/close actions
- new http route `/api/v2/slack/message-action` added
- new config option `Slack.InteractiveMessages` to opt-in
- action support in the mockslack server
- new `ReceiveSubject` method that can map a provider/subject ID to a GoAlert user for notification channel responses
- remove `alert` as a dependency for the `notification` package by using a new AlertState type instead of alert.Status
- updated Send() method in Slack ChannelSender to add action blocks
- added support for Ephemeral messages and actions and assertions in test harness/mockslack
- added slack interaction …

notification/slack: add interactivity to alert notifications

---

app/contextlocker.go
devtools/sendit/client.go
devtools/sendit/session.go
docs/development-setup.md
docs/getting-started.md
notification/receiver.go
notification/status.go
permission/context.go
permission/context_test.go
retry/do.go
schedule/storetemporaryschedules.go
switchover/README.md
web/src/app/alerts/CreateAlertDialog/useCreateAlerts.js
web/src/app/details/Notices.tsx
web/src/app/forms/README.md
web/src/app/schedules/ScheduleOverrideCreateDialog.js
web/src/app/schedules/calendar/ScheduleCalendarOverrideDialog.js
web/src/app/util/safeURL.ts
web/src/cypress/support/form.ts

Ran `go run github.com/client9/misspell/cmd/misspell -locale US`  to correct some spelling mistakes.

dev: spelling fixes

---

config/hints.go
docs/getting-started.md
graphql2/graphqlapp/slack.manifest.yaml
graphql2/mapconfig.go
web/src/app/admin/SlackActions.tsx
web/src/cypress/integration/admin.ts

Adds a callback URL hint in Slack config, adds missing scope to the app manifest, and renames button to "App Manifest" rather than "Create New App" now that Slack allows editing/updating the manifest for existing apps.

slack: add hints and update manifest

---

web/src/app/schedules/calendar/ScheduleCalendarQuery.tsx

Work-around for #1987 by raising overrides fetched per-page from 15 (default) to 149. 
**Out of scope:**
If there are more than 149 overrides for a schedule (unlikely, but still a limit to keep in mind), they won't all be queried. Would need a more permanent fix like #2028 to handle that.

ui/schedules/calendar: Increase override query page size for calendar

---

web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
web/src/cypress/integration/temporarySchedule.ts

This PR resolves an issue where editing a temporary schedule could result in a 422 error caused by the ``displayStart`` property in the shift object on submit. Fix includes omitting ``displayStart`` from the shift object before submitting and adding additional testing coverage.

ui/temp-sched: omit displayStart from shift object on submit

---

notification/slack/channel.go

Adds the link text as the `Fallback` parameter so that notifications appear correctly. (fixes "No preview available" issue)

slack: add missing fallback field for alert notifications

---

web/src/app/lists/FlatList.tsx

This PR fixes a regression in which rotations would not highlight the active on-call user list item.
Users will once again see the lime highlight color for active on-call users.
Regression introduced here: https://github.com/target/goalert/commit/a30960f29e1ca7de6c0463517a0c51988f717e35

ui/lists: fix list item highlighting

---

.eslintrc.js
web/src/app/tsconfig.json
web/src/babel.config.js
web/src/jsconfig.json
web/src/package.json
yarn.lock

This PR removes support for the class decorator transform which is considered legacy (see https://babeljs.io/docs/en/babel-plugin-proposal-decorators).
Sticking to native language features also has the added benefit of increasing our compatibility with other tooling in the JS/TS ecosystem.

ui: remove class decorator transform

---

graphql2/generated.go
graphql2/gqlgen.yml
graphql2/graphqlapp/query.go
graphql2/models_gen.go
graphql2/schema.graphql
notification/recentmessage.go
notification/status.go
notification/store.go
web/src/schema.d.ts

Adds a `debugMessages` query that can be used by an admin to retrieve a list of recent messages from the `outgoing_messages` table.

graphql: add debugMessages query

---

config/config.go
engine/cleanupmanager/db.go
engine/cleanupmanager/update.go
graphql2/mapconfig.go
smoketest/alertcleanup_test.go
web/src/schema.d.ts

The PR introduces cleanup for 3 additional tables: `user_overrides` `schedule_on_call_users` and `ep_step_on_call_users`
Fixes #916 
In admin config panel, "Alert Cleanup days" has been renamed to "Data cleanup days", and the associated description has been updated appropriately.
Deprecated `'Maintenance.AlertCleanupDays'` in favor of `'Maintenance.DataCleanupDays'`

engine/cleanupmanager: on-call cleanup

---

web/src/app/alerts/AlertsList.js
web/src/app/lists/QueryList.tsx
web/src/app/main/components/NewUserSetup.js
web/src/app/schedules/ScheduleOverrideForm.js
web/src/app/services/ServiceRouter.js
web/src/app/util/ISOPickers.tsx

This PR makes all interactions with URL query parameters use the `useURLParam` and `useResetURLParams` hooks. Using these interfaces consistently isolates the concerns of getting/setting URL params, making it more maintainable e.g. if we need to add any sort of middleware, it can be done in one place.

ui: refactor URL query parameter interactions

---

notification/slack/oncallnotification.go
sysapiserver/server.go
user/store.go

This PR fixes a regression caused by a subtle change in the way AuthSubjectsFunc works. The `userID` parameter now takes an explicit slice and the sysapiserver package now only includes a slice value if `userID` is not empty.
The regression was caused by the change from calling with an empty userID being interpreted as a slice with a single empty user id (failing validation) when the last parameter was changed from a string to a variadic slice of strings.

gRPC/user: fix user ID filter parameters

---

dataloader/ncloader.go
graphql2/graphqlapp/dataloaders.go
graphql2/graphqlapp/query.go
graphql2/graphqlapp/schedule.go
notificationchannel/store.go

Causes notification channel lookups to be batched by a new dataloader. Fixes issue in #2061 where too many logs resulted in access denied due to a recursive lookup.

graphql: batch notification channel requests

---

alert/alert.go

This PR increases the maximum length for a given alert's summary. The current limit set in place is a remnant from when SMS was one of the only alerting options, but this is no longer the case. Each notification module should handle its own truncating of the summary (and description), if necessary.
Closes #2053

alert: increase max summary length to 1kb

---

web/src/app/actions/hooks.test.ts
web/src/app/actions/hooks.ts
web/src/app/alerts/AlertsList.js
web/src/app/escalation-policies/PolicyStep.js
web/src/app/schedules/calendar/ScheduleCalendarToolbar.tsx
web/src/app/schedules/calendar/hooks.ts

This PR continues our effort to reduce our dependency on redux for client side routing by:
- refactoring `useURLParam` to use the `react-router` API's directly
- writing unit tests for _getting_ a URL param and sanitizing param values pre-_setting_ them
- refactoring `useURLParam` to share logic in `setURL`, and to not clear all params by default if an empty list is passed (too much magic, unrealistic use case)
**API changes:**
- Introduce a new `useURLParams` hook that accepts an object of name-defaultValue pairs, and returns a `[params, setParams]` array. This prevents issues that crop up when invoking `setParams` synchronously in a single render frame. This case is further handled by aborting and logging an error to the console.
- An example of this issue and its …

ui: refactor `useURLParam` and `useResetURLParams`

---

graphql2/graphqlapp/query.go

This PR fixes a bug where the alert ID was not returned if present when querying for a DebugMessage.
---
Before:
After:

admin/graphql: add alert ID to debugMessage query

---

web/src/app/admin/AdminNumberLookup.tsx
web/src/app/admin/AdminSMSSend.tsx

This PR wraps up some minor tech debt around where we use the `noSubmit` prop for `LoadingButton`, investigating all the places where the onClick function can be instead moved to the parent Form's `onSubmit` instead to remove the use of the `noSubmit` prop, closing #1839.
There were only a few places the prop was being used so there wasn't much to update.
**How to test:**
1. Login as an admin, visit the toolbox on either **Chrome** or **Firefox**
2. Press enter while focused on the **Phone Number** field for the **Twilio Number Lookup** section
3. (Acceptance Criteria) Form should attempt to submit, and the page should not incidentally refresh
4. Repeat test for a TextField in the **Send SMS** section
5. Repeat both tests in the other browser

ui/a11y: move onClick to form onSubmit functions

---

util/timeutil/duration.go
util/timeutil/duration_test.go

This PR introduces a utility for parsing ISO duration strings into an object. The supported formats are `PnYnMnDTnHnMnS` and `PnW`. `P` (for Period) is always first, and `nX` represents `n` units of `X`. `T` is a separator between the nominal date components and the accurate time components.
References include this [ISO working paper](https://www.loc.gov/standards/datetime/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf) and [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#appendix-A).
Additional context is provided in code comments.

timeutil/duration: add `ParseISODuration`

---

Makefile

Updates `make clean` target to only cleanup build output and node_modules, leaving things like `Procfile.local` or config backups intact

dev: only rm build and node_modules on `make clean`

---

alert/alertlog/legacysearch.go
alert/alertlog/search.go
alert/alertlog/store.go
alert/logentryfetcher.go
alert/store.go
app/app.go
app/initstores.go
engine/config.go
engine/escalationmanager/db.go
engine/message/db.go
engine/npcyclemanager/db.go
escalation/store.go
graphql2/graphqlapp/app.go

Closes #2127, removing the alertlog interface in favor of using structs

alert/alertlog: convert Store from interface to struct

---

devtools/resetdb/datagen.go
devtools/resetdb/main.go

This PR adds records to `alert_logs` when running `make regendb`.
Fixes #2138
**How to test:**
1. Run `make regendb`
2. Verify that `alert_logs` contains a "created" event for every alert, and that closed alerts have a corresponding "closed" event. Closed events are timestamped after the relevant created event.

regendb: seed the `alert_logs` table

---

web/src/app/main/components/ToolbarTitle.js

This PR makes the breadcrumb links push to the native navigation stack (instead of replacing the latest entry). This prevents several strange scenarios that a user may experience when navigating with mixed use of the breadcrumbs and the native browser navigation.
Fixes #2048

ui/main: fix breadcrumb navigation

---

Makefile
Procfile
Procfile.cypress
Procfile.cypress.prod
Procfile.prod
app/cmd.go
app/config.go
app/initengine.go
engine/config.go
engine/engine.go

This PR fixes some noise issues in the log output.
- Engine cycle is no longer logged by default
- After 5 sec, warnings will be logged with an error at the end of the cycle
- An error will be logged each minute if a cycle is stuck that long
- "Build Failed" will be logged and retried after 3sec on failure with `make start` instead of exiting
- Prometheus is changed to `warn` log level
- Cypress tests should no longer spam make messages
Fixes #2156 
Fixes #2157 
Request logging has been left out and can be addressed separately (or with #2106 )

dev: Fix make start output

---

notification/slack/channel.go
notification/twilio/alertsms.go
util/rendersize.go
util/rendersize_test.go

Limits the length of details in the original slack message to 3000 characters.
This is done with a new helper `RenderSize` (and `RenderSizeN` for some alert messages) that will use a render function and assert the length is within the limit. If it is not, it performs a binary search to trim the input until it fulfills the requirement.
Fixes #2175

slack: limit details to 3000 characters

---

web/src/app/alerts/components/AlertsListFilter.js
web/src/app/lists/ControlledPaginatedList.tsx
web/src/app/util/OtherActions.js

Cleans up the implementation of the Icon and IconButton in `OtherActions`. If an icon was provided as a prop, it wouldn't be rendered with an `IconButton` as it was only being added to the JSX from the `defaultProps` section.
Also fixes the color of an IconButton for the `AlertsListFilter` to match the checkbox OtherActions within the page, for consistency.

ui/tech debt: OtherActions

---

web/src/app/alerts/pages/AlertDetailPage.js
web/src/app/escalation-policies/PolicyDetails.js
web/src/app/escalation-policies/PolicyRouter.js
web/src/app/escalation-policies/PolicyServicesQuery.js
web/src/app/main/components/ToolbarTitle.js
web/src/app/rotations/RotationDetails.js
web/src/app/rotations/RotationRouter.js
web/src/app/schedules/ScheduleAssignedToList.js
web/src/app/schedules/ScheduleDetails.tsx
web/src/app/schedules/ScheduleOverrideList.js
web/src/app/schedules/ScheduleRouter.js
web/src/app/schedules/ScheduleRuleList.js
web/src/app/schedules/ScheduleShiftList.js
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.tsx
web/src/app/services/AlertMetrics/AlertMetrics.tsx
web/src/app/services/HeartbeatMonitorList.js
web/src/app/services/IntegrationKeyList.js
web/src/app/services/ServiceAlerts.js
web/src/app/services/ServiceDetails.js
web/src/app/services/ServiceLabelList.js
web/src/app/services/ServiceRouter.js
web/src/app/users/UserCalendarSubscriptionList.js
web/src/app/users/UserDetails.js
web/src/app/users/UserOnCallAssignmentList.tsx
web/src/app/users/UserRouter.js
web/src/app/users/UserSessionList.tsx

Upgrades to use `useParams()` hook for getting router's internal state as recommended by [react-router v5.1](https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v51).
Required for #2108

ui/deps: use recommended react-router v5.1 hooks

---

migrate/migrations/20220224125018-schedule-data-id.sql
smoketest/switchover_test.go
switchover/dbsync/table.go

This PR adds a unique `id` column to `schedule_data` required for switchover operation. Without it updating this table (or any missing a unique `id` column) in any way during a switchover would result in an error during the `change_log` trigger.
In addition, a smoketest has been added to detect this and any other configuration problems, like circular dependencies, during testing.

switchover/dbsync: add smoketest to detect table configuration problems

---

web/src/app/error-pages/Errors.js
web/src/app/main/App.js
web/src/app/styles/base/elements.css
web/src/app/util/SetFavoriteButton.tsx

Fixes a few dark mode color issues missed in review:
- GenericError was rendering black-on-black, updated to match the rest of the error components
- Replace red-on-black with primary color for both fav buttons and links
More info:
https://accessibility.psu.edu/color/colorvisiondetails/
---
Old vs. New
Simulated examples:
Protanopia (no red)
Deuteranopia (no green)
Tritanopia (no blue)
Achromatopsia (no color)
Contrast Loss

darkmode: fix generic errors and red-on-black for fav and links

---

calsub/render.go
calsub/store.go
calsub/subscription.go
calsub/subscriptionconfig.go
graphql2/graphqlapp/calendarsubscription.go

This PR replaces `calsub.Subscription` Store updates with calls into form.
- added a `BeforeUpdate` hook with relevant validation and scope
- moved render/iCal to it's own file

calsub: move subscription updates to gorm

---

devtools/resetdb/main.go

This PR fixes a regression in which the alerts table's alerts_id_seq sequence was not being updated after the COPY command. Without this, a developer cannot readily create alerts locally.

dev: fix resetdb

---

web/src/app/lists/PaginatedList.tsx
web/src/app/util/avatars.tsx

This PR adds skeleton loader placeholders for paginated list items and the current user avatar.
Part of #2214 
https://user-images.githubusercontent.com/17692467/157275101-5100dcfc-a761-453b-a31d-7eb6b2de65be.mov
https://user-images.githubusercontent.com/17692467/157275105-a9f6ee28-af76-4da2-903d-922e0d1d2f9f.mov

ui/theme: introduce skeleton loading placeholders

---

web/src/app/rotations/UserForm.js

This PR fixes a spacing issue due to a missing Grid item. Before, the form field was not centered and it was cut off at the top. To review this, you can hide whitespace.
Before:
After:

ui/rotations: fix user form styles

---

web/src/app/escalation-policies/PolicyStepForm.js

This PR makes the escalation policy step form field badges accessible in dark mode.
Part of #2214 
Before: 
After:

ui/theme: make EP form field badges accessible

---

web/src/app/util/Diff.tsx

This PR makes the admin diff dialog accessible in dark mode.
Before:
After, dark:
After, light:

ui/theme: make admin config dialog accessible

---

web/src/app/util/AppLink.tsx

This PR uses the default link color instead of the `secondary` variant that is currently implemented. Both pass the a11y contrast tests, but the default (`primary`) color stands out and matches the nav link button colors.
Before:
After:
Discussion in #2229

ui/theme: use primary variant for link color

---

web/src/app/schedules/calendar/ScheduleCalendar.tsx
web/src/app/schedules/calendar/ScheduleCalendarEventWrapper.tsx
web/src/app/styles/base/elements.css

Updates the border styling and shift colors for the schedule calendar to better-fit dark and light modes.
Part of #2214
**Out of scope:**
Coloring when a shift is selected is not altered. It seems this is a bug in master as well. Left out of scope for now though I did give it my best effort- might open a separate issue.
---
**Light Mode - Monthly View, Before**
**Light Mode - Monthly View, After**
---
**Dark Mode - Monthly View, Before**
**Dark Mode - Monthly View, After**
---
**Light Mode - Weekly View, Before**
**Light Mode - Weekly View, After**
---
**Dark Mode - Weekly View, Before**
**Dark Mode - Weekly View, After**

ui/theme: apply theme coloring to calendar

---

web/src/app/theme/themeConfig.tsx

This PR changes the background colors in light mode to aid a11y by increasing contrast on the cards. I think this is the only place in #2217 in which we strayed from the generated palette and I think it shows.
Closes #2260

ui/theme: invert background colors in light mode

---

engine/cleanupmanager/db.go

Lowers the batch size for log cleanup to 100 (down from 1000) matching limits on other cleanup targets. Resolves an issue where log cleanup could keep timing out.

engine/cleanup: max 100 logs at a time per-tick

---

engine/statusupdatemanager/update.go

Fixes issue where multiple engine nodes result in erroneous log entries.

engine/statusupdatemanager: don't log lock errors

---

engine/metricsmanager/db.go
engine/metricsmanager/update.go
migrate/migrations/20220317153438-alert-metrics-add-closed-at.sql

This PR populates a `closed_at` column in `alert_metrics` that will help with the implementation of #2122 
It also refactors the operation to work from oldest to newest, maintaining a `(timestamp, id)` cursor in the engine's state. To regenerate `alert_metrics` e.g. to catch any that were missed, one only needs to reset the engine state.
**How to validate:**
1. `make regendb` and `make start`
2. For each engine cycle, observe `alert_metrics` being populated (500 at a time) and the `engine_processing_version.state` value incrementing in a forward fashion
3. Wait for step 2 to finish, and observe that count(alert_metrics) == count(alerts where status = 'closed')
4. Create and close an alert
5. Wait two minutes before observing the new row in `alert_metrics` and the new …

engine/metrics: populate closed_at field in alert_metrics

---

web/etaghandler.go
web/handler.go

This PR fixes the Cache-Control HTTP response header syntax
You can confirm the issue for different deployments using https://redbot.org

web: fix cache-control header syntax

---

devtools/resetdb/datagen.go
engine/metricsmanager/db.go
engine/metricsmanager/update.go
migrate/migrations/20220329170727-add-daily-alert-metrics.sql

This PR adds a new `daily_alert_metrics` table that aggregates metrics from `alert_metrics`. We do this basically as a cacheing strategy for the metrics API targets. 
**How to test:**
1. `make regendb`
2. `make start`
3. Watch `engine_processing_versions.state` update where `type_id = 'metrics'`
4. The state's `LastMetricsDate` will never exceed the date of `LastLogTime`. Therefore, to get metrics for the current day, one must look in `alert_metrics`.
5. Observe rows being added in `alert_metrics` and `daily_alert_metrics` over time.
Closes #2122 
**Additional Information:**
This PR modifies the local dev alert generation to be spread across the previous 30 days as opposed to 2 hours. This makes testing more interesting and realistic.

engine/metricsmanager: add `daily_alert_metrics` table

---

web/src/app/main/components/ToolbarAction.js
web/src/app/util/Search.js

fixes the invisible icon buttons in the appbar when in mobile/light mode
in light mode, both the appbar and icon buttons are set to the primary color. in dark mode, the appbar is a shade of grey. dark mode is unaffected by this change.
before:
after:

ui: fix appbar icon buttons in light mode

---

web/src/app/alerts/AlertDetailLogs.js

This PR fixes an issue in which alert log events would be shuffled at random upon Apollo polling. The solution orders the log entries by timestamp in desc order. We also query the `id` fields for improved cacheing.
To validate, create an alert with many event log entries and observe the list for a minute to make sure polling does not shuffle the list items.

ui/alerts: fix log events order

---

web/src/app/services/AlertMetrics/AlertCountGraph.tsx
web/src/cypress/integration/services.ts

This styles the alert metrics graph using our MUI theme and MUI Paper, Typography elements for the graph's tooltip.
Fixes #2310
https://user-images.githubusercontent.com/17692467/164507385-4747787f-04b3-4cec-bab6-3051f4fe6911.mov

ui/services/alertmetrics: fix alert metrics graph styles

---

devtools/pgdump-lite/cmd/pgdump-lite/main.go
devtools/pgdump-lite/dumpdata.go
smoketest/harness/harness.go

Adds a skip/exclude tables option as `-T`, similar to the exclude tables option in `pg_dump`.

devtools/pgdump-lite: exclude tables option

---

devtools/simpleproxy/main.go
devtools/simpleproxy/roundrobin.go

Allows multiple destinations separated by commas and performs round-robin-based load balancing to the `simpleproxy` tool.
**Review**
Add a second instance of goalert and the proxy to `Procfile.local` (create if it doesn't exist)
```Procfile
goalert2: ./bin/goalert -l=localhost:3032 --ui-dir=web/src/build --db-url=postgres://goalert@localhost
proxy: go run ./devtools/simpleproxy -addr=localhost:3033 http://localhost:3030,http://localhost:3032
```
- run `make start`
- visit `http://localhost:3033`
- perform some mutations and ensure both `goalert` and `goalert2` show up in the log output and the requests are successful.

devtools/simpleproxy: add round-robin support

---

Makefile.binaries.mk
devtools/slowproxy/main.go
devtools/slowproxy/ratelimiter.go

Adds a new tool, `slowproxy` that can simulate network latency, jitter, and throughput constraints for testing.
**Review**
Add slowproxy to `Procfile.local` (create if necessary)
```Procfile
proxy: go run ./devtools/slowproxy -l localhost:3033 -c localhost:3030 -d 25ms -j 10ms
```
- run `make start`
- visit `http://localhost:3033`
- verify application works
- try other options to change behavior
```
$ go run ./devtools/slowproxy -h
Usage of /tmp/go-build2557664850/b001/exe/slowproxy:
-c string
Server connect address. (default "localhost:5432")
-d duration
Min latency (one-way).
-i int
Max data rate (in bytes/sec) from server to client.
-j duration
Jitter in (random +/- to latency).
-l string
Listen address. (default "localhost:5435")
-o int
Max data rate (in bytes/sec) …
```

devtools/slowproxy: add slowproxy tool to emulate slow network conditions

---

web/src/app/schedules/ScheduleOverrideForm.js
web/src/app/schedules/ScheduleRuleForm.js
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
web/src/app/schedules/temp-sched/TempSchedDialog.tsx

Now that the displayed times can't be toggled between zones in schedule dialogs, we're updating the hint text from "Configuring in America/Chicago" to "Times shown in schedule timezone (America/Chicago)".
https://github.com/target/goalert/issues/2280
schedule override - before
schedule override - after
temp schedule - before
temp schedule - after
edit notification rule - before
edit notification rule - after
edit rotation rules - before
edit rotation rules - after

ui/schedule: update timezone hint text

---

web/src/app/schedules/ScheduleOverrideList.js

The schedule override list was querying for data on every state change (e.g. when opening the create override dialog) because the `start` query variable was being recalculated each time. This was causing consistent test failures due to a race condition where the list may or may not have been loading while the Cypress runner was attempting to click on elements.
Example screenshot of loading the override list and then clicking the create override fab shortly after. You can see that the start time is slightly in the future.
With this change, `start` will only be calculated and used if the filter changes from `showPast === true`, back to using a start time of now.

cypress/overridelist: don't update queryVariables on every state change

---

engine/metricsmanager/db.go

This PR updates the metrics manager to do nothing if data gets out of sync on inserting to daily alert metrics table.
Fixes #2368

engine/metricsmanager: fix daily alert metrics out of sync

---

web/src/cypress/integration/temporarySchedule.ts

Fixes flakiness on temporary schedule tests on month edges by fixing start times of tests to begining of a future month instead of the current time.

run temp sched tests on future time

---

calsub/http.go

This PR increases the calendar subscription window of calculated shifts from 1 month to 1 year.
Fixes #1459 
This change will not require any action from any users that have existing subscriptions created.  The next time a calendar agent fetches from subscription endpoint, data for the full year will be pulled. 
**Notes:**
An analysis of impact using a worst case scenario for number of shifts (hourly rotation with 2 users, on call 24x7) resulted in a payload of 1.2 MB for 1 year (from 102 KB for 1 month).  No noticeable detrimental effect on query execution times or request duration on calendar subscription endpoint.  Application logs were reviewed and real-world payload sizes were …

calendar subscription: increase calculated shifts from 1 month to 1 year

---

web/src/app/lists/FlatList.tsx
web/src/app/users/UserCalendarSubscriptionList.tsx

ui/users: convert UserCalendarSubscriptionList file to typescript

---

web/src/app/main/components/ToolbarAction.js

Fixes the "Back a Page" button color when in light mode.
MUI renders the appbar in light mode as `primary`, but as the `surface` color when in dark mode. This causes conflicts as our icon buttons default to a `primary` color. Because of this I opted to make a fix inline as opposed to a change at the theme level.
Before:
After:

ui: fix appbar icon color in light mode

---

Makefile
Procfile.cypress
Procfile.cypress.ci
Procfile.cypress.prod
devtools/ci/dockerfiles/build-env/Dockerfile
devtools/ci/dockerfiles/build-env/start_postgres.sh
devtools/ci/dockerfiles/build-env/stop_postgres.sh
devtools/ci/dockerfiles/goalert/Dockerfile
devtools/ci/tasks/build-all.yml
devtools/ci/tasks/build-binaries.yml
devtools/ci/tasks/scripts/build-all.sh
devtools/ci/tasks/scripts/build-binaries.sh
devtools/ci/tasks/scripts/codecheck.sh
devtools/ci/tasks/test-smoketest.yml
devtools/pgdump-lite/dumpdata.go
devtools/runproc/parse.go
devtools/runproc/prefixer.go
devtools/runproc/process.go
devtools/runproc/runner.go
devtools/runproc/task.go

This PR updates the `build-env` image to have the necessary dependencies to run Cypress tests, allowing all build steps to be run in the same container.
- New `Procfile.cypress.ci` added for running Cypress tests in CI
- runproc has a new annotation `@oneshot` allowing it to be used for running tests
- `build-env` is now based on debian instead of alpine and contains google chrome pre-installed
- A new `build-all.yml` task was added to replace the smoketest, binary, and integration steps
- `pgdump-lite` now sets proper isolation options
This PR is just a first step, adding the new build task which will be transitioned to at a later time. The primary change with this PR is the tool fixes and the build-env image having missing deps added. Existing pipeline …

dev: Single build image

---

smoketest/rotationdeluser_test.go
user/store.go

When deleting a user as an admin, if that user was a member of a rotation, the active index would stay the same, even if deleting the user shortened the list of participants.
Fixes #2373

rotation: maintain active user when deleting a user on the rotation

---

web/src/cypress/support/util.ts

This PR fixes an issue with the alert metrics cypress tests failing on retry because the engine processing state needed to be reset before each test.

cypress: add reset for engine processing version state

---

web/src/cypress.json

At the moment we don't collect video or screenshots from CI, so waiting for video encoding just makes builds take longer.

ci: disable cypress video

---

web/src/app/main/components/ToolbarPageTitle.tsx

Fixes an issue with the new breadcrumb code where navigating to an admin page from a details page would show the details item name (e.g., a schedule) as the second link instead of the proper admin page.

breadcrumbs: only return name for UUID values

---

Makefile
Makefile.binaries.mk
app/healthcheck.go
app/inithttp.go
devtools/genmake/run.go
devtools/pgmocktime/cmd/pgmocktime/main.go
devtools/pgmocktime/mocker.go
engine/cyclemonitor.go
engine/engine.go
smoketest/harness/harness.go
smoketest/harness/slack.go
web/src/cypress/integration/calendarSubscriptions.ts
web/src/cypress/integration/profile.ts
web/src/cypress/integration/services.ts
web/src/cypress/integration/users.ts
web/src/cypress/plugins/index.js
web/src/cypress/support/sql.ts

This PR allows for the manipulation of space and time within the confines of a Postgres database.
It is now possible to move time forward, back, alter its speed, reverse its flow, and even go back to a specific point in the future. Engine cycles can be triggered using 2-stages for more efficient test runs (grab ID, trigger cycle, wait for ID).
This work also resolves a long-standing issue where the DB time code for smoketests changed the engine's perception of time, but failed to account for DEFAULT values in the tables. It is now possible to control things like alert-log timestamps to the millisecond, by freezing altering the passage of time.
- There is a new endpoint `/health/engine/cycle` that will return the next engine cycle ID
- The `/health/engine` endpoint now …

dev: upgrade time circuits and add a flux capacitor (engine cycle monitor and pgmocktime)

---

alert/alertmetrics/store.go
graphql2/generated.go
graphql2/gqlgen.yml
graphql2/graphqlapp/alert.go
graphql2/graphqlapp/dataloaders.go
graphql2/schema.graphql
web/src/schema.d.ts

This PR adds a dataloader and a `metrics` prop to the `Alert` type.
Only the `escalated` value is supported, `timeToAck` and `timeToClose` will be handled in a separate PR.

graphql: add metrics prop to Alert type

---

web/src/app/main/components/ToolbarPageTitle.tsx
web/src/cypress/support/navigate-to-and-from.ts

Fixed issue with breadcrumb names (e.g., services, schedules, etc...) being transformed incorrectly by removing a redundant call to `toTitleCase` as the `useName` helper already does this.

nav: remove redundant toTitleCase call

---

notification/slack/channel.go
smoketest/slackinteraction_test.go
smoketest/statusupdateschannel_test.go

This PR updates the Slack notification sender to only include the summary in the message payload.
The `summary` field is intended to be included in messages, whereas the `details` field is Markdown and intended to be viewed in the web application. This causes misformatted messages and unnecessary noise in Slack channels.
Details will continue to be available in the included direct link, similar to SMS messages.

slack: omit details from notifications

---

engine/rotationmanager/db.go
engine/rotationmanager/update.go
graphql2/graphqlapp/rotation.go
schedule/rotation/store.go
user/store.go

This PR fixes a number of deadlock issues around rotations by introducing some rather aggressive locks.
This is necessary until we can remove the dependency on triggers that cause different locking orders resulting in deadlocks depending on what changes happen when.
Any changes to rotation participants or state (including deleting a user) now acquire locks on both `rotation_participants` and `rotation_state` first, in the same order, before being allowed to continue.
Additionally, a bug was fixed that prevented deleting a user if they were the last member of a rotation and currently active.

rotation: deadlock fixes

---

web/src/app/rotations/util.test.ts
web/src/app/rotations/util.tsx

ui/rotations: convert util.js to ts

---

web/src/app/services/HeartbeatMonitorCreateDialog.tsx
web/src/app/services/HeartbeatMonitorForm.tsx
web/src/app/util/errutil.ts
web/src/cypress/integration/services.ts

ui/services: convert HeartbeatMonitorCreateDialog to ts and use urql

---

web/src/app/selection/MaterialSelect.tsx
web/src/app/selection/QuerySelect.js
web/src/app/selection/UserSelect.js
web/src/cypress/integration/rotations.ts

This PR adds email as a subtext when selecting users to add to a rotation or escalation policy step. This allows  differentiating between users with the same display names. 
https://github.com/target/goalert/issues/2496
BEFORE:
AFTER:

ui/selection: display email as subtext on user select

---

escalation/search.go
schedule/rotation/search.go
schedule/search.go
service/search.go

This PR changes `textSearch` helper function to `prefixSearch` which allows partial text matching search capabilities for services, schedules, EPs, and rotations. 
https://github.com/target/goalert/issues/2125

use prefixSearch for services, schedules, EPs, and rotations

---

web/src/app/alerts/components/AlertDetails.tsx

This PR makes the alert detail width 100% and fixes the minor ui bug we're seeing in prod. 

ui/alerts: make alert detail width 100%

---

remotemonitor/config.go
remotemonitor/instance.go
remotemonitor/monitor.go

This PR updates the remote monitor to support verifying email integration keys.
- configuration is now validated on startup
- EmailAPIKey added to remote monitor instance config
- SMTP config has been added and is now required if EmailAPIKey is used
- TestAPIKey was renamed to GenericAPIKey
- Fixed issue with fast shutdown
Closes #2514

remotemonitor: add support for testing SMTP

---

switchover/mainloop.go
switchover/notify.go

- Fixes a regression that resulted in switchover reporting invalid config for all nodes.
- Fixes a bug where a node with invalid config on startup may cause the startup of new nodes to fail.
The first was introduced when moving from passing connection strings to using the DB connectors directly for the Listener sqlutil. Previously the code relied on parsed config from the URL which determined which DB to listen to for the ID message. The changes introduced in #2305 incorrectly passed the `old.db` instance where a message was expected from the `new` DB.
The second was a long-standing race where an invalid config, which triggers a reset, was detected before the node had fully started and `SetApp` had not yet been called.

switchover: use new db for new db listener

---

Makefile
Procfile
Procfile.prod
docs/development-setup.md

This PR updates the `make start` and `make start-prod` commands to allow setting `PUBLIC_URL` for instances where external traffic is required for development of a feature.
Part of #2554

dev: allow setting public url

---

calsub/store.go
integrationkey/store.go
permission/error.go

This PR resolves an issue where invalid integration keys would return validation errors resulting in a `400 Bad Request` instead of `401 Unauthorized`.
Closes #2541
Properly formatted but invalid/deleted integration keys will now return a 401 status code, instead of 400.

intkeys: return 401 for invalid integration keys

---

devtools/gettool/fetchfile.go
grafana/grafana.go
notification/twilio/twiml_test.go
smoketest/webhook_test.go

Updated deprecated ioutils to work with go 1.19
https://github.com/target/goalert/issues/2562
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
Fixes #2562 
NA
NA
NA
NA
NA

fix for go 1.19

---

devtools/mocktwilio/voicecall.go
notification/twilio/twiml.go
notification/twilio/twiml_test.go

This PR updates the `notification/twilio` package to use `encoding/xml` instead of raw strings to build the Response document.
This is in preparation for user-definable values in #2575

twilio: use encoding/xml to generate TwiML response

---

notification/twilio/alertsms.go
notification/twilio/sms.go
test/smoke/twiliosmsrestrictions_test.go

This PR updates the SMS logic to account for additional SMS restrictions.
- URLs not allowed to some prefixes
- Added to list of prefixes that do not support 2-way SMS

twilio: update SMS restrictions

---

devtools/ci/dockerfiles/build-env/Dockerfile
devtools/ci/dockerfiles/goalert/Dockerfile
devtools/ci/tasks/build-all.yml
devtools/ci/tasks/build-binaries.yml
devtools/ci/tasks/scripts/codecheck.sh
devtools/ci/tasks/test-smoketest.yml
docs/development-setup.md
go.mod

Updates Go to 1.19.1 and bumps the min version in `go.mod` to `1.19`

deps: update to Go 1.19.1

---

graphql2/generated.go
graphql2/graphqlapp/heartbeatmonitor.go
graphql2/graphqlapp/service.go
graphql2/models_gen.go
graphql2/schema.graphql
web/src/schema.d.ts

When creating a new service with a heartbeat monitor, CreateHeartbeatMonitorInput is requiring a serviceID that has not yet been created.
This change will make serviceID optional in the schema for CreateHeartbeatMonitorInput, allowing createService to create the heartbeat monitor when the service is created.

GraphQL: serviceID should be optional

---

web/src/app/services/HeartbeatMonitorCreateDialog.tsx

Adding `Service` to the list of types updated so urql knows to re-fetch the list of heartbeat monitors (a prop of Service) when creating a new one.
Fixes #2581

heartbeat-ui: force refetch of service info (incl. hb list) on create

---

devtools/resetdb/config.go
devtools/resetdb/datagen.go
devtools/resetdb/main.go

Adds sent notifications to the `outgoing_messages` table when running `make regendb`
Closes #2629 
Does not generate messages other than alert_notifications (no bundling, status updates, etc..)

dev: generate outgoing messages

---

docs/getting-started.md

Update recommended Postgres version in the getting started docs and add "or newer" to denote that newer versions are acceptable.

docs: update Postgres version in getting-started

---

web/src/app/escalation-policies/PolicyEditDialog.tsx

While editing the description of the escalation policy with empty value, the empty value is getting updated with the last stored value and it never gets emptied though it is an optional field. Updating to other values is working as expected.
**Solution:**
In the current version, there is a default value assigned to description of the escalation policy when its empty. Solution is to remove the default value in the Escalation Policy Edit component (UI)
Fixes #2716

fixed escalation policy update description

---

test/integration/email-cm.spec.ts
web/src/app/main/components/NewUserSetup.js
web/src/app/users/UserContactMethodCreateDialog.tsx
web/src/app/users/UserContactMethodForm.tsx
web/src/app/users/UserContactMethodList.tsx
web/src/app/users/UserDetails.tsx
web/src/app/users/UserNotificationRuleList.tsx
web/src/app/util/OtherActions.js
web/src/cypress/integration/profile.ts

Part of #2693
Makes the create buttons for the profile page more visible when the browser width is large. On mobile, the two add buttons will remain as a FAB button in the bottom right.
Also updates the secondary action IconButton to be `color='secondary'` for `OtherActions`, and cleans up passing a prop through a couple components that can be pulled from an existing hook call.
Dark mode example
Light mode example w/ notification rule add disabled when no contact methods are present

ui: move profile add buttons

---

web/src/app/services/ServiceCreateDialog.tsx

Escalation policy auto-created while creating a new Service is not added to favourites
**Solution:**
Added favorite field(set it to true) while creating new EscalationPolicy
Fixes #2724

add escalation policy created via service to favourites

---

web/src/app/schedules/ScheduleRuleCreateDialog.js

Fixed an issue with the ScheduleRuleCreateDialog where it was using the users timezone for the default start and end times rather than the schedules timezone.
Fixes #2736

ui: Fix default time not being set correctly for new schedule assignments

---

web/src/app/alerts/components/AlertsListFilter.tsx
web/src/app/lists/ControlledPaginatedList.tsx
web/src/app/main/AppRoutes.tsx
web/src/app/main/NavBar.tsx
web/src/app/util/OtherActions.js

From the [design discussion here](https://github.com/target/goalert/discussions/2489#discussioncomment-4210469):
- Reduces spacing on alerts checkbox controls between the box and the dropdown arrow
- Disables the checkbox controls if no items/no items in the list are being rendered
- Hides the alert tab filters from the dropdown menu when viewing on a wide screen browser (tabs are already present)
- Clicking the GoAlert logo in the top left will route you to the homepage ('/alerts')

ui: some small fixes

---

test/integration/email-cm.spec.ts
web/src/app/users/UserContactMethodList.tsx
web/src/app/users/UserNotificationRuleList.tsx
web/src/cypress/e2e/profile.cy.ts

Switch to `title` attribute for the icon-only `+` buttons on the profile page.
This will continue to work for screen readers, but also give information to mouse users on hover. 
Hovering over the `+` buttons on your Profile page will now display information about what the button does.

ui/profile: use title instead of aria-label for icon buttons

---

web/src/app/lists/FlatList.tsx
web/src/app/services/HeartbeatMonitorList.tsx
web/src/app/services/IntegrationKeyList.tsx
web/src/app/services/ServiceLabelList.tsx

Part of #2715
Adds create buttons when on wide browser width for:
- Heartbeat monitors
- Labels
- Integration Keys
Also adds a header note for the service labels list

ui: add desktop service create buttons

---

web/src/app/services/HeartbeatMonitorList.tsx
web/src/app/services/IntegrationKeyList.tsx
web/src/app/services/ServiceLabelList.tsx
web/src/cypress/e2e/services.cy.ts

fixes a few tests that I missed updating in #2735
I opted to use the selector `data-testid` instead of `has-text()` or `.contains()` because the latter two were failing looking for the button before the page finished loading

ui: update failing cypress tests

---

web/src/app/dialogs/FormDialog.js
web/src/app/schedules/temp-sched/TempSchedDialog.tsx

Fixes #2744
Adds the prop `disableBackdropClick` to `FormDialog` for more flexibility. Currently, this is only enabled if the form is of type `alert`.

ui: disable backdrop close for temp schedules

---

web/src/app/rotations/RotationUserDeleteDialog.tsx

Following the previously [closed PR](https://github.com/target/goalert/pull/2707) on fixing the same issue, this PR fixes the operation when mutating rotation participants. The bug initially occurs because the code is trying to update the active user index on an out of bound index since the user is removed from the rotation. 
As suggested, I added the error props in the Dialog component so that the error is properly shown if there's any when submitting the mutation. I also omitted the `activeUserIndex` from the mutation and it immediately fixes this issue.
Fixes https://github.com/target/goalert/issues/2543

Fix UI bugs on removing user from rotation

---

graphql2/generated.go
graphql2/graphqlapp/messagelog.go
graphql2/models_gen.go
graphql2/schema.graphql
notification/search.go
test/smoke/graphqladminmessagelogs_test.go
web/src/app/admin/admin-message-logs/AdminDebugMessagesLayout.tsx
web/src/app/admin/admin-message-logs/DebugMessageDetails.tsx
web/src/schema.d.ts

The admin message log will now display messages that have not yet been sent at the top of the list and then sort by the created time thereafter. 
Fixes #2650 
- The sorting of the admin message logs was affected as described in the description above.
- Added the sent at time to the message details
- Added the retry count to the message details, if greater than 0
Added `sentAt` and `retryCount` to the `DebugMessage` type.
- Updated the sql query and model to retrieve the `sent_at` and `retry_count` values from the database
- Updated the sql query to sort messages first by any messages where `sent_at` is null and then `created_at` …

admin/message-log: reflect sent time in sort order

---

app/healthcheck.go
app/inithttputil_test.go
auth/handler.go
devtools/pgdump-lite/dumpdata.go
devtools/runproc/process.go
devtools/sendit/readme_test.go
graphql2/cmtype.go
graphql2/isotimestamp.go
mailgun/mailgun.go
notification/slack/channel_test.go
notification/twilio/twiml.go
remotemonitor/monitor.go
test/smoke/mailgunalerts_test.go
util/timeutil/isoduration.go
util/timeutil/isorinterval.go

In preparation for golangci-lint checks, this PR adds error checks to all io.WriteString() commands, using the logging patterns of each function
Part of https://github.com/target/goalert/issues/2579
Not making any functional changes to the app. Logging only!

feat: Error check on io.WriteString

---

notification/slack/cache.go
notification/slack/channel.go

Small PR to switch to generics for the slack in-memory cache.
Part of #2712

notification/slack: refactor cache to use generics

---

devtools/runproc/process.go

Fixes a regression where runproc would panic based on a race of when a process/pty exits and it trying to send `^C` to the subprocess.

dev/runproc: remove panics for early-exit

---

Makefile
Procfile.integration
Procfile.integration.ci
test/integration/experimental-flags.spec.ts
test/integration/lib/flags.ts
test/integration/lib/index.ts

This PR introduces support for experimental feature flags in Playwright tests by using the `configureExpFlags` function.
This function will mark the current test block (or file) as serial-only and set a beforeAll & afterAll hook to set/unset feature flags.
The added test validates the state of flags by using GraphiQL explorer UI.
Resolves #2788

playwright: experimental feature flags support

---

Procfile.cypress
devtools/ci/dockerfiles/cypress-env/Dockerfile
devtools/ci/tasks/test-integration.yml
web/src/cypress/e2e/admin.cy.ts
web/src/cypress/e2e/pagination.cy.ts
web/src/cypress/e2e/services.cy.ts
web/src/cypress/support/e2e.ts
web/src/cypress/support/login.ts
web/src/cypress/support/util.ts
web/src/package.json
yarn.lock

upgrade Cypress to v12.4.1
includes changes to how the session cookies are stored. each test now runs with its own isolated cookie rather than one session preserved once at the top level

ui: upgrade cypress to v12.5.0

---

notification/slack/oncallnotification.go
notification/slack/oncallnotification_test.go

This PR adds a missing Sort call to sort users by name in on-call messages.
Fixes #2784

notification/slack: sort on-call users by name

---

notification/slack/cache.go
web/src/app/users/UserContactMethodCreateDialog.tsx
web/src/app/users/UserContactMethodForm.tsx
web/src/app/users/UserContactMethodList.tsx

This PR adds UI support for Slack DMs as a contact method type.
Part of #2712
This is a follow-up to #2805 
It only adds support in the UI for creating & deleting the new contact method type.
Start with `make start EXPERIMENTAL=slack-dm` to create a Slack DM contact method.

slack: add UI for Slack DM contact method type (experimental)

---

web/src/app/alerts/AlertDetailLogs.js
web/src/app/alerts/AlertsList.tsx
web/src/app/services/HeartbeatMonitorList.tsx
web/src/app/services/HeartbeatMonitorStatus.tsx
web/src/app/users/UserSessionList.tsx
web/src/app/util/Time.tsx
web/src/app/util/timeFormat.test.ts
web/src/app/util/timeFormat.ts

This PR adds a new `<Time>` component to render various timestamps and durations throughout the application.
Only a few call sites have been updated to keep the PR focused on the new component.
**Screenshots**
An example of the rendered times (this change to rotations is **_not_** in this PR)
Experience should be the same, with minor changes due to the added consistency of using a single formatting function and the browsers configured locale instead of our custom logic.
Places updated to use the new component for validating this PR:
- Alert details event log timestamps
- Alert list timestamps
- Heartbeat monitor timeout display
- Heartbeat monitor status display
- User session list

ui: add Time component

---

web/src/app/alerts/components/AlertDetails.tsx
web/src/app/services/ServiceMaintenanceDialog.tsx
web/src/app/services/ServiceMaintenanceNotice.tsx
web/src/app/util/Time.tsx
web/src/app/util/timeFormat.test.ts
web/src/app/util/timeFormat.ts

Updates services and alert details to use the new `<Time>` component.
- Svc. Maint. Dialog
- Svc. Maint. Notice
- Alert details EP summary

ui/time: use Time for services and alert details

---

docs/getting-started.md

Adds a note about potential overcommit issues in response to #2828 
I validated that the issue occurs on a fresh Debian install with Postgres & GoAlert and is resolved by following the recommendations on the linked page.

readme: add note about overcommit

---

engine/engine.go
engine/message/db.go
engine/message/ratelimit.go
graphql2/maplimit.go
graphql2/schema.graphql
limit/id.go
web/src/schema.d.ts

Currently, we have rate limiting configuration set for each notification type per contact method. This is directly set in the code and not dynamic. If there's a need to change in the rate limits it needs redeployment of code everytime
Solution:
We can make the rate limits configurable in UI under admin panel. We have config limits set for unack alerts etc..Similarly we can have it for throttling which can be modified by the admin according to their needs. We can have entries added in config_limits table with the maximum limit as value.
Fixes #2653
Need to add few rows in config_limits table and add values to config limit enum
alter type enum_limit_type add value …

Added UI Configurable rate limits for each notification type

---

web/src/app/util/ISOPickers.tsx
web/src/cypress/e2e/timepickers.cy.ts
web/src/cypress/support/form.ts
web/src/global.d.ts
web/src/package.json
yarn.lock

This PR removes the fallback code for date/time pickers.
None expected, all supported browsers have had native controls for a couple of years now.
Worst case a user will have a text field to enter time and/or date info.
We only use `time`, `date`, and `datetime-local`
https://caniuse.com/input-datetime

ui/ISOPickers: Remove fallback code

---

web/src/app/alerts/components/AlertDetails.tsx
web/src/app/links/ServiceLink.js
web/src/app/links/ServiceLink.tsx

ui/ServiceLink: convert to typescript

---

notification/slack/channel.go

This PR fixes the update issue with slack DMs.
When sending a DM, a new channel ID is generated that must be preserved to update the message. This differs from channel messages that use the original channel ID for updates.
Start with `make start EXPERIMENTAL=slack-dm` to validate dm messages and message updates.

slack-dm: fix dm message updates

---

web/src/app/alerts/AlertsList.tsx
web/src/app/main/App.tsx
web/src/app/main/SnackbarNotification.tsx

On the alerts list, if multiple updates are made, only the first snackbar notification appears then it glitches out.
This change uses context at the top level in `App.js` to always shows the latest notification, pushing new notification data to the context on mutation `onComplete`s/`onError`s.
the bug:
https://youtu.be/CEMMgKroCQg

ui: fix snackbar not showing latest alert notification

---

engine/compatmanager/db.go
notification/slack/user.go

This PR fixes 2 issues with the `slack-dm` feature
- On the profile page, we should be using `Profile.DisplayName` instead of `Name`
- Contact methods created from the compat module should have `pending` set to `FALSE` as they are considered verified through the linking process.

slack: fix DM display and pending state

---

devtools/mocktwilio/twiml/doc.go
devtools/mocktwilio/twiml/nullint.go
devtools/mocktwilio/twiml/nullint_test.go
devtools/mocktwilio/twiml/verbs.go
devtools/mocktwilio/twiml/verbs_test.go

Adds a new `twiml` package for interacting with TwiML markup. First of a few PRs to break apart #2602

mocktwilio/twiml: add initial doc.go, Say verb and NullInt types

---

devtools/mocktwilio/twiml/iterator.go
devtools/mocktwilio/twiml/iterator_test.go

Adding an `Iterator` to be used in processing TwiML verbs from a `Response` document.
Part of https://github.com/target/goalert/pull/2602

mocktwilio/twiml: Add Iterator for processing TwiML documents

---

devtools/mocktwilio/server.go
notification/twilio/client.go

Small change to move the API version to the path instead of the base URL to keep things clean if using the same domain (e.g., test servers).

twilio: move version to api path instead of base

---

ctxlock/config.go
ctxlock/idlocker.go
ctxlock/idlocker_test.go
ctxlock/lock.go
ctxlock/unlock.go

This is a replacement for the concurrency limiter code with full test coverage and _hopefully_ easier-to-validate code. This implementation has better guarantees than the original and uses simple slices instead of linked lists.
- This just adds the new package and implementation, future PRs will replace the old code.
- Benchmark/memory analysis -- this will be done in a future PR before replacing old code.

ctxlock: add IDLocker and tests

---

service/service.go
web/src/app/forms/FormField.js
web/src/app/services/ServiceForm.tsx

…ervice form
Added hint indicating markdown support for create/edit service form description text box. Also increased description size to 6KiB supporting up to 6144 chars. Added a char count to indicate this capacity.
Fixes #2803
Before:
After:
New UI elements for user facing service form. Allows larger services description, adds hints.

feat: add markdown supported hint, increased description size to 6KiB for service form

---

Procfile.cypress
Procfile.cypress.ci
Procfile.cypress.prod

Node 17+ changed the default of localhost to ipv6, with no fallback for ipv4. This means something listening on `localhost` that defaults to ipv4-only will result in nodejs breaking with connection refused.
To resolve this without the need for version detection/flags we can just update the Procfiles for Cypress to use `127.0.0.1` to force the compatible option.

dev: use ipv4-only addresses for Cypress

---

web/src/app/users/UserContactMethodList.tsx
web/src/app/util/OtherActions.js
web/src/app/util/OtherActionsDesktop.js

Make test and verification options available only to the current user to send to their contact methods.
- Hide reactivate button if userid does not match current user
- Disable "send to test" and "reactivate" dropdown options if not the current user
- Show tooltip for disabled options explaining why options are disable when hovering over those options
Fixes #2823 

feat: clarify permissions around contact methods

---

auth/github/identityprovider.go

Prevent generic `Name must not be empty` error by returning `GitHub user does not have display name set.` instead.
Fixes #2940

auth/github: prevent cryptic error on no name set

---

web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertConfirm.tsx
web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertInfo.tsx
web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertListItem.tsx
web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertReview.tsx
web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceListItem.tsx
web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceSelect.tsx
web/src/app/forms/FormField.js
web/src/app/services/ServiceFilterContainer.tsx
web/src/app/services/ServiceForm.tsx

Converts all step content components to typescript.
- CreateAlertConfirm
- CreateAlertInfo
- CreateAlertListItem
- CreateAlertReview
- CreateAlertServiceListItem
- CreateAlertServiceSelect
Part of #2318

ui/alerts: Convert alert step content to typescript

---

.github/workflows/labeler.yml

The generated file was missing from ignore config.

dev: add models_gen.go to labeler ignore list

---

app/cmdcerts.go

Updates `cmdcerts.go` to store default values in the Go variables instead of relying on flag parser side effects.
No change to the command behavior, but it makes it easier to see/process default values for human and static-analysis tools alike.

certs: move default values to Go vars

---

app/cmd.go
auth/basic/db.go
graphql2/graphqlapp/user.go

- Moves bcrypt hashing out of the `CreateTx` method of the basic store
- Uses type system to ensure only hashed passwords are accepted by `CreateTx`
Fixes #2985

auth/basic: separate password hashing from DB insert

---

test/integration/schedules.spec.ts
test/integration/timepickers.spec.ts

Does some cleanup on playwright tests to reduce flakiness
- Removed all use of `waitForTimeout`
- Use random strings for generated schedules
- Removed loops for double key presses in favor of flat calls
- Use `li` qualifier for search-select items

dev: switch to wait for page vs time

---

config/config.go
graphql2/mapconfig.go
notification/email/sender.go

- Update `SMTP.Address` description to document default port numbers and add more information
- Fix the default port for TLS mode to be `465` (instead of `587`)

Fix smtp default port

---

notification/slack/channel.go
notification/slack/usergroup.go

Fixes some stale data issues by making cache times consistent:
- Listed resources used for searching (i.e., channels & user groups) are set to 1m
- Individual resources are cached for 15m
- When listing resources, individual records are now updated

slack: lower slack cache time

---

graphql2/graphqlapp/mutation.go
graphql2/graphqlapp/slack.go
notification/slack/usergroup.go
web/src/app/selection/SlackUserGroupSelect.tsx

This PR updates the Slack user group feature to use the handle for user group display and searching rather than the name field.
Within Slack users use, and are shown, the handle and not the name, so this aims to make that consistent with what is shown in GoAlert.

slack: use usergroup handle instead of name

---

graphql2/graphqlapp/app.go

Fixes a noise regression/issue where context canceled errors were being logged. Should also cleanup test output as well.

logs: don't log context canceled errors (e.g., closed browser tab)

---

graphql2/graphqlapp/escalationpolicy.go

Adding backend check for webhooks added to existing escalation steps.
Uses the same validation logic as creating a new step.
Fixes #3039 
**Attachments**
This error will appear when editing a step to include a forbidden webhook:

fix: webhook check on edit escalation policy step

---

engine/message/db.go
graphql2/graphqlapp/user.go
test/smoke/slackdm2889_test.go
test/smoke/statusupdatescancel_test.go
user/store.go
user/user.go

This PR removes leftover code around `alert_status_log_contact_method_id`, causing problems with status updates.
A smoke test was added that reproduces the issue, fails before the fix, and passes after.
The status update cancel test was also updated to use the new API.
Fixes #2889 
The deprecated status method CM ID fields no longer do anything and always return an empty string.
Root issue: Previous to the recent status update change in #2824, changing the `alert_status_log_contact_method_id` in the user table would retroactively update any pending status update messages to the new contact method.
With the new behavior, subscriptions are now per contact method. When a user …

fix slack dm status updates

---

app/cmd.go
auth/basic/db.go
graphql2/generated.go
graphql2/graphqlapp/user.go
graphql2/models_gen.go
graphql2/schema.graphql
util/errutil/maperror.go
web/src/schema.d.ts

Created two new mutations: `createBasicAuth` and `updateBasicAuth` in order to properly handle cases where basic auth is disabled or with accounts created via OICD/GITHUB and admins wish to create/update a user's basic auth.
Additional checks for `auth/basic/db.go` methods to fail fast if basic auth is disabled.
Added backend check to ensure that OldPassword is passed for non-admins and for the currentUser.
part of #2667 prereq for #2991
Created two graphql mutation endpoints for create/update basic auth

auth/basic: add `createBasicAuth` and `updateBasicAuth` for managing Basic credentials via GraphQL

---

Makefile
notification/slack/usergrouperror.go
notification/slack/usergroupsender.go
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
web/src/app/schedules/on-call-notifications/hooks.ts
web/src/app/schedules/on-call-notifications/util.ts
web/src/app/selection/SlackUserGroupSelect.tsx
web/src/cypress/e2e/schedules.cy.ts

- The dialog for creating/editing schedule on-call notifications now features a dropdown to select channel type
- Slack channel/user groups have been separated into two channel types, selectable from the dropdown
- The checkbox was removed, as its functionality is replaced by the dropdown
- User Group notifications are no longer sent to the Slack channel unless there is an error with the User Group
- The `Value` type for `ScheduleOnCallNotificationsForm` has been altered to be more accommodating of different notification channel types
- Minor dev fix: use `YARN_VERSION` instead of assumed stable version
- Fixes `Usage Error: Invalid package manager specification in CLI arguments; expected a semver version` from recent build changes
#3045 …

feat: on call notification channel separation

---

web/src/app/users/SendTestDialog.tsx

Fixes sending test notifications. A recent change from the Luxon upgrade enforces strict parsing of DateTime strings. The test dialog had a silent error where an empty string was parsed.
This PR fixes the issue by only parsing the timestamp when available.
To reproduce/validate:
- On `master` (before this change), `Send Test` from a contact method will fail with broken page
- On this branch, the test notifications should be sent, and status printed in the dialog

ui/profile: fix test message dialog

---

genericapi/handler.go

Consider `dedup` value from request body as well
Fixes #3094

feat: consider dedup value from request body as well

---

web/src/app/rotations/RotationDetails.tsx
web/src/app/rotations/RotationUserList.tsx
web/src/cypress/e2e/materialSelect.cy.ts
web/src/cypress/e2e/rotations.cy.ts

- Moves the rotation add user button to top right of card when on lg or xl screen sizes
Part of #2693
- EP add step button
- User profile buttons
**Old:**
**New:**

ui: move button for adding user to rotation

---

web/src/app/escalation-policies/PolicyDetails.tsx
web/src/app/escalation-policies/PolicyStepsCard.js
web/src/cypress/e2e/escalationPolicySteps.cy.ts
web/src/cypress/e2e/favorites.cy.ts
web/src/cypress/e2e/materialSelect.cy.ts

- Moves the escalation policy create step button to top right of card when on lg or xl screen sizes
Part of #2693
- User profile buttons
**Old:**
**New:**

ui: move button creating a step on an EP

---

auth/cookies.go

Sets the `SameSite` parameter to strict mode when setting session cookies as they are intended to only be used from the application itself.
https://pkg.go.dev/net/http#SameSite

auth: set SameSite to strict on session cookie

---

auth/handler.go
playwright.config.ts
test/integration/oidc.spec.ts

This PR adds additional validation on the `login_redir` cookie before issuing a redirect on successful login. The added validation is identical to the validation performed before setting the cookie value initially.
There are no changes in behavior: in user flows, the validation happens before the cookie is set. However, invalid cookie values will now be rejected.
- A recent integration test (oidc) validates that authentication works as it did before.

auth: Validate redir on return from auth

---

Makefile

Fixes issues where playwright won't run after updates in CI.

playwright: run playwright install before test commands

---

auth/cookies.go
auth/github/identityprovider.go
auth/handler.go
auth/oidc/identityprovider.go

Fixes a regression that prevents login when redirecting from an OIDC server by setting `SameSite=Lax` for OAuth cookies, and retaining `SameSite=Strict` for the session cookie.
1. `SameSite=None`: Cookies will be sent in all contexts. This was how cookies worked by default prior to the SameSite attribute implementation.
2. `SameSite=Lax`: Cookies are not sent on normal cross-site subrequests (for example, to load images or frames into a third-party site), but __are sent when a user is navigating to the origin site__. This is the default value in modern browsers if the attribute is not specified.
3. `SameSite=Strict`: Cookies will only be sent in a first-party context and not be sent along with requests initiated by third-party websites. This means …

auth: use samesite=lax for oauth cookies

---

service/service.go

Extending maximum maintenance mode from 8 hours to 24 hours. We also want to allow a 5 minute grace period for clock drift.
N/A
N/A
N/A
N/A
Nothing new introduced, but this does alter the maximum amount of time a service can be added to maintenance mode
none

feat: extending maintenance allowance through API

---

test/smoke/webhook_test.go
test/smoke/webhookoncall_test.go

Added additional smoke test ensuring that webhooks can receive notifications from a schedule's on-call notification rule.

feat: add smoke test for on call notification webhooks

---

Procfile

Fixes a race condition with `make start` where the grpcui tool will exit (causing `make start` to fail) if GoAlert doesn't bind the port in time.
The fix is to use the `waitfor` tool to simply wait for GoAlert first.

dev: wait for goalert to start before grpc tool

---

alert/store.go
genericapi/handler.go
grafana/grafana.go
mailgun/mailgun.go
prometheusalertmanager/prometheusalertmanager.go
site24x7/site24x7.go
test/smoke/genericapi_test.go
web/src/app/documentation/sections/IntegrationKeys.md

This PR adds the sends the created alert as response body in create alert generic API.
Fixes https://github.com/target/goalert/issues/3123
This PR changes the response of the createAlert API  (`POST /api/v2/generic/incoming`) from 204 to 200 with the alert object as the payload.

sending alert object as create alert response body

---

web/src/app/details/DetailsPage.tsx

Escalation policy notices now align with the main grid of the details page.
Fixes #3197
Before:
After:

fix: aligning esc policy notices

---

engine/sendmessage.go
notification/alert.go
notification/store.go
notification/webhook/sender.go
test/smoke/webhook_test.go

Webhook alert bundle notifications included the service id and name which were not present in the alert type. This feat adds the service name and id field to the webhook alert notification post data. 
#3009 
```
Before:
127.0.0.1 - - [26/Jul/2023 09:21:03] "POST /webhook HTTP/1.1" 200 -
Data received from Webhook is:  {'AppName': 'GoAlert', 'Type': 'Alert', 'AlertID': 79679, 'Summary': 'test3', 'Details': ''}
After:
127.0.0.1 - - [26/Jul/2023 09:39:48] "POST /webhook HTTP/1.1" 200 -
Data received from Webhook is:  {'AppName': 'GoAlert', 'Type': 'Alert', 'AlertID': 79679, 'Summary': 'test3', 'Details': '', 'ServiceID': 'df9cfe94-7a76-4757-94b5-bf6013af831e', 'ServiceName': 'test_webhook'}
```

feat: add service name/id field to webhook alerts

---

devtools/ci/dockerfiles/goalert/Dockerfile

Fixes an issue where building with the from-scratch Dockerfile can fail due to existing artifacts.

dev: run clean before building in Dockerfile

---

Procfile

Sets the `--email-integration-domain` for `make start`
Fixes error message when running `make start`

dev: set email domain to localhost in dev

---

web/src/app/main/components/ToolbarAction.tsx

Part of converting javascript files to typescript. Converted ToolBarAction file. 
Part of [#2318](https://github.com/target/goalert/issues/2318)

ui/components: Convert toolBarAction to ts

---

docs/getting-started.md
docs/switchover.md
swo/README.md
web/src/app/admin/switchover/AdminSwitchover.tsx
web/src/app/admin/switchover/AdminSwitchoverGuide.tsx
web/src/app/main/AppRoutes.tsx
web/src/app/util/AppLink.tsx

This PR adds a guide for performing a switchover to the repo.
A link to the guide has been added to the Getting Started document (in the database section) as well as a link inside the switchover page itself to be discoverable by admins.

swo: add guide and in-app documentation

---

escalation/search.go
notification/search.go
schedule/rotation/search.go
schedule/search.go
search/render.go
service/search.go
user/search.go

- Searching list pages (users, escalation policies, rotations, schedules, notifications, and services) only shows results that match the order of the search terms.
- Words can be skipped (e.g. the search "Serv Two" will return both "Service Two" and "Service One Two")
Before:
After:
Fixes #3217 
Anything using `prefixSearch` now uses `orderedPrefixSearch`, which queries with a single regex.
Examples (`\m` matches beginning of word):
`\m{term 1}`
`\m{term 1}.*\m{term 2}`
`\m{term 1}.*\m{term 2}.*\m{term 3}`

fix: prefix search

---

web/src/app/escalation-policies/PolicyStepForm.js

Fixes an issue that prevents configuring webhooks when Slack is disabled.
The current step index for webhooks changes based on whether `Slack.Enable` is set or not, but the logic was incorrectly checking the `Webhook.Enable` flag.
Fixes #3263 
This logic should be greatly simplified with the completion of #3206

ep: fix webhook expansion when slack is disabled

---

graphql2/graphqlapp/alert.go
graphql2/graphqlapp/messagelog.go
util/timeutil/isoduration.go
util/timeutil/isoduration_test.go
util/timeutil/isorinterval.go
util/timeutil/isorinterval_test.go

This PR updates the `timeutil.ISODuration` to preserve information about weeks, hours, minutes, and seconds.
Convenience methods were added for code that previously relied on the combined field values:
- The struct now has explicit fields for each part (e.g., `.YearPart` and `.WeekPart`)
- A `.TimePart()` method was added to convert hours/minutes/seconds into a `time.Duration`
- A `.SetTimePart(time.Duration)` method was added to do the reverse
- A `.Days()` method was added to give `.WeekPart` and `.DayPart` together
This allows the backend to use this type information and is necessary work for #3243

timeutil: preserve field/type information when parsing ISODuration

---

graphql2/generated.go
graphql2/gqlgen.yml
graphql2/graphqlapp/query.go
graphql2/graphqlapp/user.go
graphql2/models_gen.go
graphql2/schema.go
graphql2/schema.graphql
web/src/schema.d.ts

This PR adds a new `listGQLFields` query that can return all fields used by a valid query OR all valid fields for the schema (if a query is omitted).
It also serves as a way to validate a query against the current schema.
Additionally, `UserSession` was changed to use a gqlgen-generated model to eliminate a circular dependency on the `auth` package.
Part of #3007 
- Added a query `listGQLFields`

graphql: add `listGQLFields` query

---

web/src/app/util/timeFormat.test.ts

Fixes an issue where different versions of node break time format tests.
https://github.com/nodejs/node/issues/46123

jest: normalize whitespace before comparing timestamps

---

.github/workflows/golangci-lint.yml

Increasing the linter timeout from 2 -> 5 min as it's been timing out half the time on new PRs.
Locally it completes in a few seconds, so likely due to heavy contention/cpu-throttle on the GH actions workers.

dev: increase linter timeout

---

apikey/queries.sql
apikey/store.go
gadb/queries.sql.go
graphql2/generated.go
graphql2/graphqlapp/gqlapikeys.go
graphql2/models_gen.go
graphql2/schema.graphql
web/src/schema.d.ts

This PR adds the ability to list and update GQL API keys.
Part of #3007 
- query `gqlAPIKeys` to list all GQL API keys, including usage information
- mutation `updateGQLAPIKey` to update the name and/or description of a GQL API key
**Additional Information**
Start with `make start EXPERIMENTAL=gql-api-keys` to enable the API key flag

apikey: add list and update of graphql api keys

---

apikey/lastusedcache.go
apikey/polcache.go
apikey/store.go

This PR adds a cache for API key policy info and last-usage updates.
This ensures that last-used info isn't updated more than once per minute (per instance). The policy cache ensures that repeated use of the same key doesn't require fetching and parsing the policy JSON for each request.
Additionally, invalid keys (that otherwise have a valid signature) are put in a negative cache. This means when a key is deleted, only the first request will require a DB lookup and subsequent requests from the same key will be rejected immediately.
Part of #3007

apikey: cache policy info lookup & last usage updates

---

apikey/store.go
graphql2/generated.go
graphql2/graphqlapp/gqlapikeys.go
graphql2/models_gen.go
graphql2/schema.graphql
web/src/schema.d.ts

This PR adds a `role` field to `GQLAPIKey` indicating the permissions of the key.
```graphql
type GQLAPIKey {
// ...
role: UserRole!
}
```
Part of #3007

apikey: add role to gql api key info

---

app/initsmtpsrv.go
smtpsrv/config.go
smtpsrv/server.go

Ensures built-in SMTP server for generating alerts uses GoAlert's structured logger instead of stdout from go-smtp's Server type.  Filters out excessive logging of ECONNRESET errors that result from common TCP probe healthchecks from load balancers--see https://github.com/emersion/go-smtp/issues/236
Fixes #3335 
N/A
N/A
N/A
N/A
Once `emersion/go-smtp` handles zero-byte connections without logging an error, the conditional filter added here can be removed.

Smtp logger

---

service/search.go

Currently the `services()` query returns `null` for `maintenance_expires_at` for all services, this pr updates the search query to include it in the return.

services: update query to return maintenance_expires_at

---

devtools/mocktwilio/lookup.go
go.mod
go.sum
graphql2/graphqlapp/toolbox.go
notification/twilio/sms.go
notification/twilio/voice.go
test/smoke/harness/datagen.go
validation/validate/phone.go

This PR replaces our phone number library with one that has up-to-date metadata.
The old library's last update/release was in March 2021.
The new library's last update/release was in August 2023.
Both are Go ports of Google's libphonenumber library and have identical APIs.
Fixes #3340 
- Replaces [github.com/ttacon/libphonenumber](https://github.com/ttacon/libphonenumber) with [github.com/nyaruka/phonenumbers](https://github.com/nyaruka/phonenumbers)

validate/phone: switch to up-to-date phone number library

---

calsub/http.go
calsub/queries.sql
calsub/renderdata.go
calsub/renderical.go
calsub/subscriptionconfig.go
gadb/queries.sql.go
graphql2/generated.go
graphql2/graphqlapp/calendarsubscription.go
graphql2/models_gen.go
graphql2/schema.graphql
web/src/app/schedules/calendar-subscribe/CalendarSubscribeCreateDialog.js
web/src/app/schedules/calendar-subscribe/CalendarSubscribeEditDialog.js
web/src/app/schedules/calendar-subscribe/CalendarSubscribeForm.js
web/src/schema.d.ts

This PR introduces full schedule configuration support to GoAlert. With this change, users can now generate a calendar subscription that includes all team members' shifts for a specified schedule. This enhances visibility and allows easier management of on-call schedules in external calendar applications like Google Calendar.
Existing subscriptions can be changed to enable or disable this feature.
Fixes #3061
No items are considered out of scope for this PR.
A new `fullSchedule` field has been added to the calendar subscription options. When enabled, the calendar event label changes from "On-Call \<App Name\>: \<Schedule Name\>" to "\<User Name\> On-Call …

Feature: Full Schedule Support in Calendar Subscriptions

---

package.json
web/src/app/util/Markdown.js
yarn.lock

This PR adds a plugin to preserve line breaks in markdown in the application.
Closes #3338
Rendered markdown (alert details, docs, descriptions) will now preserve line breaks without the need for trailing whitespace and/or blank lines.

ui/markdown: preserve line breaks in markdown

---

gadb/queries.sql.go
override/queries.sql

Fixes an issue where searching with an end_time parameter caused no results to return.
The `search_start` parameter was being used instead of `search_end` due to a typo.

overrides: fix wrong param in search

---

web/src/app/services/AlertMetrics/AlertCountGraph.tsx
web/src/app/services/AlertMetrics/AlertMetrics.tsx
web/src/app/services/AlertMetrics/AlertMetricsFilter.tsx
web/src/app/services/AlertMetrics/useAlertMetrics.ts

This PR updates the UX of the alert metrics graph data, allowing the current week or month to render when "week" or "month" is the selected interval. Also updates the tooltip to show the range of time, rather than only the start date. 
Fixes #3252
Old:
New:

show alerts to now in graph, update tooltip label

---

devtools/resetdb/datagen.go

Increases the values for `DelayMinutes` from 60 to 600. When setting the `SIZE=` parameter, we run out of potential values which results in a panic.
To test: `make regendb SIZE=10` -- this will regenerate the local test DB at 10x the normal size.

devtools/resetdb: increase variance in DelayMinutes

---

dataloader/loader.go

Fix for missing function `dataloader.NewStoreLoaderIntWithDB` in `/Users/Z00BRNC/Projects/goalert/graphql2/graphqlapp/dataloaders.go`

fix for missing function

---

web/src/app/schedules/ScheduleOverrideList.js
web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx

Closes #3377
Fixes an issue where the default value was not set on the temporary schedule dialog, so the incoming data was not what was expected.
Also resolves a console error where `userID` is not a valid prop for a native HTML element.
**Out of scope:**
There's another console error related to `findDOMNode` being disabled with `React.StrictMode` enabled. This seems to be an issue with the transition library we are using, as this prop is not seen within our codebase. It will be worth looking into updating this package.

ui: fix default value not set for temp sched dialog

---

web/src/app/admin/admin-api-keys/AdminAPIKeyForm.tsx

Adds the ability to configure Allowed Fields by entering an example query.
Behind the experimental flag `gql-api-keys`. Run GoAlert with the command: `make start EXPERIMENTAL=gql-api-keys`
Part of #3007
When creating an API key, the multi-select field can be swapped to input an example query directly.

apikey: Allow entering a query directly to generate Allowed Fields

---

web/src/app/admin/AdminAPIKeys.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyCreateDialog.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyDrawer.tsx

This PR introduces a convenient "Duplicate" option for API keys within the GoAlert application. Users can now effortlessly create a new API key based on an existing one, streamlining key management and improving user efficiency. This feature applies to both active and expired keys, ensuring a continuous workflow. With user experience in mind, the duplication process is designed to be intuitive and seamless, mirroring the expiration characteristics of the source key relative to the current time.
This is part of #3007 
Visual updates for expired keys and special sorting considerations for nearly expired keys are out of scope for this PR.
Users will notice a …

Implement Duplicate Functionality for API Keys

---

web/src/app/admin/AdminAPIKeys.tsx

- Adds a warning icon with a tooltip message on hover indicating when an API key has expired.
- Updates grammar of `Expires at: m/d/y` to `Expires m/d/y`. `Expires on m/d/y` is also an acceptable solution
- Updates grammar when 1 field is allowed

ui/api-keys: add warning icon, update grammar

---

test/integration/gqlapikeys.spec.ts
test/integration/lib/flags.ts
test/integration/setup/scan-flags.ts
web/src/app/admin/AdminAPIKeys.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyForm.tsx
web/src/app/main/components/ToolbarPageTitle.tsx

This adds an integration test for GQL API keys that verifies that creating, duplicating, and deleting keys works, and checks that the keys work as tokens, with access being revoked upon deletion.
Also:
- Fixed toolbar title (`Api Keys` -> `API Keys`)
- Creating the first API key will now update the list immediately

apikey: Add integration test for GQL API keys

---

apikey/middleware.go
apikey/policy.go
apikey/store.go
graphql2/generated.go
graphql2/graphqlapp/app.go
graphql2/graphqlapp/gqlapikeys.go
graphql2/models_gen.go
graphql2/schema.graphql
test/integration/gqlapikeys.spec.ts
web/src/app/admin/AdminAPIKeys.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyCreateDialog.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyDrawer.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyEditDialog.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyForm.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyShowQueryDialog.tsx
web/src/schema.d.ts

Updates the security model of the GQL API Key feature from a list of allowed fields, to a single static query document per key.
This allows additional flexibility to restrict an API key by resource and input parameters, while also working well with GraphQL features like `operationName` (a single query doc can be used for multiple operations).
Part of #3007 
- automatic persisted queries are compatible, but not implemented by this PR

apikey: Switch policy from `allowedFields` to `query`

---

web/src/app/admin/AdminAPIKeys.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyDrawer.tsx

- Fixes a bug in the API key display where 'Last Used' mistakenly displayed the expiration time.
- Show UA and IP of last used in details drawer
- Use relative time format for dates on keys
If applicable, add some screenshots here.

apikey: Fix timestamp displays

---

web/src/app/admin/admin-service-metrics/AdminServiceFilter.tsx
web/src/app/admin/admin-service-metrics/AdminServiceMetrics.tsx
web/src/app/admin/admin-service-metrics/useServiceMetrics.ts
web/src/app/selection/MaterialSelect.tsx
web/src/app/selection/QuerySelect.js

This PR adds filtering for service metrics data table by:
- Escalation policy targets
- Integration key targets
- Label keys and values
Part of #3057
Additional metrics around integration key and escalation policy targets.
**Screenshots**
Filter side drawer:

ui/service-metrics: Add filtering for admin service metrics

---

user/search.go

Adds the ability to specify `email=` when searching for a user for an exact email match.
This is an API-only update.
Part of #3402 
- Does not add support to the filter popover (no UI changes)
N/A
If the `search` param of the `users()` query begins with `email=` it will do an exact-match search of the user email.

users: allow email= in user search

---

gadb/queries.sql.go
graphql2/graphqlapp/service.go
label/queries.sql
label/store.go
sqlc.yaml

Converts store methods of `label.Store` to use `sqlc`
- Prereq for work on #3403
- Part of #3235 
- Search endpoints using rendered SQL are unchanged
N/A
N/A

label: convert non-search store methods to sqlc

---

web/src/app/admin/AdminConfig.tsx
web/src/app/admin/AdminDialog.tsx
web/src/app/admin/AdminLimits.tsx
web/src/app/admin/AdminNumberLookup.tsx
web/src/app/admin/AdminSMSSend.tsx
web/src/app/admin/SlackActions.tsx

Updates `AdminConfig`, `AdminLimits`, `AdminNumberLookup`, `AdminSMSSend`, and `SlackActions` to use `urql` instead of `@apollo/client` for their queries and mutations
Part of #3240

ui/urql: update admin queries and mutations

---

web/src/app/users/UserContactMethodList.tsx
web/src/app/users/UserDetails.tsx
web/src/app/users/UserNotificationRuleList.tsx
yarn.lock

- Converts queries in `UserContactMethodList` and `UserNotificationRuleList` from `@apollo/client` to `urql`
- Uses a suspense context for the queries in `UserDetails`, `UserContactMethodList`, and `UserNotificationRuleList`
- Part of #3240
- Separating out work from #3229
- User details should load all at once after a centered spinner
- `yarn.lock` got updated when I ran `make start`

ui/urql: transition to urql and use suspense to load user details

---

web/src/app/forms/FormContainer.js

Converts `web/src/app/forms/FormContainer.js` component to use hooks.
Fixes: #3044
Convert to typescript

ui: convert FormContainer to hooks

---

docs/adrs/000005-api-key-architecture.md

Add ADR document outlining the API key architecture

adr: api key architecture

---

package.json
prettier.config.js
yarn.lock

Get auto formatting working again in vscode. Fixes an issue some people were seeing where prettier would only work via the command line.

dev: fix prettier formatting in vscode

---

web/src/app/admin/admin-api-keys/AdminAPIKeyDrawer.tsx
web/src/app/admin/admin-api-keys/AdminAPIKeyShowQueryDialog.tsx
web/src/app/util/CopyText.tsx

This PR improves the UX of the Show Query dialog when viewing API keys.
- Fixed formatting of the query text
- Adds the ability to copy as JSON so it can be pasted directly into code or a debugging tool
**Additional changes:**
- Updates `<CopyText />` to use `Typography` instead of a `span`. This resolves issues we have intermittently seen such as `Cannot have <p> be a child of <span>`

apikey: allow copy as JSON and fix query formatting

---

web/src/app/escalation-policies/PolicyCreateDialog.tsx

Fixes a bug where creating a new escalation policy wasn't redirecting to the new policy's details page on creation.
Fixes: #3460

ui/escalation-policies: redirect to details page on create

---

web/src/app/admin/admin-service-metrics/AdminServiceMetrics.tsx
web/src/app/admin/admin-service-metrics/AdminServiceTable.tsx

The warning icon for services without integrations was being applied incorrectly in the data table. It should only be applied to services that have no integration keys and no heartbeat monitors.

ui/service-metrics: fix service status in data table

---

web/src/app/schedules/ScheduleDetails.tsx
web/src/app/schedules/temp-sched/TempSchedDialog.tsx

Currently creating a temporary schedule will erase all other temporary schedules on a schedule and overwrite instead of merging. This removes the clearStart and clearEnd inputs to allow for more than one temporary schedules on a schedule and also for merging.

ui/temp-sched: Fix schedule not merging bug

---

package.json
web/src/app/forms/FormContainer.js
web/src/app/forms/FormField.js
web/src/app/forms/context.js
web/src/app/schedules/ScheduleOverrideForm.tsx
web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/util/ISOPickers.tsx
yarn.lock

This PR adds soft min and max limits to the ISO Pickers to allow validation errors while keeping the "always valid" intervals.
- Fixes #3456
- Fixes #3426
- Removing `ensureInterval` #3457
- Fixes an issue where keyboard input on fields was buggy
- Start and End times no longer change each other
N/A
- FormContainer now exposes `setValidationError` as a way to set validation errors up-front without waiting for submit
- FormField has `softMin` and `softMax` props added (and `softMinLabel` + `softMaxLabel`)
- ScheduleOverrideForm has `softMax` and `softMin` set on `start` and `end` times, …

ui/isopicker: Add soft limits for min and max, apply to override and temp sched.

---

apikey/middleware.go

Allow omitting the query from API requests coming from gql API keys.
- The keys already have a hash embedded to validate they only work with a single query
- When rotating or replacing a key with a modified query (presumably with the same operation names and variables) this allows easier maintenance of client applications as they can update the key, without having to keep the query in sync.

apikey: allow omitting fixed queries

---

web/src/app/admin/admin-alert-counts/AlertCountLineGraph.tsx
web/src/app/admin/admin-alert-counts/useAdminAlertCounts.ts
web/src/cypress/e2e/admin.cy.ts

Uses ISO timestamps for storing/parsing timestamps and `toLocaleString` for display. Additionally, the time buckets are now truncated (e.g., to the hour when breaking down by hour)
Previously, the graph would break if the user's locale differed from the hard-coded format. Additionally, the displayed times wouldn't match the user's locale if it differed from the hard-coded format.
This change should ensure the logic works regardless of locale, and times on the X-axis will be rendered according to the user's locale.

admin/alert-counts: use iso for storage, locale for display

---

web/src/app/admin/admin-message-logs/util.ts

Reduces the limit from 1000 intervals on the graph to a max of 75. This still allows for weekly intervals for a full year (52) and all the minutes in an hour (60), but not by day for a full year (365), which is non-performant especially when segmentation is introduced in #3296, where more data is being loaded for each interval duration.

ui/message-logs: use a sane limit for the max num of graph points

---

web/src/app/schedules/ScheduleOverrideForm.tsx
web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/util/ISOPickers.tsx

Adds soft limits of 3 months for the TempSchedDialog start & end times to prevent it from crashing while rendering thousands of years worth of shifts (e.g., when typing the year)

temp sched dialog: fix soft limits while typing

---

web/src/app/rotations/RotationAddUserDialog.tsx
web/src/app/rotations/RotationCreateDialog.tsx
web/src/app/rotations/RotationForm.tsx
web/src/app/rotations/RotationFormHandoffTimes.tsx
web/src/app/util/errutil.ts

Migrates from `@apollo/client` to `urql` for the following files:
- `web/src/app/rotations/RotationAddUserDialog.tsx`
- `web/src/app/rotations/RotationCreateDialog.tsx`
- `web/src/app/rotations/RotationForm.tsx`
Also puts the handoff times grid item in its own component so it can suspensefully load (the entire page spins in the background without it)
`RotationsUserList` is out of scope as it has caching updates, so I would prefer this be worked on & opened as a PR by itself.

ui/urql: rotations

---

apikey/middleware.go
test/integration/gqlapikeys.spec.ts

Implemented the wrong interface and as a result, omitting the `query` field would result in a validation error.
The playwright test was updated to validate that omitting `query` in the request payload works correctly.

apikey: Fix issue where omitting the `query` field doesn't work

---

web/src/app/users/UserCalendarSubscriptionList.tsx
web/src/app/users/UserList.tsx
web/src/app/users/UserOnCallAssignmentList.tsx
web/src/app/users/UserSessionList.tsx

Migrates from @apollo/client to urql for the following files:
- web/src/app/users/UserCalendarSubscriptionList.tsx
- web/src/app/users/UserList.tsx
- web/src/app/users/UserOnCallAssignmentList.tsx
- web/src/app/users/UserSessionList.tsx

ui/urql: convert user lists to urql

---

graphql2/graphqlapp/app.go
test/smoke/graphqlerror_test.go
test/smoke/harness/graphql.go

Handles the case of invalid JSON in a request body to the `/api/graphql` endpoint.
- A 400 instead of 500 is returned
- The parse error is now returned (with body stripped)
- The common case of sending a non-object has a more clear error message (default would have been cant parse string into Go-type something something)
Fixes #3498 
N/A
Invalid JSON will now result in a 400 bad request rather than 500 unexpected error
Added a smoke test to validate the new behavior.

graphql: Fix 500 errors on invalid JSON

---

web/src/app/users/UserContactMethodVerificationForm.js
web/src/app/users/UserContactMethodVerificationForm.tsx

Converts `UserContactMethodVerificationForm` to use urql and typescript.
Part of https://github.com/target/goalert/issues/2318 and https://github.com/target/goalert/issues/3240

ui/profile: convert UserContactMethodVerificationForm to typescript

---

escalation/search.go
notification/search.go
schedule/rotation/search.go
schedule/search.go
search/render.go
service/search.go
user/search.go

This PR fixes a bug where names containing underscores and hyphens could not be matched. Additionally, name matching will also include substring match in addition to prefix matches.

search: fix handling of underscores and add contains match for names

---

package.json
yarn.lock

Updates `react-big-calendar` to the latest version which fixes an issue in master where clicking "Next" or "Back" would break the page.

ui: update calendar version - fixing invalid ref with invalid scrollHeight

---

Makefile

Adds missing dependencies for changes introduced in #3533 
This ensures files get regenerated automatically when changing the additional schema files.

dev: add missing deps to makefile targets

---

package.json
web/src/app/util/CopyText.tsx
web/src/app/util/Markdown.js
web/src/app/util/Markdown.timestampSupport.tsx
yarn.lock

This PR adds support for timestamps in the markdown renderer.
It adds support for ISO-formatted timestamps, with or without sub-second precision, as well as  UNIX date-formatted timestamps (like those used for heartbeat timeouts).
- `2006-01-02T15:04:05.999999999Z`
- `2006-01-02T15:04:05.99999999907:00`
- `2006-01-02T15:04:05Z`
- `Mon Jan  2 15:04:05 MST 2006`
Timestamps will be underlined and always converted to the users local timezone and can be clicked to copy the ISO-formatted string for use in filters, SQL queries, other systems, etc..
Closes #2834 
Timestamps in any markdown document, including alert details, will be automatically detected and converted to local …

ui: Markdown timestamp support

---

.storybook/main.ts
Makefile

Updating the Makefile to pipe storybook build stderr to `/dev/null`. Fixes the flood of logs when running `test-components`

dev: pipe storybook warnings to null

---

web/src/app/users/UserCreateDialog.tsx
web/src/app/users/UserDeleteDialog.tsx
web/src/app/users/UserEditDialog.tsx
web/src/app/users/UserNotificationRuleCreateDialog.tsx
web/src/app/users/UserNotificationRuleDeleteDialog.tsx
web/src/app/users/UserNotificationRuleList.tsx

Migrates from @apollo/client to urql for the following files:
- web/src/app/users/UserCreateDialog.tsx
- web/src/app/users/UserDeleteDialog.tsx
- web/src/app/users/UserEditDialog.tsx
- web/src/app/users/UserNotificationRuleCreateDialog.tsx
- web/src/app/users/UserNotificationRuleDeleteDialog.tsx

ui/urql: convert user dialogs to urql

---

web/src/app/selection/EscalationPolicySelect.tsx
web/src/app/selection/IntegrationKeySelect.tsx
web/src/app/selection/LabelKeySelect.tsx
web/src/app/selection/LabelValueSelect.tsx
web/src/app/selection/RotationSelect.js
web/src/app/selection/ScheduleSelect.js
web/src/app/selection/ServiceSelect.js
web/src/app/selection/SlackChannelSelect.js
web/src/app/selection/TimeZoneSelect.js
web/src/app/selection/UserSelect.js

Part of #3240
Updates the imports for all Select components to use `urql` instead of `@apollo/client`.

ui: update Select gql imports to use urql

---

web/src/app/services/ServiceCreateDialog.tsx
web/src/app/services/ServiceLabelCreateDialog.tsx

Part of #3240
Updates `ServiceCreateDialog` and `ServiceLabelCreateDialog` to use `urql` instead of `@apollo/client`

ui: update ServiceCreateDialog and ServiceLabelCreateDialog to use urql

---

web/src/app/util/DestinationChip.stories.tsx
web/src/app/util/DestinationChip.tsx
web/src/app/util/DestinationInputChip.stories.tsx
web/src/app/util/DestinationInputChip.tsx

This pull request introduces the DestinationChip and DestinationInputChip components, an addition that is essential for facilitating the development of generic destinations with pluggable providers. These components play a role in processing props such as icons, text, and cancel functions, and rendering them on the screen.
Part of https://github.com/target/goalert/issues/2639
Icon Variations:
Run `make storybook` to interact with new components.
These components will be unused in main application functions, until we have wired them in with future component updates, e.g. PolicyStepDialog components.

util: add DestinationChip and DestinationInputChip components

---

web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.tsx
web/src/app/schedules/on-call-notifications/hooks.ts
web/src/app/schedules/on-call-notifications/util.ts
web/src/cypress/e2e/alerts.cy.ts

- Updates `schedules/on-call-notifications/hooks.ts` to use `urql` instead of `@apollo/client`
- Adds support for `urql`'s `CombinedError` to `schedules/on-call-notifications/util.ts`
- Apollo's `ApolloError` will be left in until `urql` has fully replaced`@apollo/client`

ui: update schedule oncall hooks and util to use urql

---

graphql2/generated.go
graphql2/graph/destinations.graphqls
graphql2/graphqlapp/destinationtypes.go
graphql2/models_gen.go
web/src/app/selection/DestinationSearchSelect.stories.tsx
web/src/app/selection/DestinationSearchSelect.tsx
web/src/app/selection/MaterialSelect.tsx
web/src/schema.d.ts

This PR introduces the DestinationSearchSelect component which will be used as a generic component for search-selectable destinations (e.g., a slack channel)
Part of https://github.com/target/goalert/issues/2639
- The `DestinationField` meta-component will be in a separate PR.
N/A
N/A
Run `make storybook` to see the new component.

ui: DestinationSearchSelect component

---

config/config.go
engine/cleanupmanager/db.go
engine/cleanupmanager/update.go
graphql2/mapconfig.go
web/src/schema.d.ts

This PR adds an opt-in config entry to extend the auto-close unacked alerts option to acknowledged alerts as well.
Closes #3397
- New boolean option to allow auto-closing active alerts.

config: Add option to auto-close acked alerts

---

test/integration/schedules.spec.ts
web/src/app/schedules/ScheduleCreateDialog.tsx
web/src/app/schedules/ScheduleDeleteDialog.tsx
web/src/app/schedules/ScheduleDetails.tsx
web/src/app/schedules/ScheduleOverrideCreateDialog.tsx
web/src/app/schedules/ScheduleOverrideDialog.js
web/src/app/schedules/ScheduleOverrideList.js
web/src/app/schedules/ScheduleShiftList.tsx

Description:
Updates `ScheduleCreateDialog`, `ScheduleDeleteDialog`, `ScheduleOverrideCreateDialog`, `ScheduleOverrideDialog`, and `ScheduleOverrideList` to use `urql` instead of `@apollo/client` for their queries and mutations
Which issue(s) this PR fixes:
Part of #3240

ui/urql: update schedule queries and mutations

---

app/cmd.go

This PR adds a check for the scheme (http/https) in the public-url option on startup. If started with just a domain, for example, the app would previously start but return 404 errors.

cli: check for scheme on public-url

---

app/cmd.go

This PR makes a small update to normalize the public URL path, if specified, by removing any trailing `/` which would cause problems.

cli: normalize public url

---

.gitignore
Makefile
Makefile.binaries.mk
Procfile.integration
Procfile.prod
devtools/genmake/template.mk
web/handler.go
web/src/esbuild.config.js

This PR adds validation of the UI assets when running without the `--ui-dir` flag. A number of bugs/issues with development targets were also fixed.
- All files under `web/src` (other than `build/` and `cypress/`) will now trigger `app.js` to be rebuilt
- Fixed dependency issues where yarn commands would never result in a stable state (always rebuild)
- removed esbuild watcher from Procfiles that already use `BUNDLE=1` (they would clobber each other)
- `app.js` must now exist and the embedded `GOALERT_VERSION` **MUST** match the backend version (if `--ui-dir` is unset)
- esbuild will now abort immediately if `GOALERT_VERSION` is undefined
- Changing the `GIT_VERSION` (e.g., by making a commit) will now trigger a rebuild to keep version strings in sync
Additionally, `make …

dev/admin: prod build validation

---

Makefile

Fixes the `cy-*` targets, a regression introduced in #3629 causes them to fail due to `GOALERT_VERSION` being left blank.

dev: add GOALERT_VERSION to cy commands

---

.yarnrc.yml
Makefile
devtools/ci/dockerfiles/build-env/Dockerfile
devtools/ci/tasks/scripts/codecheck.sh
package.json
yarn.lock

Upgrade node to version 20.11.0 in ci.

ci: upgrade node version

---

graphql2/generated.go
graphql2/graph/escalationpolicy.graphqls
graphql2/graphqlapp/compat.go
graphql2/graphqlapp/escalationpolicy.go
web/src/app/escalation-policies/PolicyStepsCard.jsx
web/src/app/escalation-policies/PolicyStepsQuery.tsx
web/src/app/escalation-policies/stepUtil.tsx
web/src/app/util/DestinationAvatar.tsx
web/src/schema.d.ts

This PR updates the policy step rendering to use `DestinationChip` when the `dest-types` experimental flag is set.
- PolicyStepQuery will now pick which query to use based on the flag
- PolicyStepCard will use the appropriate render function based on the provided data (`actions` or `targets`)
- Fixed a regression in avatar rendering that made the chip icons too big (needed to pass `...rest` props)
Part of #2639 
- Dialogs will be handled separately
N/A
- Adds a new `actions` field on `EscalationPolicyStep` listing Destinations for the step
Use `make start` and `make start EXPERIMENTAL=dest-types` to compare the …

ep: destinations: update step list/actions to use dest-types

---

.github/workflows/labeler.yml

Experiment to enable the `fail_if_xl` flag on the PR labeler (rejects PRs >500 lines)
- Updated to a version of the labeler that will ignore deleted files from line count calculation.

github: labeler: enable fail_if_xl flag

---

graphql2/graphqlapp/app.go
graphql2/graphqlapp/contactmethod.go
graphql2/graphqlapp/destinationvalidation.go
notification/slack/channel.go
notification/slack/user.go
notification/slack/usergroup.go
web/src/app/users/UserContactMethodFormDest.tsx

This PR adds a normalized output to destination validation errors (currently only called from contact method input `dest` field).
- `extensions.code` will be one of: `INVALID_DESTINATION_TYPE` or `INVALID_DESTINATION_FIELD_VALUE`
- The `.path` property of errors will reflect the actual input field (and fieldID) that failed validation
Since no code currently uses this, tests will be added with the user contact method dialog PR(s).
N/A
- Destination validation errors are now well-defined.
Existing field errors are unaffected.

dest: return proper data in graphql errors

---

.storybook/preview.ts
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.stories.tsx
web/src/app/selection/DestinationField.stories.tsx
web/src/app/selection/DestinationInputDirect.stories.tsx
web/src/app/selection/DestinationSearchSelect.stories.tsx
web/src/app/storybook/graphql.ts
web/src/app/users/UserContactMethodFormDest.stories.tsx
web/src/app/util/DestinationChip.stories.tsx
web/src/app/util/DestinationInputChip.stories.tsx
web/src/app/util/TelTextField.stories.tsx
web/src/app/util/useExpFlag.ts

Adds a helper and default to handle the `useExpFlags` query.
Fixes the 404 for the `useExpFlags` hook used by components

storybook: add exp flags helper

---

web/src/app/util/safeURL.test.ts
web/src/app/util/safeURL.ts

User indicated that hyperlinks which should be rendered correctly via markdown were displayed as text. The issues seems to be that the `<ReactMarkdown>` component checks for safeUrls with url and label where url is rendered with html entities causing special characters such as `&` to be converted to `&amp;`. This messes with the accuracy of safeUrls regex checks resulting in false negatives thus causing ReactMarkdown to display the hyperlinks as plain text. 
Adding preprocessing in the form of `encodeHtmlEntities()` ensures that the label/url comparisons are free of discrepancies caused by html entity conversions. 
[For significant amounts of work, it is best to start an issue first, preferably before the work is started.
For large pull …

fix: alert detail markdown link bug

---

Procfile
Procfile.prod
app/cmd.go
app/pprof.go
web/src/app/localdev/LocalDev.tsx

This PR adds a `listen-pprof` flag to enable profiling running instances of GoAlert (off by default)
Closes #3642 
- A `default.pgo` can be added to `cmd/goalert/` to enable automatic optimizations, but is not in scope for this PR since the initial profile should come from real production workloads.
- https://go.dev/blog/pprof
- https://go.dev/doc/pgo

Pprof endpoint

---

graphql2/graph/destinations.graphqls
graphql2/graph/errorcodes.graphqls
graphql2/models_gen.go

This PR replaces comments (that were intended for documentation) to description strings which will appear in introspection (i.e., tools like GraphiQL and the built-in explorer)
- Also ran relevant files through prettier for formatting.
- No API changes were introduced.
- Only updates and additions made as part of the destination/plugin work were changed.

dest/graphql: convert comments to description strings

---

graphql2/graphqlapp/destinationtypes.go

2 incompatible PRs were merged at the same time resulting in a broken state.
- #3703 updated some schema fields (valid on its own)
- #3700 added new fields (valid on its own)
The schema normalization one didn't have the new fields, and the new fields PR didn't have the new normalized names. They both passed, but when both were merged, the new fields didn't match the new names.
This PR fixes the issue.

dev: fix PR merge conflict

---

graphql2/graph/_Mutation.graphqls
graphql2/graph/_Query.graphqls
graphql2/graph/escalationpolicy.graphqls
graphql2/schema.graphql
package.json

Updates package.json to include `.graphql` and `.graphqls` files in prettier formatting.
Note: if vscode isn't already auto-formatting:
- ensure you have the `GraphQL` extension installed
- check for an error {} icon on the bottom bar (where you can select vscode-prettier as the formatted if it complains you have multiple)

dev: format graphql files with prettier

---

web/src/app/util/Markdown.stories.tsx
web/src/app/util/safeURL.test.ts
web/src/app/util/safeURL.ts

Fixes an issue where URLs with characters like `|` aren't handled properly.
This PR ensures intended behavior where the printed/displayed link will show `|` and the `href` attribute will contain the properly escaped URL.

util/Markdown: fix handling of links with URL-escapable characters

---

web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsFormDest.tsx

Updates the `*Dest` variant of the schedule notification form to preserve state of the time and weekday filter options.
The old non-dest form was not updated; this is ONLY when the `dest-types` flag is set to use the new form and dialog code.
https://github.com/target/goalert/assets/595010/0be58b4c-22ea-483b-b1a9-00d05b5a81f8
N/A just a quality-of-life fix
N/A
Note: The parent `props.value` and `onChange` handlers still receive a `null` time when the value changes (no effect on API). This fix is handled purely in the form's state.

sched/notif: retain time and weekday filter if swapping radio options

---

README.md
devtools/ci/dockerfiles/demo/start.sh

Makes a couple small updates to the demo container for integration test use-cases:
- Added a non-admin login
- Added the ability to skip the DB seed step when not necessary
To validate with docker:
```bash
make bin/goalert-linux-amd64.tgz bin/linux-amd64/resetdb
docker build -t gademo -f devtools/ci/dockerfiles/demo/Dockerfile.prebuilt --build-arg ARCH=amd64 .
docker run -it --rm -p 8081:8081 gademo
docker run -it --rm -p 8081:8081 -e SKIP_SEED=1 gademo
```
Both should allow login of admin/admin123 and user/user1234, with the latter skipping the random data generation (no services, rotations, etc...)

dev: update demo container for integration test usage

---

graphql2/graphqlapp/config.go
web/src/app/escalation-policies/PolicyStepCreateDialogDest.stories.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialogDest.stories.tsx

Fixes the Site 24x7 integration key type displaying as "Generic" in the dropdown.
- also fixes a couple typescript issues that made their way into master

intkeys: fix site24x7 label bug

---

alert/store.go
graphql2/graphqlapp/alert.go

It uses `withContextTx` for the transaction to create an alert and allow for additional calls, like storing metadata. This removes the need for the Store to create and commit its own transaction when the request may already have one available.
Related to work for #3764 (#3653)

graphql: use tx with create alert

---

graphql2/generated.go
graphql2/graph/destinations.graphqls
graphql2/graph/escalationpolicy.graphqls
graphql2/schema.graphql

Updates the GraphQL schema to remove the requirement of the `dest-types` experimental flag to use the new API.
- UI components that leverage the new API will still be controlled by the `dest-types` flag
- `CreateUserContactMethodInput` still requires the flag as its use currently changes how the `name` field validation is reported.
Subsequent PRs will update sections of the app to _always_ use the new dest API (without the flag), this is a prerequisite of that work.

graphql: remove experimental directive for dest-types

---

util/sqlutil/splitquery.go
util/sqlutil/splitquery_test.go

The `SplitQuery` function wrongly assumed `$$` was the only possible block delimiter, when it can be a user-defined tag like `$foobar$`
This PR fixes the bug and adds a test case for the more complex case.
More info:
https://www.postgresql.org/docs/16/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

util/sqlutil: fix handling of block delimiters in SplitQuery

---

.github/workflows/labeler.yml

Enables the `ignore_deleted` option in the labeler, this ignores the size of deleted files when calculating the size label for a PR.

dev: ignore deleted files when calculating pr size

---

Makefile
devtools/gqltsgen/run.go
graphql2/generated.go
graphql2/graph/destinations.graphqls
graphql2/graphqlapp/compat.go
graphql2/graphqlapp/contactmethod.go
graphql2/graphqlapp/destinationdisplayinfo.go
graphql2/graphqlapp/destinationtypes.go
graphql2/models_gen.go
notification/slack/channel.go
notification/slack/user.go
web/src/app/escalation-policies/PolicyStepEditDialogDest.stories.tsx
web/src/app/escalation-policies/PolicyStepsQuery.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.tsx
web/src/app/selection/DestinationSearchSelect.stories.tsx
web/src/app/selection/DestinationSearchSelect.tsx
web/src/app/users/UserContactMethodEditDialogDest.stories.tsx
web/src/app/users/UserContactMethodEditDialogDest.tsx
web/src/app/users/UserContactMethodListDest.stories.tsx
web/src/app/users/UserContactMethodListDest.tsx
web/src/app/users/UserNotificationRuleListDest.tsx
web/src/app/util/DestinationChip.tsx
web/src/app/util/DestinationInputChip.tsx
web/src/schema.d.ts

Fixes error handling with the new destination API. Namely, it prevents the entire page from breaking (e.g., the escalation policy details page) if any single action is invalid (e.g., archived or invalid slack channel). Instead individual chips/line items will render an error.
The purpose is to ensure in such an event, a user is able to interact with the page and take action to resolve the issue.
- gql typescript generator tool was updated to support GraphQL unions
<details>
<summary>Escalation Policy Details</summary>
TODAY
This PR
</details>
<details>
<summary>User Contact Methods</summary>
TODAY
This PR
</details>
<details>
<summary>Schedule On-Call Notifications</summary>
TODAY
This PR
</details>
N/A …

dest: Destination display error handling

---

app/cmd.go
engine/statusmgr/db.go
engine/statusmgr/queries.sql
engine/statusmgr/update.go
gadb/queries.sql.go
test/smoke/statusupdatesnolog_test.go

This PR introduces logic to "skip" status updates that are missing log entries.
Currently, these updates will result in _all_ status updates failing indefinitely, or until the alert has no changes for 7 days.
The new behavior has the following properties:
- If a log entry is missing for any reason, an error is logged, the status update is skipped, and the status subscription is updated. This means future updates will still be attempted.
- Since only log entries from the last hour are considered, that means 1 hour is the max possible delay for a status update (currently, it is indefinite)
- An "omit" list is kept during each engine cycle, ensuring each subscription is attempted at most once per engine cycle. If a status update fails today, it will be retried 100 times, …

engine/statusmgr: Skip status updates without an associated log entry

---

web/src/app/selection/DestinationInputDirect.tsx
web/src/app/selection/DestinationSearchSelect.tsx
web/src/app/util/RequireConfig.tsx

Updates the RequireConfig component to always request `destinationTypes` -- the API is no longer under the experimental flag.
- A missing `name` prop was also added to the `DestinationInputDirect` and `DestinationSearchSelect` components

ui/config: always request dest types

---

web/src/app/admin/admin-api-keys/AdminAPIKeyCreateDialog.tsx

Fixes an issue where fields on the GQL API key create dialog would reset with each poll.
The new approach leverages the Suspense behavior by setting the initial state/value directly, rather than relying on a `useEffect` handler.
Closes #3791

gql-api-keys: only setState once when duplicating key

---

web/src/app/escalation-policies/PolicyStepCreateDialog.tsx
web/src/app/escalation-policies/PolicyStepsCard.tsx
web/src/app/escalation-policies/PolicyStepsQuery.tsx
web/src/app/escalation-policies/stepUtil.tsx
web/src/app/rotations/util.tsx

- Switches policy step list to use urql.
- Replaces apollo cache manipulation with an array of strings (for drag-and-drop)
- Part of #2639 
- Part of #3240

ep: switch policy steps to use urql

---

web/src/app/services/ServiceMaintenanceDialog.tsx
web/src/app/util/ISOPickers.tsx

Updates the maintenance dialog to allow specifying a custom end time up to 24 hours in the future.
Closes #3681 
- A 4th option in the dialog allows specifying an exact end time.
N/A

service maint: allow specifying a custom end time

---

test/integration/schedules.spec.ts
web/src/app/schedules/ScheduleShiftList.tsx

Fixes a flaky playwright test that would fail to find the tooltip selector.
- Creating an override is no longer necessary as by default the user that creates a schedule is assigned as on-call

playwright: Fix tooltip hover check

---

web/src/app/lists/FlatListItem.tsx
web/src/app/lists/ListPageControls.tsx
web/src/app/lists/PaginatedList.tsx
web/src/app/users/UserList.tsx
web/src/app/util/AppLink.tsx
web/src/app/util/pagination.ts
web/src/cypress/e2e/favorites.cy.ts
web/src/cypress/e2e/users.cy.ts

This PR takes a composable approach with a ListPageControls component with two slots:
- `list` The list of items to render (likely FlatList)
- `search` Optional search bar (likely the `<Search>` component)
Part of #3240 
- Moving the cursor logic into a re-usable hook will be done separately.
N/A UI behavior is identical
N/A

urql: Convert UserList to use urql

---

web/src/app/rotations/RotationList.tsx

Updates RotationList to use ListPageControls instead of QueryList

urql: move rotation list to urql

---

web/src/app/admin/admin-service-metrics/AdminServiceFilter.tsx
web/src/app/wizard/WizardForm.jsx

Updates a couple of places that were never migrated to use the integration key types query.
- AdminServiceFilter (Admin -> Service Metrics)
- WizardForm (Setup Wizard)

intkey: update old code to use API-driven key types

---

web/src/app/main/components/BreadCrumb.tsx
web/src/app/main/components/ToolbarPageTitle.tsx
web/src/app/util/AppLink.tsx

This PR updates the breadcrumbs component to work on double nested routes (which haven't existed until now for universal integration keys)
Also fixes an issue with ref forwarding inside of AppLink.

ui: update breadcrumbs to handle doubly nested routes

---

web/src/app/lists/ListPageControls.tsx

Fixes a regression where conditional buttons would always render, even if the handler was undefined.

list pages: fix conditional create button rendering

---

integrationkey/config.go
validation/validate/range.go

Adds some initial validation and limits to integration key configuration.
Most notable:
- max 100 rules
- max 10 actions per rule
- max 10 parameters per action

uik: add bounds/limits on int key config

---

gadb/queries.sql.go
graphql2/generated.go
graphql2/graphqlapp/queries.sql
graphql2/graphqlapp/user.go
graphql2/models_gen.go
graphql2/schema.graphql
web/src/app/users/UserDetails.tsx
web/src/app/users/UserOnCallAssignmentList.tsx
web/src/schema.d.ts

Makes a single DB call for on-call assignments instead of the recursive resolvers it previously used.
Fixes #3870
If introducing any user-facing changes, provide a clear description of them.
- Added `onCallOverview` to the User type
- Deprecated `onCallSteps`

profile: optimize on-call query

---

gadb/queries.sql.go
graphql2/generated.go
graphql2/graph/univkeys.graphqls
graphql2/graphqlapp/integrationkey.go
integrationkey/queries.sql
integrationkey/uik.go
web/src/schema.d.ts

This PR adds a way to delete a secondary token so that users aren't forced to promote/delete the primary in the event the secondary token is lost/cant be used.
- added `deleteSecondaryToken` mutation

uik: add deleteSecondaryToken mutation

---

graphql2/generated.go
graphql2/graph/univkeys.graphqls
graphql2/graphqlapp/integrationkey.go
graphql2/models_gen.go
web/src/schema.d.ts

Adds fields for CRUD on single rules
- Added `KeyConfig.oneRule(id: ID!)` for reading a single rule (e.g., edit or delete dialog)
- Added `KeyConfigInput.setRule` for creating or updating a single rule
- Added `keyConfigInput.deleteRule` for deleting a single rule from config

uik: add methods of updating single rules

---

test/integration/email-cm.spec.ts
test/integration/first-login.spec.ts
test/integration/lib/select.ts
web/src/app/lists/FlatList.tsx
web/src/app/lists/FlatListItem.tsx
web/src/app/users/UserContactMethodDeleteDialog.tsx
web/src/app/users/UserNotificationRuleDeleteDialog.tsx
web/src/app/util/OtherActionsDesktop.jsx
web/src/app/util/SpeedDial.tsx

Fixes flaky contact method tests
- use single-selector action
- use `toBeHidden` instead of `not.toBeVisible`
- move mouse after submitting dialogs, since on mobile it can leave the pointer over the speed dial
- Update `pageAction` helper to wait for aria-expanded to update
- Set cm and first login tests back to parallel
- Fixed FlatList causing menus to disappear when new items are added/removed
- Added missing `additionalTypenames`
- Pass direct reference on OtherActions to prevent rerenders
- Added explicit `setOpen(false)` when SpeedDial actions are clicked

playwright: fix flaky contact method tests

---

web/src/app/escalation-policies/PolicyStepCreateDialog.stories.tsx
web/src/app/escalation-policies/PolicyStepCreateDialog.tsx
web/src/app/escalation-policies/PolicyStepDeleteDialog.tsx
web/src/app/escalation-policies/PolicyStepEditDialog.stories.tsx
web/src/app/escalation-policies/PolicyStepEditDialog.tsx
web/src/app/escalation-policies/PolicyStepForm.stories.tsx
web/src/app/escalation-policies/PolicyStepForm.tsx
web/src/app/escalation-policies/PolicyStepsCard.tsx
web/src/app/main/AppRoutes.tsx
web/src/app/main/components/NewUserSetup.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.stories.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.stories.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.stories.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.stories.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.tsx
web/src/app/users/UserContactMethodCreateDialog.stories.tsx
web/src/app/users/UserContactMethodCreateDialog.tsx
web/src/app/users/UserContactMethodEditDialog.stories.tsx
web/src/app/users/UserContactMethodEditDialog.tsx
web/src/app/users/UserContactMethodForm.stories.tsx
web/src/app/users/UserContactMethodForm.tsx
web/src/app/users/UserContactMethodList.stories.tsx
web/src/app/users/UserContactMethodList.tsx
web/src/app/users/UserDetails.tsx
web/src/app/users/UserNotificationRuleList.tsx
web/src/app/users/UserNotificationRuleListDest.stories.tsx

Now that the `dest-types` experimental flag has been merged and the legwork behind removing the conditional rendering behind the feature flag is complete, this PR focuses on renaming all of the files with "Dest" at the end back to their original names.

ui/chore: remove "Dest" suffix from relevant UI files

---

test/integration/escalation-policies.spec.ts
web/src/app/escalation-policies/stepUtil.tsx

Fixes the the display for the EP step delay text to properly be the next index + 1 (so +2 overall).
Before:
After:

ui: fix step number display for EP step delay text

---

web/src/app/forms/HelperText.tsx
web/src/app/forms/index.js
web/src/app/selection/DestinationField.tsx
web/src/app/selection/DestinationInputDirect.tsx
web/src/app/selection/DestinationSearchSelect.tsx
web/src/app/selection/DynamicActionForm.stories.tsx
web/src/app/selection/DynamicActionForm.tsx

Move to explicit error props as strings in form components, rather than various structures.
This is part of an effort to simplify form rendering and disconnect it from the API. More work to follow.
- `HelperText` component was added to normalize how form helper text is rendered (part of effort to move away from the old Form code magic.

dest/action: simplify error flow in forms

---

web/src/app/selection/DynamicActionForm.tsx
web/src/app/services/UniversalKey/UniversalKeyActionsForm.tsx
web/src/app/services/UniversalKey/UniversalKeyActionsList.tsx
web/src/app/services/UniversalKey/UniversalKeysActionsForm.stories.tsx
web/src/app/storybook/defaultDestTypes.ts
web/src/app/util/DestinationAvatar.tsx
web/src/app/util/DestinationChip.tsx
web/src/app/util/DestinationInputChip.tsx

Added directly from `uik-editor` branch with stories

Add Universal Key Actions management forms

---

web/src/app/schedules/ScheduleOverrideList.jsx

Updates ScheduleOverrideList to use ListPageControls instead of QueryList
Part of #3240

urql: move schedule override list to ListPageControls

---

web/src/app/admin/admin-message-logs/AdminMessageLogsLayout.tsx
web/src/app/lists/ListPageControls.tsx
web/src/cypress/e2e/admin.cy.ts

Updates AdminMessageLogsLayout to use ListPageControls instead of QueryList

urql: move admin message logs to ListPageControls

---

web/src/app/dialogs/FormDialog.jsx
web/src/app/escalation-policies/PolicyStepCreateDialog.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
web/src/app/services/UniversalKey/UniversalKeyActionsForm.tsx
web/src/app/services/UniversalKey/UniversalKeyRuleCreateDialog.tsx
web/src/app/services/UniversalKey/UniversalKeyRuleEditDialog.tsx
web/src/app/users/UserContactMethodCreateDialog.tsx
web/src/app/users/UserContactMethodEditDialog.tsx
web/src/app/util/ErrorConsumer.ts

Insulates error mapping from render order by allowing the `remainingLegacy()` function of `ErrorConsumer` to be used via callback.
- FormDialog now accepts error functions for dynamic errors
- Updated components to use `remainingLegacyCallback` method
- Simplified error display in UniversalKeyActionsForm

ErrorConsumer: Support function-based error handling and cleanup

---

graphql2/generated.go
graphql2/gqlgen.yml
graphql2/graph/destinations.graphqls
graphql2/graphqlapp/compat.go
graphql2/graphqlapp/contactmethod.go
graphql2/graphqlapp/destinationdisplayinfo.go
graphql2/graphqlapp/destinationvalidation.go
graphql2/graphqlapp/escalationpolicy.go
graphql2/graphqlapp/integrationkey.go
graphql2/graphqlapp/schedule.go
graphql2/models_gen.go
test/smoke/actionvalidate_test.go

Switches from generated models to use `gadb.DestV1` for GraphQL to simplify code and future validation.

dest: use gadb.DestV1 for Destination and DestinationInput

---

graphql2/generated.go
graphql2/gqlgen.yml
graphql2/graphqlapp/destinationtypes.go
graphql2/models_gen.go
notification/nfydest/provider.go
notification/nfydest/registry.go
notification/nfydest/typeinfo.go

Moves type definitions to a single package for destinations.
Next PR will use the Registry type to move logic out of the GraphQL code.

dest: move desttypes to nfydest package

---

app/startup.go
graphql2/graphqlapp/compat.go
graphql2/graphqlapp/destinationdisplayinfo.go
graphql2/graphqlapp/destinationtypes.go
graphql2/graphqlapp/destinationvalidation.go
notification/slack/nfydestug.go

Moves "Update Slack Usergroup" destination to use the `nfydest.Registry` instead of hard-coded in the graphql2 package.

nfydest: move slack usergroup support to registry

---

app/startup.go
graphql2/graphqlapp/compat.go
graphql2/graphqlapp/contactmethod.go
graphql2/graphqlapp/destinationdisplayinfo.go
graphql2/graphqlapp/destinationtypes.go
graphql2/graphqlapp/destinationvalidation.go
notification/webhook/nfydest.go

Moves webhook destination to use the `nfydest.Registry` instead of hard-coded in the graphql2 package.

nfydest: move webhook to `nfydest.Registry`

---

app/startup.go
graphql2/graphqlapp/compat.go
graphql2/graphqlapp/destinationdisplayinfo.go
graphql2/graphqlapp/destinationtypes.go
graphql2/graphqlapp/destinationvalidation.go
schedule/nfydest.go
schedule/rotation/nfydest.go

Moves Rotation and Schedule destinations to the `nfydest.Registry`

dest: move schedule and rotation to `nfydest.Registry`

---

web/src/app/alerts/CreateAlertDialog/CreateAlertDialog.tsx
web/src/app/dialogs/FormDialog.jsx
web/src/app/loading/components/LoadingButton.tsx
web/src/app/services/UniversalKey/UniversalKeyActionsForm.tsx
web/src/app/services/UniversalKey/UniversalKeyRuleDialog.tsx
web/src/app/services/UniversalKey/UniversalKeyRuleForm.tsx

Adds the prop `nextTooltip` to FormDialog, for optional use with the `next` button when using a stepper with FormDialog.
<details>
<summary>UIK Screenshot w/ tooltip</summary>
</details>
Also shows the next button on the last step when creating a new alert, rather than replacing it with the submit button.
<details>
<summary>Create Alert Screenshot</summary>
</details>
**Additional Changes:**
Addresses deprecation warning from using `FormDialog.defaultProps`

ui: add tooltip to formdialog action buttons, use for universal keys

---

graphql2/graphqlapp/destinationvalidation.go
notification/slack/channel.go

- Fixes `unexpected error` on missing slack channel
- Fixes error path so dest field errors are now passed to the correct field in the UI

dest: bugfix on error paths

---

devtools/resetdb/datagen.go
devtools/resetdb/main.go
escalation/desttargets.go
escalation/step.go
escalation/store.go
gadb/dest.go
graphql2/generated.go
graphql2/graph/escalationpolicy.graphqls
graphql2/graphqlapp/escalationpolicy.go
graphql2/graphqlapp/target.go
graphql2/schema.graphql
util/errutil/maperror.go

- move escalation.Step to use uuid for ID
- updated GraphQL code to use EP step `actions` field instead of `targets`
- Deleting the old methods and SQL queries will be done in a separate PR

dest: move remaining EP code away from targets and to dest

---

escalation/store.go

- Eliminated redundant SQL statements in Store struct
- Removed validation and helper functions for step targets
- Deleted methods handling step target operations

escalation: Remove unused step target methods

---

gadb/queries.sql.go
graphql2/generated.go
graphql2/graphqlapp/compat.go
graphql2/graphqlapp/escalationpolicy.go
graphql2/graphqlapp/messagelog.go
graphql2/graphqlapp/mutation.go
graphql2/graphqlapp/queries.sql
graphql2/graphqlapp/schedule.go
graphql2/graphqlapp/target.go
graphql2/inputs.go
graphql2/schema.graphql
notificationchannel/queries.sql
notificationchannel/store.go
schedule/oncallnotificationrule.go

- Changed OnCallNotificationRuleInput to use 'Dest' instead of 'Target'
- Refactored resolver and mutation logic for new field
- Deprecated 'Target' in the schema and added relevant annotations
- Removed unused imports and redundant validation code

Transition OnCallNotificatonRule to use 'Dest' field

---

web/src/app/schedules/ScheduleOverrideDialog.jsx
web/src/app/schedules/temp-sched/TempSchedDialog.tsx
web/src/app/util/FilterContainer.jsx

Fixes #3914
Also fixes:
- defaultProps deprecation warning in console for components related to this dialog, when opening
- disableSubmit not set for temp schedule dialog step 0

ui: fix edit empy temp sched bug

---

engine/engine.go
engine/isknowndest.go
engine/message/bundlealerts.go
engine/message/db.go
engine/message/dedupalerts.go
engine/message/deduponcallnotifications.go
engine/message/dedupstatusmessages.go
engine/message/queue.go
engine/message/queue_test.go
engine/sendmessage.go
gadb/dest.go
gadb/queries.sql.go
graphql2/graphqlapp/messagelog.go
notification/desttype.go
notification/namedreceiver.go
notification/receiver.go
notification/resultreceiver.go
notification/store.go
notification/twilio/sms.go
notification/twilio/voice.go
user/contactmethod/queries.sql
user/contactmethod/store.go

Updates code using `notification.Dest` as a comparable value to use `DestHash` instead along with updating some signatures to use `gadb.DestV1` directly instead of type/value.

dest: move to DestV1 away from DestType

---

graphql2/graphqlapp/app.go
notification/nfydest/validate.go
notification/nfydest/validateaction.go

Fixes an issue where invalid fields would result in 500 unexpected errors for field validation issues.
- arg and param errors are now correctly marked client-safe
- updated error presenter to return proper codes for these types

graphql: Improve error handling for validation for arg and param types

---

notification/store.go

This pull request improves the error handling for validation in GraphQL. It includes a fix for a bug where the LastMessageStatus function was returning an error when there were no rows found in the database. Now, if the query returns no rows, the function will return nil instead of an error. This improves the overall error handling and ensures a smoother experience when working with GraphQL validation.

Fix no-rows bug with last message status

---

.github/workflows/labeler.yml

This pull request adds permissions to the labeler job in the workflow file. The permissions include read access to contents and write access to pull requests.
Fixes broken PRs due to recent API changes.

Add permissions to labeler

---

integrationkey/uik/handler.go

Encapsulates errors in validation for more informative responses.

integrationkey/uik: Wrap error in validation for HTTP response

---

alert/store.go

The intention here should be to initialize a slice with a capacity of  `len(alertIDs)`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW

fix: fix slice init length

---

remotemonitor/config.go
remotemonitor/monitor.go

`remotemonitor` should retry sending emails to create alerts to avoid getting paged due to a temporary network outage or similar.
N/A - this is a small change to implement retrying SMTP send in `remotemonitor` only
For users of `goalert monitor` command, an additional field is added to the TOML config to allow specifying a number of times to retry sending email when creating test alerts.  The field is validated to ensure inputs are reasonable (in range 0-5).

add smtp retries

---

engine/schedulemanager/db.go
engine/schedulemanager/queries.sql
engine/schedulemanager/update.go
gadb/models.go
gadb/queries.sql.go
schedule/data.go
sqlc.yaml

Transitions the schedule manager to sqlc
- most IDs are now handled natively as UUIDs
- Queries are unchanged

engine/schedulemanager: convert to sqlc

---

util/timeutil/isoduration.go
util/timeutil/isoduration_test.go

Fixes a bug where sometimes the `SecondsPart` of `ISODuration` would result in an encoded exponent and produce a string that is not a valid ISO 8601 duration.

util/timeutil: Ensure exponents are never encoded into the output String()

---

app/app.go
app/cmd.go
app/config.go
app/context.go
app/initsmtpsrv.go
app/initstores.go
app/listenevents.go
app/multilistener.go
app/multilistener_test.go
app/pause.go
app/runapp.go
app/startup.go
go.mod
go.sum
smtpsrv/config.go
smtpsrv/server.go
test/smoke/harness/harness.go
util/log/log.go

Introduced `*slog.Logger` to the `App` struct as an eventual replacement for the custom logging package.
This can also be used as a logger to pass into other tools that take an *slog.Logger argument.

logging: introduce slog.Logger

---

app/app.go
app/cmd.go
app/pause.go
migrate/migrate.go
swo/manager.go
swo/pgxpool.go

Removes connection management for `sql.DB` now that it's backed by a `pgxpool.Pool`.
- Also, added validation that migration version matches to prevent using a switchover from an older version of GoAlert when newer DB migrations are present.

pgxpool: Don't use idle connections with stdlib when doing pooling

---

engine/message/db.go
engine/processinglock/conn.go

Updates use of the global message sending lock to use the `_try` variant. If multiple instances of the engine are running, it can cause all instances to block until released, preventing other modules from processing.

engine: update advisory lock handling and add locked transaction support

---

engine/processinglock/conn.go
engine/processinglock/lock.go
engine/processinglock/queries.sql
engine/signalmgr/schedulemessages.go
engine/signalmgr/setup.go
gadb/queries.sql.go

This PR adds a `WithTxShared` to the processing lock package. This gives the same module-version guarantees as before, but allows for concurrent workers. Additionally, the signals code has been updated to allow for up to 3 workers and leveraging this.
- Existing/older versions of the engine will continue to use `NO WAIT` and are granted exclusive access, ensuring no conflicts with new code
- the shared lock will BLOCK, since it is used by workers not in the engine cycle (thus no need for the same non-blocking guarantees, but DO want to guarantee work is performed)
- Previously, lock acquisition was performed as "get lock, check version" which could cause out-of-date instances to cause skips or unnecessary blocking. This has been changed to "get lock, if-correct-version" …

engine/processinglock: enable shared locking for concurrent work

---

app/secureheaders.go

Fix RiverUI in local dev with CSP headers enabled.
Since the UI doesn't support passing a nonce value and the assets are fixed, hard-code the inline hashes to fix local development.
- Add a make target somehow to load the page and calculate them automatically
- Build our own UI for monitoring jobs

http: fix Content Security Policy for riverui

---

Makefile.binaries.mk
devtools/ci/dockerfiles/demo/Dockerfile.prebuilt
devtools/ci/dockerfiles/goalert/Dockerfile.prebuilt
devtools/genmake/template.mk

Fixes and simplifies `make container-goalert` and `make container-demo`
Only notable change is switching from the custom `ARCH` build arg to the built-in `TARGETARCH` allowing all platform builds to be done in parallel.

build: refactor container build process to use docker buildx

---

web/src/app/services/IntegrationKeyList.tsx
web/src/app/services/UniversalKey/UniversalKeyPage.tsx

This PR makes two changes to reduce confusion:
- Rather than clickable items mixed in the integration key list, UIKs will now have a MANAGE button
- The universal key edit page now includes an example request for how to use a key.
Part of #4187 
See above
N/A

uik: add some clarity to using universal keys 

---

web/src/app/services/UniversalKey/ExprField.tsx

This adds in a a info icon with a link to the expr syntax docs in the label of each expr field.
Part of [4187](https://github.com/target/goalert/issues/4187)
N/A
Users can now click to see the docks via the info icon
N/A
N/A

adding info link to expr syntax

---

.github/dependabot.yml

This pull request includes a change to the `.github/dependabot.yml` file to better manage dependencies by introducing a grouping mechanism.
Dependency management improvements:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R98-R100): Added a `groups` section under the `go-deps` dependency type to allow pattern-based grouping of dependencies.

chore(deps): add group for Go dependencies in dependabot configuration

---

engine/cleanupmanager/queries.sql
engine/cleanupmanager/scheddata.go
engine/cleanupmanager/setup.go
gadb/queries.sql.go

This PR changes the schedule data cleanup from one big loop, to a look-for-work step followed by a job for individual schedules.
This has better error handling and retrying behavior. It won't risk the "big" job timing out, it is easier to track errors, and it allows better prioritization due to the smaller pieces.

engine/cleanupmgr: individualize schedule data cleanup jobs

---

calsub/http.go
test/smoke/calendarsubscriptionjson_test.go

Adding support for `Accept: application/json` on calendar subscription requests.
This pull request introduces several changes to the `calsub/http.go` file, primarily enhancing the functionality to support JSON responses and refactoring existing code to improve maintainability.
* Added a new constant `PayloadType` and types `JSONResponseV1` and `JSONShiftV1` to structure JSON responses for calendar subscriptions.
* Modified the `ServeICalData` function to handle requests with `Accept: application/json` header, constructing and returning a JSON response with schedule and user shift details.
* Introduced the `userNameMap` function to encapsulate the logic for fetching and mapping user names from user IDs, replacing the inline code in `ServeICalData`.
* Refactored the code …

calsub: Add JSON as a supported format for calendar subscriptions

---

web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx

Add a tooltip to the on-call notification label to provide users with additional context regarding the notification behavior when multiple rules are configured.

Add tooltip for on-call notification clarity

---

.github/workflows/dep-autoapprove.yml

Adds a workflow for dependabot PRs that will run `make generate`, commit changes (if any), and then have dependabot approve the PR.
This should result in most safe changes handling things like version updates in generated files, and having CI passing before a developer looks at it to do final approval and merge.
Due to the nature of GH Actions, this may take some iteration to get right.

deps: run make generate and auto-approve dependency PRs

---

.github/workflows/dep-autoapprove.yml

Trial-and-error -- auto-approve doesn't currently work, if this doesn't we may have to settle for `make generate` for now.

ci: update permissions for Dependabot auto-approve workflow

---

web/src/app/rotations/RotationUserDeleteDialog.tsx

Fixes an issue where removing a user from a rotation could cause it to advance.
Fixes #3771

feat: fix rotation advance when removing a user

---

engine/message/ratelimit.go

Increases On-Call Status Notifications
- 3 per minute, burst (from 2 per 15-minute)
- 20 per hour, overall (from 4 per hour)
Fixes #4188

engine: update rate limit rules for on-call user notifications

---

app/lifecycle/manager.go

Fixes an issue where the app would deadlock if the Run function failed outside of shutdown.
Fixes #3868

fix(lifecycle): skip shutdown wait on run failure

---

web/src/app/services/ServiceCreateDialog.tsx
web/src/app/services/ServiceEditDialog.tsx
web/src/app/services/ServiceForm.tsx
web/src/app/util/ErrorConsumer.ts

Fixes issues where service create dialog didn't display label errors and unexpected errors didn't get displayed.
Fixes #3623

service: fix label error messaging for create and edit

---

notice/store.go

Disable alert limit notice when limit is disabled.
Fixes #3313

fix(notice): handle negative limit in FindAllServiceNotices

---

web/src/app/admin/AdminToolbox.tsx

Disables toolbox if Twilio isn't enabled.
Fixes #1220 
**Screenshots**

feat: add Twilio configuration check in AdminToolbox component

---

app/inithttp.go
calsub/http.go
genericapi/handler.go

This PR adds methods to the registered routes for API calls, ensuring unknown API calls return 404 and the UI/index.html is only returned on GET requests.
- Updated heartbeats and user avatar to use `PathValue`
- Fix calsub handling when no token specified to return 401 (instead of 500 error)

http: Add method restrictions to routes, fix response codes

---

engine/rotationmanager/advance.go
engine/rotationmanager/update.go

- Updates the v1 detection code to calculate proper advance for V1 state, before marking it as V2
- Returns an error for unknown versions.
Part of #4244

rotations: fix v1 -> v2 migration logic

---

web/src/app/schedules/calendar-subscribe/CalendarSubscribeButton.tsx
web/src/app/schedules/calendar-subscribe/CalendarSubscribeCreateDialog.tsx
web/src/app/schedules/calendar-subscribe/CalendarSubscribeEditDialog.tsx
web/src/app/schedules/calendar-subscribe/CalendarSubscribeForm.tsx
web/src/app/schedules/calendar-subscribe/CalendarSuccessForm.tsx

Converts the calendar subscribe jsx files to tsx to properly enforce typing.
Include any out of scope items here.
N/A
N/A
N/A
N/A

Jsx to tsx convert calendar subscribe jsx files

---

web/src/app/forms/FormField.jsx
web/src/app/services/ServiceLabelEditDialog.tsx
web/src/app/services/ServiceLabelForm.tsx

Converts the `ServiceLabelForm.tsx` components to typescript.
For significant amounts of work, it is best to start an issue first, preferably before the work is started.
For large pull requests, be sure to reference the associated GitHub issue(s).
Part of https://github.com/target/goalert/issues/2318

ui/service: convert ServiceLabelForm to typescript

---

engine/schedulemanager/update.go
test/smoke/harness/harness.go
test/smoke/scheduleoverrideadd_test.go
test/smoke/scheduleoverrideremove_test.go
test/smoke/scheduleoverridereplace_test.go

- Adds smoketests for each of the three override types
- Ensures adding a new shift only happens if the user was already on-call (for replace overrides)

schedules: Fixes a bug where 'replace' overrides would behave as an 'add' + 'delete' rather than replace

---

engine/cleanupmanager/queries.sql
gadb/queries.sql.go

Fixes a bug where the API cleanup would incorrectly disable already disabled calendar subscriptions; causing the job to eventually timeout.

fix: Exclude disabled subscriptions from inactivity queries

---

app/runapp.go
engine/engine.go

Removes unecessary goroutines surrounding river's `.Start()` methods, removing the startup race and need to check for early shutdown errors from the library.

river: call `.Start()` synchronously

---

gadb/queries.sql.go
graphql2/graphqlapp/queries.sql

The on-call assignments query omitted teh `is null` check and was incorrectly including historic shifts in addition to currently active ones.
- Formatted the query file with pgformatter for consistency with other query files.
Fixes #4256

profile: Fix on-call assignments page data

---

graphql2/graphqlapp/service.go

The average ack time currently returns the close time - this corrects the avgacksec to return the average acknowledge time

Correct Average Ack Time in reporting

---

ctxlock/idlocker_test.go

This pull request includes a small change to the `TestIDLocker_CancelQueue` test in the `idlocker_test.go` file. The `Timeout` configuration for the `ctxlock.NewIDLocker` instance was increased from `time.Millisecond` to `time.Second` to adjust the timeout duration.
This matches other tests and should resolve issues in CI.

fix: increase timeout in TestIDLocker_CancelQueue for better stability

---

Makefile
dataloader/fetcher_test.go
engine/schedulemanager/calcupdates.go
engine/schedulemanager/calcupdates_test.go
engine/schedulemanager/update.go
go.mod
go.sum
test/smoke/harness/email.go
test/smoke/harness/harness.go
test/smoke/harness/mailpit.go
test/smoke/harness/mailpit_test.go
test/smoke/harness/slack.go

This PR updates the schedule manager to:
- reactors logic to focus on a single schedule at a time, greatly simplifying the flow
- separates fetching data from calculating desired state, in prep for job queue migration
- fixes a few flaky test issues
Part of #4245
N/A
N/A

engine/schedulemanager: refactor schedule calculation for maintainability and job queue migration

---

genericapi/handler.go
test/smoke/maxbodyresponse_test.go
util/errutil/httperror.go

Fixes various incorrect status code responses
- Hitting a limit (like too many unacked alerts) now correctly responds with [409 Conflict](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/409) fixing a regression.
- Body size limit errors now respond with [413 Content Too Large](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/413)
- Aborted/disconnected requests will be sent a 499 to distinguish from 400
- Requests in the queue that timeout will now get [408 Request Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/408) (as opposed to the [429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/429) when the queue is full)
Also a test was added for the body size limit, as prior …

fix various HTTP response codes

---

alert/alertlog/search.go
graphql2/generated.go
graphql2/graphqlapp/alert.go
graphql2/graphqlapp/service.go
graphql2/models_gen.go
graphql2/schema.graphql
test/integration/service.spec.ts
web/src/app/services/ServiceDetails.tsx
web/src/app/services/ServiceRecentEvents.tsx
web/src/schema.d.ts

Adds a `Recent Events` section to the service details page that shows the 5 most recent events from the alert log (any alert owned by the service).
This is intended to help debugging issues, especially "duplicate suppressed" messages which would previously require the user to open all active alerts and look at their individual logs.
- Note: the log entries are clickable and take you to the alert
- New section under the on-call card on the service details page
- `recentEvents` under `Service` with the same types/functionality as the one under `Alert` (but limited to a single service ID instead of alert ID)

service details: Add "Recent Events" as an aggregated alert log
