- graphql2/generated.go
- graphql2/graphqlapp/service.go
- graphql2/models_gen.go
- graphql2/schema.graphql
- user/favorite/store.go
- web/src/app/lists/PaginatedList.js
- web/src/app/services/ServiceCreateDialog.js
- web/src/app/wizard/util.js
- web/src/app/wizard/util.test.js
- web/src/cypress/integration/favorites.ts
- web/src/cypress/integration/services.ts
- web/src/cypress/support/service.ts
This PR makes new services favorited by default and refactors the Cypress tests for service favorites to be more generalized for adding new favorite types.
The `service.ts` support file was also updated to use the new GraphQL endpoint.
> services: favorites test code improvements

- web/src/app/escalation-policies/PolicyStepForm.js
- web/src/cypress/integration/escalationPolicySteps.ts
- web/src/package.json
- web/src/yarn.lock
When Slack is disabled, the user config section in the EP step form used the wrong index, this PR fixes that and adds a simple test to check for it in the future.
Fixes #34
> ep step: allow user selection when Slack is disabled

- web/src/app/main/components/Login.js
Re-adds a missing key to providers rendered from a map.
> ui: add key to login provider elements

- web/src/app/admin/AdminRouter.js
- web/src/app/users/UserContactMethodVerificationDialog.js
- web/src/app/users/UserRouter.js
- web/src/app/util/RequireConfig.js
This PR adds hooks `useConfig` and `useSessionInfo` to eventually replace the `Config` and `RequireConfig` higher-order components.
- Existing hooks components have been updated to use the new hooks
- Fixes the admin page flicker (on load)
> hooks: add useConfig and useSessionInfo

- web/src/app/wizard/WizardRouter.js
Before, for mobile when on the wizard page, there was a horizontal scroll.
Now there is no horizontal scroll.
> ui: remove wizard mobile horizontal scroll

- migrate/inline_data_gen.go
Fix `migrate/inline_data_gen.go` - tweak to migration occurred but forgot to regenerate.
> migrate: regenerate embedded

- Makefile
- devtools/ci/dockerfiles/build-env/Dockerfile
- devtools/runjson/ci-cypress.json
- migrate/inline_data_gen.go
This PR makes some adjustments for our ci pipeline work.
- Adjusts `PATH` for `postgres:11`
- Production cypress smoketests using alternate `RUNJSON` file.
- `RUNJSON` ci file adjustments to align with local dev setup (goalert user & db)
> ci: ci tweaks

- web/src/cypress.json
- web/src/cypress/integration/schedules.ts
- web/src/cypress/support/page-fab.ts
- web/src/cypress/support/select-by-label.ts
Updates flaky tests with more assertions to trigger more and proper retries from within Cypress.
> cypress: tweaks for flaky tests

- devtools/ci/tasks/scripts/test-integration.sh
Fixes an issue where the `DB_URL` contains query parameters.
> cypress: fix db url handling

- devtools/ci/tasks/scripts/test-integration.sh
Fixes an issue where debug tgz failed if no screenshots/video was taken
> ci: add all of cypress dir to debug tgz

- web/src/cypress/integration/escalationPolicySteps.ts
This PR adds more assertions to the cypress test for escalation policy steps.
> cypress: add more assertions for epSteps test

- web/src/app/escalation-policies/PolicyDeleteDialog.js
This PR fixes a race condition when deleting an escalation policy. Currently, if the Apollo cache is updated faster than the page rerenders the dialog component, the broken page will then be rendered instead saying that the EP does not exist, because the `<Redirect />` component did not have a chance to be rendered/executed.
Now, instead of rendering the `<Redirect />` component, an action will be dispatched when the mutation completes successfully that will redirect back to the list.
- Converts the component to hooks
> eps: race condition fix for deletion

- web/src/app/rotations/RotationDeleteDialog.js
This PR converts `RotationDeleteDialog` to hooks. 
This helps solve a race condition with redirect after deletion.
> rotations: convert RotationDeleteDialog to hooks

- web/src/app/schedules/ScheduleDeleteDialog.js
This PR converts `ScheduleDeleteDialog` to hooks.
This helps solve a race condition with redirect after deletion.
> schedules: convert ScheduleDeleteDialog to hooks

- devtools/ci/dockerfiles/build-env/Dockerfile
Updates the build environment golang version such that the builds can run properly with the pending pgx driver changes.
> ci: update build env Go version to 1.13

- migrate/migrate.go
This PR updates a missing OID from the migrate-up check.
> migrate: set correct OID for migration target

- migrate/migrate.go
This PR adds retry logic to the DB connect call during the migrations. This corrects a regression introduced during the DB driver changes, where application startup would fail if the DB proxy (e.g. a side-car scenario) had not yet started. 
**Additional Information**
- Retry follows the same backoff timing as elsewhere in the app
- Max of 12 retries
- All connection errors are still logged
> migrate: retry DB connection on initial failure

- web/src/app/users/UserContactMethodList.js
- web/src/app/users/UserDetails.js
- web/src/cypress/integration/profile.ts
- web/src/cypress/support/page-fab.ts
To meet internal compliance needs, we need to move the Notification Disclaimer from the Contact Method card on the profile page to the "Add Contact Method" form.
- Converts `UserDetails` to hooks
> tcpa compliance: move notification disclaimer to add contact method form

- web/src/app/lists/FlatList.js
Fixes drag-and-drop rendering on the rotation details page.
> rotations: add missing placeholder in DnD control

- devtools/ci/dockerfiles/build-env/Dockerfile
Updating Go to the latest version.
> go: update to version 1.13.4

- web/src/.eslintrc.js
- web/src/app/alerts/components/AlertDetails.js
- web/src/app/alerts/components/UpdateAlertsSnackbar.js
- web/src/app/dialogs/components/DialogTitleWrapper.js
- web/src/app/lists/FlatList.js
- web/src/app/rotations/RotationUserList.js
- web/src/app/schedules/ScheduleShiftList.js
- web/src/app/util/CountDown.js
- web/src/app/util/Options.js
- web/src/app/wizard/WizardRouter.js
Adds the `no-else-return` rule following the same pattern/rules we use in backend.
```js
if (foo) {
return 'bar'
} else {
return 'baz'
}
```
Will now be automatically "fixed" to:
```js
if (foo) {
return 'bar'
}
return 'baz'
```
> dev: add eslint rule `no-else-return`

- web/src/package.json
- web/src/yarn.lock
Upgrade react-beautiful-dnd to version 12.1.1
🏃‍♀️ 10% faster + 25% less memory usage for everyone
🎯 More robust browser focus retention
♿️ Accessibility overhaul with perfect lighthouse score
📱 Dragging with touch now allows for reparenting
🧨 Reworked error handling
🎩 Drop animation now flushed on user scroll
`onKeyDown`, `onMouseDown` and `onTouchStart` have been removed from DragHandleProps
https://github.com/atlassian/react-beautiful-dnd/releases/tag/v12.1.1
> ui dependencies: upgrade react-beautiful-dnd to v12

- devtools/ci/tasks/scripts/build-binaries.sh
This PR renames our bundle tarball created for integration tests to use format `integration-<date>-<short_sha>...` to allow proper sorting/ordering.
> ci: rename bundle tarball

- web/src/webpack.dll.config.js
> dev: Remove prop-types-extra from dll config

- notification/twilio/voice.go
- smoketest/twiliovoiceverification_test.go
This PR improves the user voice call messages. 
For verification codes, it repeats the code's digits two times, with a delay in between every digit, making it more understandable.
For all voice calls, it introduces a timeout of 10 seconds (versus a default of 5 seconds), which gives the user more time to select their option from the keypad.
> twilio : make voice verification calls more user-friendly

- web/src/cypress/integration/scheduleCalendar.ts
> cypress: increase timeout threshold for creating schedule

- config/config.go
- config/hints.go
- devtools/configparams/main.go
- graphql2/generated.go
- graphql2/graphqlapp/config.go
- graphql2/mapconfig.go
- graphql2/models_gen.go
- graphql2/schema.graphql
- web/src/app/admin/AdminConfig.js
- web/src/app/apollo.js
Update protected branch with latest master again, to resolve conflicts.
> feature/refetch: update with latest

- web/src/app/lists/QueryList.js
This PR updates the `QueryList` component to use the `network-only` fetch policy and enable polling when not paginating through results.
It fixes issues when coming from a details page (e.g. favorite or delete) and having the list be out-of-date.
> ui/QueryList: always display new data

- web/src/cypress/integration/schedules.ts
Added ui tests for schedule assignments including creating a user, adding multiple rules, unchecking days, and changing times.
> cypress: ui tests for creating scheduling assignments

- docs/development-setup.md
- docs/getting-started.md
Thanks for goalert! I was trying it out and updated the documentation as I went along, hope that helps!
> docs: list minimum Go version and fix typo in pg setup

- .dependabot/config.yml
> deps: ignore @date-io/luxon <= 2.2.0

- web/src/cypress/integration/profile.ts
- web/src/cypress/support/profile.ts
- web/src/cypress/support/schedule.ts
This PR updates several support commands found under `web/src/cypress/support` using the old `graphql` api to the newer, more supported `graphql` api.
- Alert tests, to be completed in tandem with updating the alert UI components to the newer api.
> cypress: update support functions to utilize gql2

- .dependabot/config.yml
There are a couple issues in this library that conflict with our pickers library -- see #391
> deps: ignore @date-io/luxon 2.4.0

- web/src/package.json
- web/src/yarn.lock
This is a dependency of `@babel/plugin-transform-runtime`
Reference: https://babeljs.io/docs/en/babel-plugin-transform-runtime
> deps: install @babel/runtime

- web/src/app/lists/QueryList.tsx
This PR converts QueryList to typescript.
> ui: convert querylist to typescript

- web/src/app/util/Diff.js
- web/src/app/util/Diff.tsx
- web/src/app/util/debug.ts
- web/src/package.json
- web/src/yarn.lock
> ui: convert Diff and debug util to typescript

- web/src/app/util/CopyText.tsx
- web/src/app/util/copyToClipboard.ts
> ui: convert copy to clipboard util to typescript

- Makefile
- web/src/app/tsconfig.json
- web/src/cypress/integration/escalationPolicySteps.ts
- web/src/cypress/integration/profile.ts
- web/src/cypress/support/rotation.ts
- web/src/package.json
- Adds `noUnusedLocals` and `noFallthroughCasesInSwitch` to our `tsconfig.json`
- Compartmentalizes yarn scripts into `format`, `lint`, and `ts-compile` with an all-in-one command `yarn run check`
> dev: clean up yarn scripts, tsconfig

- web/src/cypress/integration/services.ts
Resolves the issue where test failed at retry because the services persisted.
> cypress: resolve service test retry issue

- .dependabot/config.yml
Fixes formatting in `.dependabot/config.yml` -- now passing validation: https://dependabot.com/docs/config-file/validator/
> dependabot: fix formatting in config.yml

- web/src/app/services/HeartbeatMonitorForm.js
This PR converts the `<HeartbeatMonitorForm />` class component to a functional component.
> hooks: converting HeartbeatMonitorForm to hooks

- web/src/app/services/ServiceForm.js
This PR converts the `<ServiceForm />` class component to a functional component.
Co-authored-by: Quynhd07 <Quynhd07@yahoo.com>
> hooks: converting ServiceForm to hooks

- web/src/app/main/components/Login.js
This PR converts `< Login />` to hooks.
> Hooks: convert Login to hooks

- web/src/app/rotations/RotationEditDialog.js
This PR converts `< RotationEditDialog />` to hooks.
> hooks: convert RotationEditDialog to hooks

- web/src/app/services/IntegrationKeyCreateDialog.js
- web/src/app/services/ServiceCreateDialog.js
This PR converts `< ServiceCreateDialog />` to hooks.
Co-authored-by: jakegleason jacob.gleason07@gmail.com
> hooks: convert ServiceCreateDialog to hooks

- web/src/app/rotations/RotationUserListItem.js
This PR converts `< RotationUserListItem />` to hooks.
> hooks: convert RotationUserListItem to hooks

- web/src/app/rotations/RotationForm.js
This PR converts `< RotationForm />` to a functional component.
> hooks: convert RotationForm to functional component

- web/src/app/rotations/UserForm.js
This PR converts `< UserForm />` to a functional component.
> hooks: convert UserForm to functional component

- web/src/app/rotations/RotationRouter.js
This PR converts `< RotationRouter />` to a functional component.
> hooks: convert RotationRouter to functional component

- web/src/app/loading/components/Spinner.js
This PR converts `< Spinner />` to hooks.
> hooks: convert Spinner to hooks

- web/src/app/util/QuerySetFavoriteButton.js
This PR adds an error response to the favorite button. If a mutation error occurs, the dialog will return the error's message.
> favorites: add dialog to handle mutation errors

- devtools/ci/dockerfiles/all-in-one/Dockerfile
- devtools/ci/dockerfiles/goalert/Dockerfile
This PR adds missing `EXPOSE` lines to the Dockerfiles.
> docker: add EXPOSE line in relevant dockerfiles

- docs/development-setup.md
> docs/a11y: use proper heading for title

- graphql2/generated.go
- graphql2/graphqlapp/alert.go
- graphql2/models_gen.go
- graphql2/schema.graphql
- web/src/schema.d.ts
This PR introduces the sanitize option for createAlertInput. The sanitize function strips unwanted characters from the payload, which aligns with our other API endpoints.
> alerts: add sanitize option to createAlertInput

- web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceSelect.js
> ui: fix service search select filtering logic

- web/src/app/services/ServiceForm.tsx
- Delete goalert/web/src/app/services/ServiceForm.js
- Convert ServiceForm to ts
> ui: Converted ServiceForm to Typescript

- web/src/app/util/RequireConfig.js
This PR converts the RequireConfig utility to use the new hooks API.
> ui/util: convert RequireConfig.js to hooks

- web/src/app/admin/AdminFieldComponents.tsx
- web/src/app/admin/AdminNumberLookup.tsx
- web/src/app/admin/AdminSMSSend.tsx
- web/src/app/admin/AdminSection.tsx
- web/src/app/apollo.js
- web/src/app/users/UserContactMethodForm.js
- web/src/app/util/TelTextField.js
- web/src/app/util/TelTextField.tsx
This PR introduces new component, <TelTextField />, which is a TextField specific for phone number field. All phone number fields (add contact method, Admin Toolbox, and Admin config) have converted to <TelTextField />
> TelTextField: add new phone number input field component with live validation

- .dockerignore
This PR has docker ignore `.git/`, decreasing the size of the build context thereby decreasing time to upload
> docker: ignore .git/ directory

- devtools/ci/dockerfiles/cypress-env/Dockerfile
- web/src/cypress/support/form.ts
- web/src/cypress/support/select-by-label.ts
- web/src/cypress/types/select-by-label.d.ts
- web/src/package.json
- web/src/yarn.lock
Updating to the most recent version of cypress
> deps: update cypress to 4.11.0

- README.md
Updating the reference to the `all-in-one-demo` image to the new name.
> docker: update all-in-one image name

- devtools/ci/dockerfiles/build-env/Dockerfile
- go.mod
- notification/manager.go
This PR updates Go to version 1.15.1 which adds the ability to embed TZ information as well as new vet rules.
https://golang.org/doc/go1.15
> dev: update to Go 1.15.1

- devtools/ci/dockerfiles/build-env/Dockerfile
- engine/message/db.go
- go.mod
- notification/manager.go
- smoketest/cmtestdisable_test.go
- web/src/yarn.lock
Merging master into feature branch to get 1.15 fixes
> update feature/temp-schedules with master

- migrate/inline_data_gen.go
- migrate/migrations/20200922140909-session-last-access-time.sql
Updating with latest from master with migration fix
> temp schedules: merge master

- web/src/app/users/UserSessionList.tsx
This PR fixes the issue with "Log Out Other Sessions" after ending a single session.
Additionally the dialog code in `UserSessionList.tsx` was refactored to be easier to follow and two additional issues were fixed:
- log out a single session could result in a blank/broken session list
- Unknown/blank user agent strings would cause a broken page or invalid text
Fixes #873
> ui/sessions: fix issues with ending sessions

- web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx
- web/src/app/schedules/temp-sched/TempSchedTimesStep.tsx
Just making some tweaks to the step text in the temporary schedule dialog
> temp-schedules: rephrase step text

- web/src/app/schedules/ScheduleCalendar.js
- web/src/app/schedules/temp-sched/TempSchedAddShiftForm.tsx
- web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx
- web/src/app/util/ClickableText.tsx
- fixed overflow scroll bug on shifts list
- made the manual entry toggle an anchor tag
- updated green temp shift color to a darker shade for a11y
I found a nice tool to check for color contrast: https://snook.ca/technical/colour_contrast/colour.html#fg=FFFFFF,bg=094F13
> ui: miscellaneous usability improvements

- oncall/singlerulecalculator.go
This PR fixes issues with the new oncall calculation code with rotations with < 2 participants
Fixes #960 
0-length rotations caused issues because an assumption was made that `.Rotation` would be populated in all cases. However empty rotations have no entry in `rotation_state` which causes them to be omitted from the original query. The fix for this was to ensure target type is user before assuming target id is a user id.
single-user rotations caused an infinite loop because the `UserID` method would short-circuit without advancing the rotation times. The fix for this is to not iterate through the rotation when there would be no handoff.
> oncall: handle calculations for 0 and 1 participant rotations

- web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx
This solves some UI blemishes such as hiding the scrollbar area, removing the horizontal overflow scroll, and giving the shifts list an absolute height
> fix: temporary schedules dialog layout

- devtools/ci/dockerfiles/cypress-env/Dockerfile
- web/src/app/lists/PaginatedList.tsx
- web/src/app/util/AppLink.tsx
- web/src/cypress.json
- web/src/cypress/support/fail-fast.ts
- web/src/cypress/support/index.ts
- web/src/cypress/support/login.ts
- web/src/cypress/support/util.ts
- web/src/package.json
- web/src/yarn.lock
Updating to the latest version of Cypress
> update to Cypress 5.5.0

- devtools/ci/tasks/scripts/codecheck.sh
- devtools/ci/tasks/test-integration.yml
This PR updates the code check and task file so the cypress-env image only needs to be built once per version
> cypress: use tagged image

- web/src/app/admin/AdminDialog.js
This PR has AdminDialog use apollo's hooks 
Part of #923
> ui/hooks: admin dialog

- web/src/app/alerts/components/AlertDetails.js
This PR converts the AlertDetails class to a function
Part of #923
> ui/hooks: alert details

- web/src/app/alerts/components/AlertsListFilter.js
This PR has AlertsListFilter use hooks
Part of #923
> ui/hooks: alerts list filter

- web/src/app/alerts/components/UpdateAlertsSnackbar.js
This PR has UpdateAlertsSnackbar use hooks
Part of #923
> ui/hooks: update alerts snackbar

- web/src/app/services/HeartbeatMonitorForm.tsx
- web/src/app/util/NumberField.tsx
Pulling in the `NumberField` component into master from the `feature/temp-schedules` branch to fix failing heartbeat integration tests.
> ui/utils: NumberField component

- web/src/app/alerts/components/AlertsListControls.js
This PR has AlertsListControls use hooks
Part of #923
> ui/hooks: alert list controls

- web/src/app/alerts/pages/AlertDetailPage.js
This PR has AlertDetailPage using hooks
Part of #923
> ui/hooks: alert detail page

- web/src/app/dialogs/components/DialogContentError.js
Converts dialogContentError.js to use hooks.
Part of #923
> ui/hooks: dialog content error

- web/src/app/dialogs/components/DialogTitleWrapper.js
Converted dialogTitleWrapper.js to use hooks.
Part of #923
> ui/hooks: dialog title wrapper

- web/src/app/error-pages/Errors.js
Converts PageNotFound, ObjectNotFound, and GenericError to functions.
Part of #923
> ui/hooks: convert errors 

- web/src/app/main/App.js
- web/src/app/selectors/auth.ts
- web/src/app/selectors/index.js
Use hooks in main/App.js
Part of #923
> ui/hooks: App

- web/src/app/escalation-policies/PolicyCreateDialog.js
Converts PolicyCreateDialog.js to use hooks.
Part of #923
> ui/hooks: policy create dialog

- devtools/ci/dockerfiles/build-env/Dockerfile
Update the `goalert/build-env` image to use the latest version of Go
> dev: update Go version to 1.15.4

- web/src/app/documentation/components/IntegrationKeyAPI.js
converted class component to hook for IntegrationKeyAPI.js
Part of https://github.com/target/goalert/issues/923
> ui/hooks: IntegrationKeyAPI

- web/src/app/escalation-policies/PolicyForm.js
Converts PolicyForm.js to use hooks.
Part of #923
> ui/hooks: policy form

- web/src/app/escalation-policies/PolicyServicesCard.js
Converts PolicyServicesCard.js to use hooks.
Part of #923
> ui/hooks: policy services card

- web/src/app/main/components/SideBarDrawerList.js
Use hooks for SideBarDrawerList
Part of #923
> ui/hooks: sidebar drawer list

- web/src/app/escalation-policies/PolicyServicesQuery.js
Please include a description of the proposed changes.
Converts PolicyServicesQuery.js to use hooks.
Part of #923
> ui/hooks: policy services query

- web/src/app/icons/components/Icons.js
- web/src/app/styles/materialStyles.js
converted class components to hooks in Icons.js
Part of https://github.com/target/goalert/issues/923
> ui/hooks: Icons

- devtools/ci/dockerfiles/build-env/Dockerfile
Update to the latest version of Go
> dev: update build-env to 1.15.5

- web/src/app/schedules/ScheduleShiftList.js
This PR converts ScheduleShiftList to hooks
Part of #923 
Prereq for #955
> ui/hooks: schedule shift list

- web/src/package.json
- web/src/yarn.lock
Removes extraneous `except` node module. We can use `_.omit()` instead.
> ui: remove except package

- web/src/app/escalation-policies/PolicyStepCreateDialog.js
Converts PolicyStepCreateDialog.js to use hooks.
Part of #923
> ui/hooks: policy step create dialog

- web/src/app/escalation-policies/PolicyStepsQuery.js
Converts PolicyStepsQuery.js to use hooks.
Part of #923
> ui/hooks: policy steps query

- web/src/app/escalation-policies/PolicyStepForm.js
Converts PolicyStepForm.js to use hooks.
Part of #923
> ui/hooks: policy step form

- web/src/app/escalation-policies/PolicyStep.js
Converts PolicyStep.js to use hooks.
Part of #923
> ui/hooks: policy step

- web/src/app/main/components/ToolbarAction.js
Convert ToolbarAction.js to hooks
Part of #923
> ui/hooks: toolbar action

- web/src/app/util/FilterContainer.js
Convert FilterContainer.js to hooks
Part of #923
> ui/hooks: filter container

- web/src/app/escalation-policies/PolicyStepsCard.js
- web/src/app/styles/materialStyles.js
Converts PolicyStepCard.js to use hooks.
Part of #923
> ui/hooks: policy step card

- Makefile
- devtools/ci/dockerfiles/goalert/Dockerfile
This PR fixes our CI docker build issues.
> docker: ci build fixes

- engine/rotationmanager/advance.go
- engine/rotationmanager/update.go
- schedule/rotation/store.go
- smoketest/harness/backend.go
This PR logs a warning message if a rotation advances unexpectedly outside the bounds of the specified threshold (15 minutes)
> rotations: warn of unexpected rotation advancement

- mobile/README.md
- mobile/package.json
- mobile/yarn.lock
We can bundle expo-cli similar to how we use cypress so that developers never have a version mismatch
> mobile: bundle expo-cli

- app/cmd.go
- docs/getting-started.md
Adds clarification to use of the `--data-encryption-key` flag and adds a subsection in the Getting Started guide to make it more prominent.
> cmdline: make use of data-encryption-key flag more clear

- docs/getting-started.md
This PR updates our Getting Started Guide to include updated configuration info for Slack integration.
> docs: update slack config info

- .dependabot/config.yml
- web/src/package.json
- yarn.lock
This PR fixes an issue that manifests in development that was introduced in #1180 
This PR also has dependabot ignore `react`, `react-dom`, and `@hot-loader/react-dom` which should not be upgraded on an individual basis
> ui: fix dependency regression in @hot-loader/react-dom

- smoketest/graphqlmultiplealerts_test.go
- smoketest/prioritization_test.go
Adds an additional fast-forward during the multi-alert test to account for new throttling rules.
> smoketest: account for throttling

- graphql2/graphqlapp/app.go
- graphql2/graphqlapp/playground.go
- web/src/cypress/integration/playground.ts
Updates graphql playground dependency from `graphql-playground-react` to `@apollographql/graphql-playground-react`.
Fixes #1040
> graphql/playground: fix graphql playground schema

- notification/twilio/carrier.go
- remotemonitor/monitor.go
This PR fixes Twilio signature validation for the remote monitor and fixes a subsequent crash.
> remote monitor: set url props so validation passes

- web/src/app/admin/AdminNumberLookup.tsx
- prevents default behavior of admin twilio carrier lookup form button
Fixes #1209
> toolbox: fix twilio number lookup in firefox

- docs/development-setup.md
This PR updates our development setup guide to require Go 1.15+ (when [tzdata package was embedded](https://golang.org/doc/go1.15)).
> docs: update go version requirement

- web/src/app/dialogs/FormDialog.js
- web/src/app/util/gracefulUnmount.js
- Refactors `@gracefulUnmount` as an higher order component
- Refactors FormDialog to use hooks
Part of #923
> ui/hooks: form dialog

- notification/slack/channel.go
I quickly prototyped this in Block Kit Builder for my own experimentation and realized I should just suggest the code change to accompany [my comment][1] on #19.
[1]: https://github.com/target/goalert/issues/19#issuecomment-775372619
N.b. I made this change in GitHub, so I didn't run any tests. I did use the Block Kit Builder to [prototype it](https://app.slack.com/block-kit-builder/T03SVRWU0#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Hello,%20Assistant%20to%20the%20Regional%20Manager%20Dwight!%20*Michael%20Scott*%20wants%20to%20know%20where%20you'd%20like%20to%20take%20the%20Paper%20Company%20investors%20to%20dinner%20tonight.%5Cn%5Cn%20*Please%20select%20a%20restaurant:*%22%7D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22secti …
> Adds some color and emoji to the Slack alert buttons

- web/src/app/documentation/components/IntegrationKeyAPI.js
- web/src/app/util/Markdown.js
- web/src/cypress/integration/markdown.ts
- web/src/package.json
- yarn.lock
This PR fixes a regression with rendering tables with `react-markdown`. It now requires a separate dependency, `remark-gfm`
Fixes: #1244
> ui: fix markdown table rendering

- web/src/app/alerts/components/AlertDetails.js
Ensures listed assignments on the alert details EP section are sorted alphabetically. Previously it would cause instances of flicker as the item order could change from one request to the next.
> web/alert: sort entities in alert details EP list

- web/src/app/services/ServiceLabelForm.js
[x] Identified the issue which this PR solves.
[x] Read the CONTRIBUTING document.
[x] Code builds clean without any errors or warnings.
[x] Added appropriate tests for any new functionality.
[x] All new and existing tests passed.
[x]Added comments in the code, where necessary.
[x]Ran make check to catch common errors. Fixed any that came up.
Description:
Converted serviceLabelForm.js to use hooks
Which issue(s) this PR fixes:
Part of #923
> ui/hooks: serviceLabelForm.js

- web/src/app/schedules/util.js
Fixes an issue causing the TimePickers test to fail in CI
> use timezone from function params

- Makefile
- devtools/runjson/localdev-cypress-prod.json
- devtools/runjson/localdev-cypress.json
This PR has local environments use postgres 13 (was previously 11)
The following may help current developers upgrade their local setup:
```sh
docker stop $(docker container ls -q --filter name=goalert-postgres)
docker rm $(docker container ls -qa --filter name=goalert-postgres)
make clean postgres regendb
```
> db: bump to postgres 13

- devtools/ci/dockerfiles/build-env/Dockerfile
Updates Go to version 1.16.2
https://github.com/golang/go/issues/44618
> update to Go 1.16.2

- web/src/app/util/PageActions.js
Converted PageActions to use hooks
Part of #923
> ui/hooks: page actions

- web/src/app/main/components/ToolbarTitle.js
Converts ToolbarTitle.js to use hooks.
- Includes NameLoader and ToolbarTitle
Part of #923
> ui/hooks: toolbar title

- web/src/app/schedules/ScheduleTZFilter.js
Adds time zone abbreviation in ScheduleTZFilter.js
Fixes #1066
> ui: add time zone abbriviation in filter

- web/src/app/lists/FlatList.tsx
- web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
- Fixes bug where no coverage notices were not rendering properly in the shift list
- Fixes bug where shifts weren't splitting when overlapping multiple days.
> temp-schedules: fix shift list transitions

- web/src/app/schedules/CalendarEventWrapper.js
- web/src/app/schedules/ScheduleCalendar.js
- web/src/app/schedules/temp-sched/TempSchedAddShiftsStep.tsx
- web/src/app/schedules/temp-sched/TempSchedTimesStep.tsx
- Adds an Edit button on individual user shifts in a temporary schedule.
- Shortens the dialog text
> temp-schedules: Add Edit Button & Shorten Text

- web/src/app/dialogs/FormDialog.js
This PR fixes an issue where the toolbar was not being rendered for the temp schedules form dialog. It will now render correctly, as shown below:
> feature/temp sched: show toolbar in form dialog

- engine/schedulemanager/db.go
- migrate/migrations/20210420100139-sched-module-v3.sql
Bumping schedule module to version `3` with the addition/requirement of processing temporary schedules.
> engine: bump schedule module to v3 for temp schedule support

- web/src/app/lists/FlatList.tsx
- web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
Updates FlatList to support scrolling new shifts into view.
https://user-images.githubusercontent.com/595010/115597225-a9121880-a29e-11eb-99b9-527d4070c9f8.mp4
https://user-images.githubusercontent.com/595010/115597227-a9121880-a29e-11eb-9b85-b2226a2ef20d.mp4
> temp-schedules: scroll new shifts into view

- web/src/app/loading/components/LoadingButton.js
- web/src/app/rotations/UserForm.js
Refactored `app/loading/components/LoadingButton.js` to use hooks.
Also fixed a typo in `web/src/app/rotations/UserForm.js`
Part of #923
> Refactoring LoadingButton.js to use hooks and fixing a typo

- web/src/app/rotations/RotationUserDeleteDialog.js
Refactored `web/src/app/rotations/RotationUserDeleteDialog.js` to use hooks.
Part of #923
> Refactoring RotationUserDeleteDialog to use hooks

- web/src/app/escalation-policies/PolicyEditDialog.js
Patches a null check causing test failures in Cypress.
> cypress: patch falsey test

- web/src/app/rotations/RotationSetActiveDialog.js
Refactored `web/src/app/rotations/RotationSetActiveDialog.js` to use hooks.
Part of #923
> Refactoring RotationSetActiveDialog to use hooks

- web/src/app/rotations/RotationAddUserDialog.js
Refactored `web/src/app/rotations/RotationAddUserDialog.js` to use hooks.
Part of #923
> Refactoring RotationAddUserDialog to use hooks

- web/src/app/rotations/RotationCreateDialog.js
- web/src/app/rotations/RotationDetails.js
- web/src/app/rotations/RotationUserList.js
- refactors the RotationUserList in hooks
- handles loading and error states
Part of #923
> ui/hooks: rotation user list

- web/src/app/users/UserContactMethodList.js
- web/src/app/users/UserDeleteDialog.tsx
- web/src/app/users/UserDetails.js
- web/src/cypress/integration/profile.ts
- web/src/cypress/integration/users.ts
The provides a UI for admins to delete users
Part of #1247 
Admins will see a "DELETE" button in the app bar on user pages
> ui/users: user delete dialog

- web/src/app/main/App.js
- web/src/app/main/WideSideBar.tsx
- web/src/app/main/components/NavSubMenu.js
- web/src/app/main/components/SideBarDrawerList.js
- web/src/app/styles/materialStyles.js
- web/src/global.d.ts
This PR updates the navbar layout to fit the Material design spec.
Closes #1497
- Navbar is now full-height
- GoAlert logo slightly increased in size
- Using non-scaled version of GoAlert logo (was on the verge of looking blurry on my end)
- Styling of list item states has changed (navbar only)
> ui: fix navbar design

- web/src/app/schedules/CalendarToolbar.tsx
- web/src/app/schedules/ScheduleCalendar.js
- web/src/cypress/integration/scheduleCalendar.ts
This PR makes CalendarToolbar responsible for managing the schedule calendar state
Closes #1489
> ui/schedules: CalendarToolbar refactor

- web/src/app/users/UserSessionList.tsx
This PR adds a note when a user has no active sessions
> ui/users: empty message for active sessions list view

- smoketest/statusinprogress_test.go
Adds coverage for in-progress status notifications in prep for refactoring some of the notification package.
> smoketest: in-progress status notifications coverage

- web/src/app/schedules/CalendarToolbar.tsx
- web/src/app/schedules/ScheduleCalendar.js
- web/src/app/schedules/hooks.ts
Refactors ScheduleCalendar as functional component
Part of #923 
Another iteration towards #1428
> ui/hooks: schedule calendar

- assignment/targettype.go
Adds text marshaling methods for `assignment.TargetType` so it can be stored/parsed from JSON.
> assignment: add text methods to targettype

- app/concurrencylimiter.go
- app/concurrencylimiter_test.go
Fixes some potential deadlock and race conditions with the old implementation and switches to using `container/list.List`
> app: Concurrency limiter refactor

- web/src/app/schedules/ScheduleRuleList.js
Converts ScheduleRuleList.js to hooks.
Part of #923
> ui/hooks: schedule rule list

- user/search.go
Fixes an issue where searching by phone number could return duplicate user results
> user search: omit duplicate users when searching by number

- web/src/app/util/OtherActionsDesktop.js
Hello there,
The therActionsMenuComponent class component is refactored to a functional component.
Please have a look at it and make any necessary suggestions.
Find the branch [here](https://github.com/Voninkazo/goalert/tree/other-actions-menu-desktop).
Thank you in advance!
> ui/hooks: OtherActionsMenuDesktop

- web/src/app/schedules/ScheduleRuleDeleteDialog.js
Hey team,
I have converted the class component in this issue to a functional component. So, check it out when you have time.
Thanks,
Converting a class component to a functional component 
Part of #923
> ui/hooks: ScheduleRuleDeleteDialog

- web/src/app/schedules/ScheduleForm.js
Converts Schedule form into hooks 
Part of #923
> ui/hooks: ScheduleForm

- web/src/app/schedules/ScheduleRouter.js
Refactoring this class component to a functional component. 
Usage: Part of #923
Include any out of scope items here.
> ui/hooks: ScheduleList

- engine/schedulemanager/db.go
- engine/schedulemanager/update.go
Fixes a regression where a schedule with configured on-call notification(s), but no assignments/rules would result in a panic causing the engine to skip schedule processing.
This happens because timezone information is only loaded with schedule rules, but is required for on-call notifications as well.
This PR fixes the problem by ensuring timezone information for ALL schedules is loaded before processing, rather than only those with rules associated with them.
**Steps to Reproduce/Validate**
1. Create a schedule with no rules/assignments
2. Add on-call notification
3. Observe error in logs, and other schedules will no longer update on-call users
Future work will focus on isolating schedule processing so a single schedule won't cause the entire module to …
> engine/schedule: fix panic on notification without assignment/rules

- web/src/app/schedules/ScheduleAssignedToList.js
Converts Schedule assign to list into hooks 
Part of #923
> ui/hooks: ScheduleAssignedToList

- web/src/app/users/UserContactMethodEditDialog.js
Refactoring UserContactMethodEditDialog class component to a functional component and removing unused code
Part of #923
> ui/hooks: UserContactMethodEditDialog

- web/src/app/util/OtherActionsMobile.js
Refactoring the OtherActionsMenuMobile class component to functional component.
You can find the branch in this [link](https://github.com/Voninkazo/goalert/tree/other-actions-menu-mobile)
Usage: Part of #923
> ui/hooks: OtherActionsMobile

- web/src/app/schedules/ScheduleCreateDialog.js
Converts Schedule create dialog into hooks 
Part of #923
> ui/hooks: ScheduleCreateDialog

- web/src/app/util/OtherActions.js
Hello there,
The OtherActions class component is refactored to a functional component.
Please have a look at it and make any necessary suggestions.
Find the branch [here](https://github.com/Voninkazo/goalert/tree/other-actions).
Thank you in advance!
> ui/hooks: OtherActions

- web/src/app/schedules/ScheduleEditDialog.js
- web/src/app/services/ServiceLabelDeleteDialog.js
Converts Schedule edit dialog into hooks 
Part of #923
> ui/hooks: ScheduleEditDialog

- web/src/app/schedules/ScheduleOverrideDeleteDialog.js
Refactoring the Schedule override delete dialog class component to a functional component.
Part of #923
> ui/hooks: ScheduleOverrideDeleteDialog

- web/src/app/services/IntegrationKeyCreateDialog.js
Converts IntegrationKeyCreateDialog into hooks 
Part of #923
> ui/hooks: IntegrationKeyCreateDialog

- web/src/app/users/UserContactMethodSelect.js
Refactoring  UserContactMethodSelect class component to a functional component
Part of #923
> ui/hooks: UserContactMethodSelect

- web/src/app/users/UserNotificationRuleCreateDialog.js
Refactoring UserNotificationRuleCreateDialog class component to a regular component and removing an unused state.
Part of #923
> ui/hooks: UserNotificationRuleCreateDialog

- web/src/app/users/UserStatusUpdatePreference.js
Hi there,
The UserStatusUpdatePreference class component is converted to a functional component.
You are welcome to have a look at it and make any feedback!
Thank you in advance!
Converting a class component to a functional component.
One of the #923 issue
> ui/hooks: UserStatusUpdatePreference

- web/src/app/users/UserNotificationRuleDeleteDialog.js
Refactoring UserNotificationRuleDeleteDialog class component to a functional component
Part of #923
> ui/hooks: UserNotificationRuleDeleteDialog

- web/src/app/users/UserNotificationRuleForm.js
Hello there,
The  UserNotificationRuleForm  class component is now refactored to a functional component and unused propTypes are removed from the component.
Please have a look and give any comments for things to improve.
Thanks in advance!
Part of #923
> ui/hooks: UserNotificationRuleForm 

- web/src/app/schedules/ScheduleRuleForm.js
Converts Schedule rule form into hooks 
Part of #923
> ui/hooks: ScheduleRuleForm 

- web/src/app/services/ServiceLabelDeleteDialog.js
Converts this file into hooks
Part of #923
> ui/hooks: ServiceLabelDeleteDialog

- web/src/app/schedules/ScheduleOverrideEditDialog.js
Converts this file into hooks 
Part of #923
> ui/hooks: ScheduleOverrideEditDialog

- web/src/app/services/ServiceLabelList.js
Converts this file into hooks 
Part of #923
> ui/hooks: ServiceLabelList

- web/src/app/users/UserNotificationRuleList.js
Hi there,
The UserNotificationRuleList  is now converted to a functional component and all decorators are changed into hooks.
Please have a look and give any feedback.
Thanks in advance!
Refactoring a class component to a functional component
This is part of the #923 issues
> ui/hooks:   UserNotificationRuleList 

- web/src/app/wizard/WizardRouter.js
Hello all,
I have refactored the wizardRouter class component to a functional component.
Please have a look at it and give any feedback for things to improve.
Here is the [branch](https://github.com/Voninkazo/goalert/tree/wizard-router)
Thanks in advance!
> ui/hooks: WizardRouter

- web/src/app/services/ServiceLabelEditDialog.js
Converts this file into hooks
Part of #923
> ui/hooks: ServiceLabelEditDialog

- web/src/app/util/GoogleAnalytics.js
Fixes import warnings for ReactGA in GoogleAnalytics.js
> fix: import warnings

- web/src/app/selection/MaterialSelect.tsx
Filters selected options from multi-select since they need to be appended to the options list regardless if they are an available option.
Fixes #1877
> ui/materialselect: filter selected on multi-select

- web/src/app/util/MountWatcher.js
This PR converts MountWatcher to a functional component
Part of #923
> ui/hooks: mount watcher

- web/src/app/util/GoogleAnalytics.js
This PR converts GoogleAnalytics to a functional component
Part of #923
> ui/hooks: google analytics

- Makefile.binaries.mk
- devtools/ci/dockerfiles/goalert/Dockerfile.buildx
- devtools/ci/tasks/build-image.yml
- devtools/genmake/template.mk
Fixes a reference in the buildx file and updates the integration bundle to use the same path so that image building is simpler in CI.
> dev: fix integration bundle and dockerfile references

- web/src/app/schedules/calendar/ScheduleCalendarEventWrapper.js
This PR tweaks the replace override description on the schedule calendar. The user's names were interchanged for replace overrides.
For an example override like this
Before:
After the fix:
> ui/schedules: replace override description fix

- schedule/storetemporaryschedules.go
> schedule/storetemporaryschedules: prevent new temp sched from overwriting history

- devtools/ci/dockerfiles/all-in-one/Dockerfile
- devtools/ci/dockerfiles/all-in-one/Dockerfile.buildx
- devtools/ci/dockerfiles/build-env/Dockerfile
- devtools/ci/dockerfiles/goalert/Dockerfile
- devtools/ci/dockerfiles/goalert/Dockerfile.buildx
- devtools/ci/tasks/build-binaries.yml
- devtools/ci/tasks/scripts/codecheck.sh
- devtools/ci/tasks/test-smoketest.yml
This PR bumps versions to go@1.17.2 and alpine@3.14
> dev: bump go and alpine versions

- web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
Fixes a bug with shift transitions that causes multiple other shifts to transition in and out when adding a new shift to an existing temporary schedule.
> ui/temp-sched: fix transitions on edit

- devtools/ci/dockerfiles/all-in-one/Dockerfile
- devtools/ci/dockerfiles/all-in-one/Dockerfile.buildx
- devtools/ci/dockerfiles/build-env/Dockerfile
- devtools/ci/dockerfiles/goalert/Dockerfile
- devtools/ci/dockerfiles/goalert/Dockerfile.buildx
- devtools/ci/tasks/build-binaries.yml
- devtools/ci/tasks/scripts/codecheck.sh
- devtools/ci/tasks/test-smoketest.yml
Update to the latest version of Go.
> Bump Go to 1.17.5

- app/app.go
- app/initstores.go
- dataloader/alertlogstateloader.go
- engine/config.go
- graphql2/graphqlapp/app.go
- notification/recentmessage.go
- notification/store.go
Closes #2142, removing the notification interface in favor of using structs
> notification: convert Store from interface to struct

- alert/legacysearch.go
- alert/search.go
- alert/store.go
- app/app.go
- app/initstores.go
- dataloader/alertloader.go
- engine/config.go
- engine/engine.go
- engine/heartbeatmanager/db.go
- engine/sendmessage.go
- genericapi/config.go
- grafana/grafana.go
- graphql2/graphqlapp/app.go
- mailgun/mailgun.go
- prometheusalertmanager/prometheusalertmanager.go
- site24x7/site24x7.go
Part of an ongoing effort to remove interfaces in favor of DB structs
> alert: convert Store from interface to struct

- web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceSelect.js
- web/src/app/mui.ts
- web/src/app/styles/materialStyles.js
Closes #2120 
Removes use of `adaptV4Theme` and references to colors by number.
> ui: migrate to v5 theme obj

- web/src/cypress/integration/schedules.ts
This PR adds adds a check to wait for the quick links to be present before navigating to/from on-call notifications
> cypress: patch flaky test

- web/src/app/alerts/components/AlertDetails.js
- web/src/app/styles/materialStyles.js
This PR makes the alert details page accessible.
Before:
After:
> ui/theme: fix alert details accessibility

- devtools/ci/dockerfiles/cypress-env/Dockerfile
- devtools/ci/dockerfiles/cypress-env/start_postgres.sh
- devtools/ci/dockerfiles/cypress-env/stop_postgres.sh
- devtools/ci/tasks/test-integration.yml
- web/src/package.json
- yarn.lock
Updates Cypress to `9.5.4` and updates the DB commands for the Postgres update to version 13 (introduced in Cypress `9.5.2`).
> dev: update cypress and db commands

- web/src/app/schedules/ScheduleOverrideForm.js
Use more concise wording when I creating a replace override. 
https://github.com/target/goalert/issues/2319
Before
After
> ui/schedules: make override dialog form label more concise

- web/src/app/admin/admin-message-logs/AdminDebugMessagesLayout.tsx
- web/src/app/admin/admin-message-logs/DebugMessageCard.tsx
- web/src/app/admin/admin-message-logs/DebugMessagesControls.tsx
Updated styling on admin's message logs page to match overall look and feel of other pages. 
https://github.com/target/goalert/issues/2316
Original style: 
Updated style (no details, light mode)
Updated style (no details, dark mode)
Updated style (with details, light mode)
Updated style (with details, dark mode)
> ui/admin: update style for message logs controls

- validation/validate/username.go
Adds `_`, `-`, and `.` to the allowed characters for usernames.
resolves #2325
> users: expand allowed chars in usernames

- app/app.go
- app/initstores.go
- auth/handlerconfig.go
- genericapi/config.go
- grafana/grafana.go
- graphql2/graphqlapp/app.go
- integrationkey/store.go
- mailgun/mailgun.go
- prometheusalertmanager/prometheusalertmanager.go
- site24x7/site24x7.go
Part of an ongoing effort to remove interfaces in favor of DB structs. This PR addresses integrationkey store only. 
Part of https://github.com/target/goalert/issues/2317
> integrationkey: convert Store from interface to struct

- app/app.go
- app/initstores.go
- graphql2/graphqlapp/app.go
- override/search.go
- override/store.go
Part of an ongoing effort to remove interfaces in favor of DB structs. This PR addresses the override store only.
Part of https://github.com/target/goalert/issues/2317
> override: convert Store from interface to struct

- app/app.go
- app/initstores.go
- dataloader/serviceloader.go
- graphql2/graphqlapp/app.go
- service/legacysearch.go
- service/search.go
- service/store.go
Part of an ongoing effort to remove interfaces in favor of DB structs. This PR addresses service store only.
Part of https://github.com/target/goalert/issues/2317
> service: convert Store from interface to struct

- web/src/app/util/Search.js
- web/src/cypress/integration/temporarySchedule.ts
This PR fixes issues where the list page search box may drop typed characters while searching.
> cypress: fix lost input in search.js

- web/src/app/admin/AdminRouter.tsx
Part of an ongoing effort to convert javascript files to typescript.
> ui/admin: convert javascript file to typescript

- web/src/app/forms/FormField.js
- web/src/app/users/UserNotificationRuleForm.tsx
> ui/users: convert UserNotificationRuleForm file to typescript

- web/src/app/alerts/components/AlertsListControls.tsx
- web/src/app/alerts/components/AlertsListFilter.tsx
> ui/alerts: use typescript for alerts list filter and controls

- web/src/app/users/UserNotificationRuleList.tsx
> ui/users: convert UserNotificationRuleList file to typescript

- Makefile
- Procfile.prod
Fix `start-prod`, `cy-wide-prod-run`, and `cy-mobile-prod-run`
> dev: fix localdev commands

- web/src/app/rotations/RotationCreateDialog.tsx
- web/src/app/rotations/RotationForm.js
> ui/rotations: convert RotationCreateDialog to ts

- web/src/app/forms/FormContainer.js
To prevent a large PR with multiple changes, this PR is part of a two step process to convert the file to typescript. This first PR converts the file from a class based component to a function component. The next PR will handle converting the file to TS. 
Related to https://github.com/target/goalert/issues/923
> ui/forms: convert to function component

- web/src/app/rotations/RotationAddUserDialog.tsx
> ui/rotations: convert RotationAddUserDialog file to ts

- web/src/app/schedules/ScheduleDeleteDialog.tsx
> ui/schedules: convert ScheduleDeleteDialog to typescript

- web/src/app/forms/FormContainer.js
Reverts target/goalert#2427
Currently causing dialogs/forms to break in StrictMode
> Revert "ui/forms: convert to function component"

- grafana/grafana.go
This PR adds ImageURL to the alert details, when available, for Grafana-generated alerts.
Grafana <8 (legacy alerting):
Grafana 8+ (unified alerting):
> grafana: add images to grafana alerts (if available)

- web/src/app/rotations/RotationEditDialog.tsx
- web/src/app/urql.ts
- web/src/app/util/errutil.ts
> ui/rotations: convert RotationEditDialog to ts

- engine/schedulemanager/update.go
- graphql2/graphqlapp/contactmethod.go
- graphql2/graphqlapp/schedule.go
- graphql2/graphqlapp/schedulerule.go
- graphql2/graphqlapp/user.go
- graphql2/graphqlapp/useroverride.go
- override/store.go
- sysapiserver/server.go
- user/store.go
- util/errutil/maperror.go
- web/src/app/schedules/ScheduleEditDialog.tsx
This PR adds missing validation for not-found errors around schedules, missing dialog validation errors, and a fix for a possible schedule manager panic by setting the isolation level to `Repeatable Read`.
> schedules: validation error fixes

- web/src/app/users/UserContactMethodDeleteDialog.tsx
> ui/users: convert UserContactMethodDeleteDialog to ts

- web/src/app/rotations/RotationDeleteDialog.tsx
> ui/rotations: convert RotationDeleteDialog to ts and use urql

- web/src/app/util/CountDown.tsx
> ui/util: convert CountDown to ts

- web/src/app/rotations/RotationSetActiveDialog.tsx
> ui/rotations: convert RotationSetActiveDialog to ts and use urql

- web/src/app/services/HeartbeatMonitorStatus.tsx
> ui/services: convert HeartbeatMonitorStatus to ts

- web/src/app/users/UserContactMethodCreateDialog.tsx
- web/src/app/users/UserDetails.tsx
> ui/users: convert UserDetails to ts

- web/src/app/util/CountDown.tsx
This PR adds truncating to time strings. 
Resolves an issue where time strings were showing decimal values. See screenshot:
> ui/util: truncate time strings

- web/src/app/escalation-policies/PolicyServicesQuery.tsx
> ui/escalation-policies: convert PolicyServicesQuery to ts

- web/src/app/escalation-policies/PolicyDetails.tsx
> ui/escalation-policies: convert PolicyDetails to ts

- cmd/goalert-slack-email-sync/main.go
- config/config.go
- permission/permission.go
- user/user.go
Fixed golang linting issues by running `go fmt ./...`
Fixes #2577 
NA
NA
NA
NA
NA
> Fix Linting Issues

- web/src/app/escalation-policies/PolicyStep.tsx
> ui/escalation-policies: convert PolicyStep to ts

- web/src/app/details/DetailsPage.tsx
- web/src/app/services/ServiceDetails.tsx
> ui/services: convert ServiceDetails to ts

- web/src/app/services/IntegrationKeyDeleteDialog.tsx
> ui/services: convert IntegrationKeyDeleteDialog to ts

- web/src/app/schedules/ScheduleRuleEditDialog.js
Removed shouldComponentUpdate function to complete conversion of ScheduleRuleEditDialog from class components to hooks.
**Issue:**
Part of issue #923, building off #1792
> ui/hooks: ScheduleRuleEditDialog

- web/src/app/forms/FormField.js
- web/src/app/rotations/UserForm.tsx
- web/src/app/schedules/ScheduleRuleEditDialog.js
Converting the `UserForm` component to Typescript.
Part of #2318
> ui/rotations: convert UserForm to typescript

- web/src/app/rotations/RotationUserList.tsx
Convert the `RotationUserList` component to Typescript.
Part of #2318
> ui/rotations: convert RotationUserList to typescript

- web/src/app/services/IntegrationKeyForm.tsx
- web/src/package.json
- yarn.lock
Regenerating `yarn.lock` to pull updates for transitive dependencies (e.g., `json5`).
> chore: regen yarn.lock to update deps

- .github/workflows/main.yml
updates node in github actions, fix for failing build
> update node version in github actions

- web/src/package.json
- yarn.lock
updates wonka to latest. patches a TS type issue that affects new generations of our yarn.lock file (see #2767).
> ui/deps: update wonka version to latest, fixes yarn.lock generations

- web/src/app/links/UserLink.tsx
> ui/UserLink: convert to typescript

- web/src/app/links/RotationLink.tsx
> ui/RotationLink: convert to typescript

- web/src/app/util/Time.tsx
Increase the underline offset for readability on the `Time` component
Before:
After:
> ui/Time: increase underline offset

- devtools/mocktwilio/twiml/anyverb.go
- devtools/mocktwilio/twiml/gather.go
- devtools/mocktwilio/twiml/verbs.go
- devtools/mocktwilio/twiml/verbs_test.go
Add remaining verbs: `Pause`, `Redirect`, and `Reject`
> mocktwilio/twiml: add remaining verbs

- test/integration/service.spec.ts
- web/src/cypress/e2e/services.cy.ts
Moves some of the service testing to a new playwright test instead.
Part of #2847 
- Creating service & EP works, searching, editing, and deleting
- Maintenance mode
- Details page info and list page link
> testing: Move some service testing to playwright

- swo/swomsg/log.go
- swo/swosync/logicalsync.go
Adding error checking to the methods in the `swo` folder.
adding any additional complexity to the existing methods.
NA
NA
NA
NA
> feat: adding error checking to the swo methods

- migrate/migrate.go
- remotemonitor/monitor.go
- search/render.go
- util/jsonutil/merge.go
- validation/validate/jmespath_test.go
- validation/validate/phone_test.go
Adding error checks to some misc packages.
adding any complexity to the existing methods.
NA
NA
NA
NA
> feat: adding error checking on misc packages

- engine/compatmanager/update.go
- engine/engine.go
- engine/message/db.go
Adding error checks to methods within the `engine` folder
adding any complexity to existing methods
NA
NA
NA
NA
> feat: add error checks to engine methods

- auth/basic/db.go
This PR lowers the difficulty for new accounts to 12, down from 14, (800ms -> 200ms), and disables concurrent computing hashes to prevent saturating the CPU.
> auth/basic: lower bcrypt difficulty, limit 1 compare at a time

- test/smoke/harness/harness.go
- test/smoke/migrations_test.go
Adding error checks to the methods inside the `tests` folder.
adding any complexity to the methods
NA
NA
NA
NA
> feat: adding error checks to tests folder

- notification/email/sendmail.go
- notification/slack/servemessageaction.go
- notification/twilio/signature.go
- notification/twilio/validation.go
Adding error checks to methods inside of the `notification` folder
adding complexity to existing methods
NA
NA
NA
NA
> feat: adding error checks to notification methods

- web/src/app/alerts/pages/AlertDetailPage.tsx
Conver to typescript.
Part of #2318
> ui/AlertDetailPage: Convert to typescript

- package.json
- web/src/app/admin/admin-alert-counts/AlertCountLineGraph.tsx
- web/src/app/services/AlertMetrics/AlertAveragesGraph.tsx
- web/src/app/services/AlertMetrics/AlertCountGraph.tsx
- web/src/app/worker/methods.ts
- yarn.lock
Updates `prettier` and `stylelint` to the latest versions.
The prettier update adds `()` around `typeof` expressions in a few places.
> dev/ui: Update prettier & stylelint

- Makefile
Fixes "Command not found" being printed when make is run
> dev: fix "Command not found" noise

- .github/dependabot.yml
Updating dependabot to align with Target's Open Source policies.
Target template: https://github.com/target/.github/blob/main/dependabot.yml
> feat: update dependabot for full scanning

- web/src/app/alerts/AlertDetailLogs.tsx
Convert <AlertDetailLogs /> component to typescript.
Part of #2318
> ui/AlertDetailLogs: Convert to typescript

- Makefile
- playwright.config.ts
- Adds `make playwright-ui` to start the Playwright UI for running tests.
- Disables test retries unless running in CI
> dev: playwright tweaks

- README.md
Updates readme with Docker Hub info.
> docs: add docker hub link and nightly image info

- web/src/app/schedules/ScheduleRuleEditDialog.js
Converts the ScheduleRuleEditDialog to use urql and hooks.
Part of #923
- Not doing a TypeScript conversion in this PR to minimize diff.
> ui: convert ScheduleRuleEditDialog to hooks

- devtools/ci/dockerfiles/build-env/Dockerfile
- devtools/ci/dockerfiles/goalert/Dockerfile
- devtools/ci/tasks/build-all.yml
- devtools/ci/tasks/build-binaries.yml
- devtools/ci/tasks/scripts/codecheck.sh
- devtools/ci/tasks/test-smoketest.yml
Updating to the latest version of Go
> go: update Go to 1.20.5

- test/integration/email-cm.spec.ts
- web/src/app/users/UserContactMethodList.tsx
- web/src/app/users/UserDetails.tsx
- web/src/app/users/UserNotificationRuleList.tsx
- web/src/cypress/e2e/profile.cy.ts
- Updates button styling for creating a contact method and adding a notification rule to match the rest of the application, now that all button have been migrated from FABs when on lg or xl screen sizes.
Part of #2693
**Old:**
**New:**
> ui: update button styling on profile

- devtools/ci/dockerfiles/goalert/Dockerfile
- devtools/ci/tasks/build-all.yml
- devtools/ci/tasks/build-binaries.yml
- devtools/ci/tasks/scripts/codecheck.sh
- devtools/ci/tasks/test-smoketest.yml
- go.mod
- go.sum
Update to the latest version of Go
> deps: update to Go 1.21.0

- web/src/app/admin/switchover/AdminSWOStatusCard.tsx
- web/src/app/admin/switchover/AdminSwitchover.tsx
- web/src/app/admin/switchover/AdminSwitchoverGuide.tsx
- web/src/app/admin/switchover/SWONode.tsx
Fixes spacing, fonts, layout, etc... with the Switchover Guide button on the admin page
> swo: Polish the guide/documentation rendering

- devtools/fetchcounts/run.go
- devtools/pgdump-lite/cmd/pgdump-lite/main.go
- devtools/pgdump-lite/dumpdata.go
- devtools/pgdump-lite/dumpschema.go
- devtools/pgdump-lite/pgd/db.go
- devtools/pgdump-lite/pgd/queries.sql.go
- devtools/pgmocktime/mocker.go
- devtools/resetdb/main.go
- devtools/waitfor/main.go
- devtools/waitfor/schemapostgres.go
- go.mod
- go.sum
- sqlc.yaml
- test/smoke/harness/harness.go
- util/sqlutil/rollback.go
Updates all devtools to use pgx5 and the Rollback utility function to support both v4 and v5
> dev: update all devtools to use pgx v5

- docs/development-setup.md
Added the dev connection URL to the setup guide and updated some version numbers.
> dev: add local db url to dev setup guide

- .github/workflows/golangci-lint.yml
Update the linter to use Go 1.21
> dev: update linter to use version of Go used by project

- app/app.go
- app/inithttp.go
- app/initstores.go
- gadb/queries.sql.go
- go.mod
- go.sum
- notifyapi/config.go
- notifyapi/notify.go
- notifyapi/rule.go
- service/rule/queries.sql
- service/rule/store.go
- signal/queries.sql
- signal/signal.go
- signal/store.go
- sqlc.yaml
- Added signal store
- `/notify/incoming` endpoint will create Signals based on rules for the given integration key, if the filters match
NSP-542
- Create Alert for rules
- Rename all instances of 'notify' to 'signal'
- `/notify/incoming` creates the appropriate Signals and returns all Signals created
> feat: signal queue logic

- web/src/app/util/useExpFlag.ts
Adds a `<ExpFlag>` component for conditional rendering based on an experimental flag being enabled.
> ui: add ExpFlag component for conditional rendering

- graphql2/generated.go
- graphql2/gqlgen.yml
- graphql2/graphqlapp/servicerule.go
- graphql2/models_gen.go
- graphql2/schema.graphql
- service/rule/rule.go
- service/rule/store.go
- signalapi/notify.go
- web/src/app/main/AppRoutes.tsx
- web/src/app/services/IntegrationKeyList.tsx
- web/src/app/services/ServiceDetails.tsx
- web/src/app/services/ServiceRules/ServiceRuleCreateDialog.tsx
- web/src/app/services/ServiceRules/ServiceRuleDeleteDialog.tsx
- web/src/app/services/ServiceRules/ServiceRuleEditDialog.tsx
- web/src/app/services/ServiceRules/ServiceRuleForm.tsx
- web/src/app/services/ServiceRules/ServiceRules.tsx
- web/src/app/services/ServiceRules/ServiceRulesList.tsx
- web/src/schema.d.ts
Create UI for signals integration to create, edit, read, and deleted service rules.
https://github.com/target/goalert/issues/3398
internal: https://jira.target.com/browse/NSP-574
> create signal UI (POC)

- service/rule/store.go
- signalapi/signal.go
added signal to alert logic in rules engine
> Go signal to alert logic

- service/rule/store.go
- signalapi/signal.go
adding in the template variable injection for summary and details
> Go signal to alert

- web/src/app/users/UserContactMethodSelect.js
- web/src/app/users/UserContactMethodSelect.tsx
Converts `UserContactMethodSelect` to typescript and to use urql.
Part of #3240 and #2318
> ui: convert UserContactMethodSelect to typescript

- web/src/app/users/UserContactMethodVerificationDialog.js
- web/src/app/users/UserContactMethodVerificationDialog.tsx
Converts `UserContactMethodVerificationDialog` to use urql and ts.
Part of https://github.com/target/goalert/issues/2318 and https://github.com/target/goalert/issues/3240
> ui/profile: convert UserContactMethodVerificationDialog to ts

- web/src/app/users/UserContactMethodCreateDialog.tsx
Converts `UserContactMethodCreateDialog` to use urql.
> ui/profile: convert UserContactMethodCreateDialog to urql

- web/src/app/lists/FlatList.tsx
- web/src/app/services/ServiceOnCallList.js
- web/src/app/services/ServiceOnCallList.tsx
Converts <ServiceOnCallList /> to use typescript and migrates from @apollo/client to urql.
Part of https://github.com/target/goalert/issues/3240 and #2318
Closes #3308
> ui/service: convert ServiceOnCallList to typescript

- web/src/app/users/UserContactMethodCreateDialog.tsx
- web/src/app/users/UserContactMethodVerificationDialog.tsx
Currently user contact methods aren't updating properly when verified, this pr adds missing typenames to the mutations for creating and verifying user contact methods as a fix.
> fix: add missing typenames

- web/src/app/schedules/temp-sched/TempSchedDeleteConfirmation.tsx
- web/src/app/schedules/temp-sched/TempSchedDialog.tsx
- Updates TempSchedDeleteConfirmation and TempSchedDialog to use urql instead of @apollo/client
- Adds `additionalTypenames: ['Schedule']` to the create + delete mutations updated for refetching on complete
> ui: update temp sched dialogs to use urql, add additionalTypenames

- web/src/app/wizard/WizardRouter.js
Updates WizardRouter to use urql instead of @apollo/client
> ui: update WizardRouter to use urql

- test/integration/email-cm.spec.ts
This pull request adds an extra assertion for editing a contact method name and enabling status updates.
https://github.com/target/goalert/issues/3607
N/A
N/A
N/A
N/A
N/A
> users: add assertion for editing contact method

- .github/workflows/codeql.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/main.yml
- devtools/ci/dockerfiles/build-env/Dockerfile
- devtools/ci/dockerfiles/goalert/Dockerfile
- devtools/ci/tasks/build-all.yml
- devtools/ci/tasks/build-binaries.yml
- devtools/ci/tasks/scripts/codecheck.sh
- devtools/ci/tasks/test-smoketest.yml
- go.mod
> dev: update Go to 1.22

- go.mod
https://github.com/golang/go/issues/62278#issuecomment-1933790368
> go: fix toolchain error with go

- Makefile
- docs/development-setup.md
This PR add help documentation for both Playwright and Cypress tests
Fixes #3643.
> Update Makefile and development-setup files

- test/integration/schedules.spec.ts
- web/src/app/schedules/ScheduleShiftList.tsx
Fixes an integration test that fails when America/Chicago changes from CST to CDT.
> dev: CST/CDT changes, use testid

- go.sum
runs `make` to update the `go.sum` file
> chore: update go.sum

- web/src/app/escalation-policies/PolicyStepsCard.tsx
- web/src/app/escalation-policies/stepUtil.tsx
Converts PolicyStepCard to TS, in prep for the always-on dest API change.
- Part of #2639 
- Part of #2318
> ts: convert PolicyStepCard to ts

- web/src/app/users/UserContactMethodList.tsx
- web/src/app/users/UserContactMethodListDest.tsx
Fixes flicker on the user details page when opening dialogs by wrapping in `<Suspense></Suspense>`
Closes #3751
> profile: fix flicker when opening dialogs

- web/src/app/services/ServiceCreateDialog.tsx
- web/src/app/services/ServiceList.tsx
- web/src/app/users/UserList.tsx
Updates ServiceList to use ListPageControls instead of QueryList
- added missing empty message on UserList
> urql: move service list to urql

- web/src/app/escalation-policies/PolicyList.tsx
Updates PolicyList to use ListPageControls instead of QueryList
> urql: move policy list to urql

- web/src/app/schedules/ScheduleList.tsx
Updates ScheduleList to use ListPageControls instead of QueryList
> urql: move schedule list to urql

- test/smoke/harness/harness.go
Removes redundant import in the test harness
> chore: pkg imported more than once

- web/src/app/escalation-policies/PolicyCreateDialog.tsx
- web/src/app/users/UserContactMethodEditDialog.tsx
Updates components to use urql instead of apollo.
- PolicyCreateDialog
- UserContactMethodEditDialog
Part of #3240
> urql: PolicyCreateDialog and UserContactMethodEditDialog

- web/src/cypress/e2e/escalationPolicies.cy.ts
- web/src/cypress/e2e/materialSelect.cy.ts
Part of #3867
Adds pre-flight test changes to help the Dest API work going on
> ui: update material select tests

- app/app.go
- app/inithttp.go
- app/initstores.go
- graphql2/generated.go
- graphql2/graph/destinations.graphqls
- graphql2/graphqlapp/destinationtypes.go
- graphql2/models_gen.go
- integrationkey/uik.go
- integrationkey/uik/handler.go
- web/src/app/selection/DestinationInputDirect.tsx
- web/src/app/storybook/defaultDestTypes.ts
- web/src/app/util/RequireConfig.tsx
- web/src/schema.d.ts
- Extends dest type information to include dynamic parameters for dynamic action destinations
- Moves uik handling to it's own package and implements alert creation support
> uik: add dynamic actions api

- graphql2/exprscalar.go
- graphql2/generated.go
- graphql2/gqlgen.yml
- graphql2/graph/univkeys.graphqls
- graphql2/graphqlapp/integrationkey.go
- graphql2/models_gen.go
- test/smoke/actionvalidate_test.go
- test/smoke/harness/graphql.go
- web/src/app/forms/HelperText.tsx
- web/src/app/selection/DynamicActionForm.tsx
- web/src/schema.d.ts
- Adds new type ExprStringMap (map where the value is a valid Expr expression)
- Switches DynamicParams to use an ExprStringMap (breaking, but behind experimental flag)
- Adds an action validation query `actionInputValidate`
- Updates DynamicActionForm appropriately & fixes an issue with HelperText handling Expr errors
Superseeds #3925
> Update DynamicParams to use ExprStringMap

- web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
- web/src/app/services/UniversalKey/UniversalKeyDefaultActions.tsx
- web/src/app/services/UniversalKey/UniversalKeyRuleForm.tsx
- web/src/app/services/UniversalKey/UniversalKeyRuleRemoveDialog.tsx
- web/src/app/services/UniversalKey/utils.tsx
Adds action dialog, rule form, and remove dialog from the `uik-editor` branch
> Add default action edit and rule management dialogs

- test/integration/uik.spec.ts
- web/src/app/services/UniversalKey/UniversalKeyPage.tsx
- web/src/app/services/UniversalKey/UniversalKeyRuleConfig.tsx
- web/src/app/services/UniversalKey/UniversalKeyRuleCreateDialog.tsx
- web/src/app/services/UniversalKey/UniversalKeyRuleEditDialog.tsx
Adds the ability to add and manage uik rules
> uik: Add ability to edit and manage rules

- gadb/queries.sql.go
- notificationchannel/channel.go
- notificationchannel/queries.sql
- notificationchannel/store.go
- sqlc.yaml
Updates notification channel store to use sqlc.
Part of the work to switch to the new `dest` types.
> Refactor notification channels handling

- gadb/queries.sql.go
- integrationkey/config.go
- integrationkey/queries.sql
- integrationkey/uik/compilerule.go
- integrationkey/uik/compilerule_test.go
Follow up to #3959 adding additional comments, clarification, and a unit test for the Expr builder functionality.
> uik: Enhance channel creation and rule compilation

- README.md
Adds a small "quick start" for local development with the basics.
> Update README with local development instructions

- .github/workflows/migrations.yml
- devtools/scripts/validate-migrations.sh
- Adds validation that existing migrations aren't modified (beyond whitespace)
- Adds validation that new migrations are alphabetically AFTER existing ones
- Adds the `DB Migration` label to PRs that have changes in the `migrate/migrations` directory
> migrate: Add GH action workflow to validate new migrations

- graphql2/schema.graphql
- notification/store.go
- web/src/app/users/SendTestDialog.tsx
- web/src/app/users/UserContactMethodList.tsx
- web/src/app/users/UserContactMethodVerificationDialog.tsx
- web/src/app/util/DestinationAvatar.tsx
This PR refactors the SendTestDialog, fixing issues like these:
The new code displays the time the message was scheduled, as well as the current status, while resolving these issues.
The existing `DestinationInputChip` is used to render the contact method details, ensuring compatibility with current and future destination types.
Marked `formattedValue` as deprecated on `UserContactMethod` type.
> test contact method: Fix verification dialog, and refactor send test dialog

- docs/universal-integration-keys.md
Adds a writeup of the Universal Integration Keys feature
> Add documentation for Universal Integration Keys

- graphql2/generated.go
- graphql2/graph/_Mutation.graphqls
- graphql2/graph/_Query.graphqls
- graphql2/models_gen.go
- graphql2/schema.graphql
Converts schema comments to docstrings that will show up in introspection documentation (e.g., autocomplete and graphql explorer)
> graphql: enhance GraphQL schema documentation for mutations and queries

- README.md
- docs/development-setup.md
- docs/getting-started.md
Updated the development setup guide with more info and to be easier to follow
> readme: update development setup guide

- .gitignore
- .vscode/launch.json
- Procfile.tools
Adds launch configuration for debugging from vscode
> feat: vscode: add launch configuration for debugging

- graphql2/generated.go
- graphql2/graphqlapp/service.go
- graphql2/models_gen.go
- graphql2/schema.graphql
- service/search.go
- service/service_test.go
- test/smoke/graphqlservicesearchonly_test.go
- web/src/schema.d.ts
Please include a description of the proposed changes.
This should include details if the user experience is impacted.
Concise PR description -- part 2 of [this PR](https://github.com/target/goalert/pull/4379)!
also fixes https://github.com/target/goalert/issues/4383
> Feat: ServiceSearch "only"

- web/src/app/services/IntegrationKeyList.tsx
- web/src/app/services/UniversalKey/UniversalKeyPage.tsx
Allows users to open the manage view for externally created universal integration keys without having to look up the integration key id.
For significant amounts of work, it is best to start an issue first, preferably before the work is started.
For large pull requests, be sure to reference the associated GitHub issue(s).
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
Include any out of scope items here.
If introducing any user-facing changes, provide a clear description of them.
If introducing any API changes, provide a clear description of them.
Any additional information or …
> uik: add direct links for externally created uik with warning
